#
# Makefile for tkportaudio<OSS replacement> plugin on Linux / GCC platform
# 
# (c) 2010 Bastian Spiegel <bs@tkscript.de> 
#
#

include ../install_linux.mk

PLUGIN=tkportaudio

EXTRAFLAGS=

EXTRALIBS=

include make.objects

include ../plugin_linux.mk
