#
# Makefile for tkportaudio<OSS replacement> plugin on Linux / GCC / Clang platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#
#

include ../install_linux.mk

PLUGIN=tkportaudio

EXTRAFLAGS=

EXTRALIBS=

include make.objects

include ../build_linux.mk
