// ---- ying_portaudio_PaStreamMacOSWorkgroupJoinToken.cpp: auto generated by YInG - the YAC interface generator (Sat, 21/Jun/2025 21:04:48)

#ifndef YAC_NO_HOST
#endif // YAC_NO_HOST

// ------------------ YAC class "_PaStreamMacOSWorkgroupJoinToken" reflection map (implementation) ------------------
sUI          YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMemberGetNum                  (void) {return 0;}
const char **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMemberGetNames                (void) {return 0;}
const sUI   *YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMemberGetTypes                (void) {return 0;}
const char **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMemberGetObjectTypes          (void) {return 0;}
const sU8  **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMemberGetOffsets              (void) {return (const sU8**)0;}
sUI          YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetNum                  (void) {return 1;}
const char **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetNames                (void) {
#ifndef YAC_NO_HOST
static const char *r[]={"operator"}; return r;
#else
return 0;
#endif // YAC_NO_HOST
}
const sUI   *YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetNumParameters        (void) {
#ifndef YAC_NO_HOST
static const sUI r[]={2}; return r;
#else
return 0;
#endif // YAC_NO_HOST
}
const sUI  **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetParameterTypes       (void) {
#ifndef YAC_NO_HOST
static const sUI rt0[]={1,3};static const sUI *r[]={rt0}; return r;
#else
return 0;
#endif // YAC_NO_HOST
}
const char***YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetParameterObjectTypes (void) {
#ifndef YAC_NO_HOST
static const char *rs0[]={0,"",};static const char**r[]={rs0}; return r;
#else
return 0;
#endif // YAC_NO_HOST
}
const sUI   *YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetReturnTypes          (void) {
#ifndef YAC_NO_HOST
static const sUI r[]={4}; return r;
#else
return 0;
#endif // YAC_NO_HOST
}
const char **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetReturnObjectTypes    (void) {
#ifndef YAC_NO_HOST
static const char *r[]={""}; return r;
#else
return 0;
#endif // YAC_NO_HOST
}
const void **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacMethodGetAdr                  (void) {
#ifndef YAC_NO_HOST
static const void *r[]={(void*)Object__operator}; return r;
#else
return 0;
#endif // YAC_NO_HOST
}
sUI          YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacConstantGetNum                (void) {return 0;}
const char **YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacConstantGetNames              (void) {static const char*r[]={""}; return r;}
const sUI   *YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacConstantGetTypes              (void) {static const sUI r[]={0}; return r;}
yacmemptr    YAC_VCALL _PaStreamMacOSWorkgroupJoinToken::yacConstantGetValues             (void) {static sUI r[]={0,};yacmemptr m; m.ui=(sUI*)r; return m;}

YAC_C(_PaStreamMacOSWorkgroupJoinToken, "PaStreamMacOSWorkgroupJoinToken");

#ifndef YAC_NO_HOST
#endif // YAC_NO_HOST
