#
# Makefile for tkclap plugin + Microsoft Visual C++
# 
# (c) 2024 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkclap

EXTRAFLAGS= 

EXTRALIBS= user32.lib gdi32.lib

PLAF_OBJ= \
	tkclap_window_win32.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include ../plugin_msvc.mk
