#
# Makefile for tkclap plugin on Windows / Visual C++ platform
#
# (c) 2024-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkclap

EXTRAFLAGS=

EXTRALIBS= user32.lib gdi32.lib

PLAF_OBJ= \
	tkclap_window_win32.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include ../build_msvc.mk
