// ---- ying_clap.h: auto generated by YInG - the YAC interface generator (Thu, 9/Apr/2026 17:37:38)
extern sUI clid_CLAPPluginBundle;
extern sUI clid_CLAPPlugin;
class CLAPPluginBundle;
class CLAPPlugin;
YAC_APIC void  YAC_CALL __APIC__tkclap_set_bpm(yacmemptr           );
YAC_APIC void  YAC_CALL __APIC__tkclap_set_song_pos_beats(yacmemptr);
