#
# Makefile for eqxmms plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2003-2009 Bastian Spiegel <bs@tkscript.de> 
#

FORCE_NO_WINDDK=y

include ../install_msvc.mk

PLUGIN=eqxmms

EXTRAFLAGS=

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
