#
# Makefile for eqxmms plugin on macOS
# 
# (c) 2003-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=eqxmms

EXTRAFLAGS=

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
