#
# Makefile for eqxmms plugin on Linux / GCC platform
# 
# (c) 2003-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=eqxmms

EXTRAFLAGS=

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_linux.mk
