#
# Makefile for tkdist2d plugin + MingW / GCC
# 
# (c) 2003-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tkdist2d

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_mingw.mk
