#
# Makefile for tkfreeverb plugin on macOS / GCC platform
# 
# (c) 2009-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tkfreeverb

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
