#
# Makefile for tkfreeverb plugin on Linux / GCC platform
# 
# (c) 2009-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkfreeverb

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_linux.mk
