#
# Makefile for tkfreeverb plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2010 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkfreeverb

EXTRAFLAGS= -fp:fast

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
