#
# Makefile for tkfreeverb plugin on Windows / Visual C++ platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkfreeverb

EXTRAFLAGS= -fp:fast

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
