#
# Makefile for tkfreeverb plugin on Linux / GCC / Clang platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkfreeverb

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_linux.mk
