// ---- auto-generated by tkscript::EntityTree - do not edit!
sUI tks_entity_tree_getIDByString(YAC_String *_s) {
   if(!_s) return 0;
   sUI l=_s->length;
   if( (l<2) || (l>(EntityTree_MAX_LENGTH-1)) ) return 0;
   if(!_s->chars) return 0;
   sU8 *s=_s->chars;
   switch(l-1) {
      case 1:
         if(s[0]=='!')return 45;
         else if(s[0]=='%')return 31;
         else if(s[0]=='&')return 37;
         else if(s[0]=='(')return 12;
         else if(s[0]==')')return 13;
         else if(s[0]=='*')return 29;
         else if(s[0]=='+')return 27;
         else if(s[0]==',')return 7;
         else if(s[0]=='-')return 28;
         else if(s[0]=='.')return 6;
         else if(s[0]=='/')return 30;
         else if(s[0]==':')return 52;
         else if(s[0]==';')return 9;
         else if(s[0]=='<')return 48;
         else if(s[0]=='=')return 43;
         else if(s[0]=='>')return 50;
         else if(s[0]=='?')return 51;
         else if(s[0]=='@')return 111;
         else if(s[0]=='E')return 79;
         else if(s[0]=='[')return 53;
         else if(s[0]==']')return 54;
         else if(s[0]=='^')return 38;
         else if(s[0]=='{')return 10;
         else if(s[0]=='|')return 35;
         else if(s[0]=='}')return 11;
         else if(s[0]=='~')return 46;
         break;
      case 2:
         if(s[0]=='!') {
            if(s[1]=='=')return 44;
         }
         else if(s[0]=='#') {
            if(s[1]=='(')return 55;
            else if(s[1]=='[')return 56;
         }
         else if(s[0]=='%') {
            if(s[1]=='=')return 21;
         }
         else if(s[0]=='&') {
            if(s[1]=='&')return 36;
            else if(s[1]=='=')return 25;
         }
         else if(s[0]=='*') {
            if(s[1]=='=')return 19;
         }
         else if(s[0]=='+') {
            if(s[1]=='+')return 14;
            else if(s[1]=='=')return 17;
         }
         else if(s[0]=='-') {
            if(s[1]=='-')return 15;
            else if(s[1]=='=')return 18;
            else if(s[1]=='>')return 16;
         }
         else if(s[0]=='.') {
            if(s[1]=='.')return 68;
         }
         else if(s[0]=='/') {
            if(s[1]=='*')return 4;
            else if(s[1]=='/')return 5;
            else if(s[1]=='=')return 20;
         }
         else if(s[0]==':') {
            if(s[1]==':')return 39;
         }
         else if(s[0]==';') {
            if(s[1]==';')return 8;
         }
         else if(s[0]=='<') {
            if(s[1]=='<')return 32;
            else if(s[1]=='=')return 47;
         }
         else if(s[0]=='=') {
            if(s[1]=='=')return 40;
            else if(s[1]=='>')return 41;
         }
         else if(s[0]=='>') {
            if(s[1]=='=')return 49;
            else if(s[1]=='>')return 33;
         }
         else if(s[0]=='P') {
            if(s[1]=='I')return 85;
         }
         else if(s[0]=='^') {
            if(s[1]=='=')return 26;
         }
         else if(s[0]=='d') {
            if(s[1]=='o')return 60;
         }
         else if(s[0]=='i') {
            if(s[1]=='f')return 57;
         }
         else if(s[0]=='|') {
            if(s[1]=='=')return 24;
            else if(s[1]=='|')return 34;
         }
         break;
      case 3:
         if(s[0]=='1') {
            if(s[1]=='P') {
               if(s[2]=='I')return 82;
            }
         }
         else if(s[0]=='2') {
            if(s[1]=='P') {
               if(s[2]=='I')return 84;
            }
         }
         else if(s[0]=='<') {
            if(s[1]=='<') {
               if(s[2]=='=')return 22;
            }
            else if(s[1]=='=') {
               if(s[2]=='>')return 42;
            }
         }
         else if(s[0]=='>') {
            if(s[1]=='>') {
               if(s[2]=='=')return 23;
            }
         }
         else if(s[0]=='P') {
            if(s[1]=='I') {
               if(s[2]=='2')return 83;
            }
         }
         else if(s[0]=='f') {
            if(s[1]=='o') {
               if(s[2]=='r')return 59;
            }
         }
         else if(s[0]=='i') {
            if(s[1]=='n') {
               if(s[2]=='t')return 69;
            }
         }
         else if(s[0]=='n') {
            if(s[1]=='e') {
               if(s[2]=='w')return 91;
            }
         }
         else if(s[0]=='t') {
            if(s[1]=='a') {
               if(s[2]=='g')return 96;
            }
            else if(s[1]=='r') {
               if(s[2]=='y')return 116;
            }
         }
         else if(s[0]=='u') {
            if(s[1]=='s') {
               if(s[2]=='e')return 90;
            }
         }
         break;
      case 4:
         if(s[0]=='L') {
            if(s[1]=='N') {
               if(s[2]=='1') {
                  if(s[3]=='0')return 81;
               }
            }
         }
         else if(s[0]=='b') {
            if(s[1]=='o') {
               if(s[2]=='o') {
                  if(s[3]=='l')return 69;
               }
            }
            else if(s[1]=='y') {
               if(s[2]=='t') {
                  if(s[3]=='e')return 69;
               }
            }
         }
         else if(s[0]=='c') {
            if(s[1]=='a') {
               if(s[2]=='s') {
                  if(s[3]=='e')return 66;
               }
            }
            else if(s[1]=='h') {
               if(s[2]=='a') {
                  if(s[3]=='r')return 69;
               }
            }
         }
         else if(s[0]=='e') {
            if(s[1]=='l') {
               if(s[2]=='s') {
                  if(s[3]=='e')return 58;
               }
            }
            else if(s[1]=='n') {
               if(s[2]=='u') {
                  if(s[3]=='m')return 93;
               }
            }
         }
         else if(s[0]=='l') {
            if(s[1]=='o') {
               if(s[2]=='o') {
                  if(s[3]=='p')return 89;
               }
            }
         }
         else if(s[0]=='n') {
            if(s[1]=='u') {
               if(s[2]=='l') {
                  if(s[3]=='l')return 75;
               }
            }
         }
         else if(s[0]=='t') {
            if(s[1]=='h') {
               if(s[2]=='i') {
                  if(s[3]=='s')return 99;
               }
            }
            else if(s[1]=='r') {
               if(s[2]=='u') {
                  if(s[3]=='e')return 76;
               }
            }
         }
         else if(s[0]=='v') {
            if(s[1]=='o') {
               if(s[2]=='i') {
                  if(s[3]=='d')return 74;
               }
            }
         }
         break;
      case 5:
         if(s[0]=='A') {
            if(s[1]=='r') {
               if(s[2]=='r') {
                  if(s[3]=='a') {
                     if(s[4]=='y')return 120;
                  }
               }
            }
         }
         else if(s[0]=='L') {
            if(s[1]=='O') {
               if(s[2]=='G') {
                  if(s[3]=='1') {
                     if(s[4]=='0')return 80;
                  }
               }
            }
         }
         else if(s[0]=='S') {
            if(s[1]=='Q') {
               if(s[2]=='R') {
                  if(s[3]=='T') {
                     if(s[4]=='2')return 88;
                  }
               }
            }
         }
         else if(s[0]=='b') {
            if(s[1]=='r') {
               if(s[2]=='e') {
                  if(s[3]=='a') {
                     if(s[4]=='k')return 67;
                  }
               }
            }
         }
         else if(s[0]=='c') {
            if(s[1]=='a') {
               if(s[2]=='t') {
                  if(s[3]=='c') {
                     if(s[4]=='h')return 117;
                  }
               }
            }
            else if(s[1]=='l') {
               if(s[2]=='a') {
                  if(s[3]=='s') {
                     if(s[4]=='s')return 62;
                  }
               }
            }
         }
         else if(s[0]=='d') {
            if(s[1]=='e') {
               if(s[2]=='r') {
                  if(s[3]=='e') {
                     if(s[4]=='f')return 100;
                  }
               }
            }
         }
         else if(s[0]=='f') {
            if(s[1]=='a') {
               if(s[2]=='l') {
                  if(s[3]=='s') {
                     if(s[4]=='e')return 77;
                  }
               }
            }
            else if(s[1]=='l') {
               if(s[2]=='o') {
                  if(s[3]=='a') {
                     if(s[4]=='t')return 70;
                  }
               }
            }
         }
         else if(s[0]=='l') {
            if(s[1]=='o') {
               if(s[2]=='c') {
                  if(s[3]=='a') {
                     if(s[4]=='l')return 97;
                  }
               }
            }
         }
         else if(s[0]=='m') {
            if(s[1]=='a') {
               if(s[2]=='y') {
                  if(s[3]=='b') {
                     if(s[4]=='e')return 78;
                  }
               }
            }
         }
         else if(s[0]=='s') {
            if(s[1]=='h') {
               if(s[2]=='o') {
                  if(s[3]=='r') {
                     if(s[4]=='t')return 69;
                  }
               }
            }
         }
         else if(s[0]=='t') {
            if(s[1]=='h') {
               if(s[2]=='r') {
                  if(s[3]=='o') {
                     if(s[4]=='w')return 119;
                  }
               }
            }
         }
         else if(s[0]=='w') {
            if(s[1]=='h') {
               if(s[2]=='i') {
                  if(s[3]=='l') {
                     if(s[4]=='e')return 61;
                  }
               }
            }
         }
         break;
      case 6:
         if(s[0]=='1') {
            if(s[1]=='S') {
               if(s[2]=='Q') {
                  if(s[3]=='R') {
                     if(s[4]=='T') {
                        if(s[5]=='2')return 87;
                     }
                  }
               }
            }
         }
         else if(s[0]=='O') {
            if(s[1]=='b') {
               if(s[2]=='j') {
                  if(s[3]=='e') {
                     if(s[4]=='c') {
                        if(s[5]=='t')return 71;
                     }
                  }
               }
            }
         }
         else if(s[0]=='S') {
            if(s[1]=='t') {
               if(s[2]=='r') {
                  if(s[3]=='i') {
                     if(s[4]=='n') {
                        if(s[5]=='g')return 72;
                     }
                  }
               }
            }
         }
         else if(s[0]=='d') {
            if(s[1]=='e') {
               if(s[2]=='f') {
                  if(s[3]=='i') {
                     if(s[4]=='n') {
                        if(s[5]=='e')return 94;
                     }
                  }
               }
            }
         }
         else if(s[0]=='m') {
            if(s[1]=='e') {
               if(s[2]=='t') {
                  if(s[3]=='h') {
                     if(s[4]=='o') {
                        if(s[5]=='d')return 104;
                     }
                  }
               }
            }
            else if(s[1]=='o') {
               if(s[2]=='d') {
                  if(s[3]=='u') {
                     if(s[4]=='l') {
                        if(s[5]=='e')return 98;
                     }
                  }
               }
            }
         }
         else if(s[0]=='p') {
            if(s[1]=='u') {
               if(s[2]=='b') {
                  if(s[3]=='l') {
                     if(s[4]=='i') {
                        if(s[5]=='c')return 105;
                     }
                  }
               }
            }
         }
         else if(s[0]=='r') {
            if(s[1]=='e') {
               if(s[2]=='t') {
                  if(s[3]=='u') {
                     if(s[4]=='r') {
                        if(s[5]=='n')return 64;
                     }
                  }
               }
            }
         }
         else if(s[0]=='s') {
            if(s[1]=='t') {
               if(s[2]=='a') {
                  if(s[3]=='t') {
                     if(s[4]=='i') {
                        if(s[5]=='c')return 109;
                     }
                  }
               }
            }
            else if(s[1]=='w') {
               if(s[2]=='i') {
                  if(s[3]=='t') {
                     if(s[4]=='c') {
                        if(s[5]=='h')return 65;
                     }
                  }
               }
            }
         }
         else if(s[0]=='t') {
            if(s[1]=='c') {
               if(s[2]=='c') {
                  if(s[3]=='h') {
                     if(s[4]=='a') {
                        if(s[5]=='r')return 121;
                     }
                  }
               }
            }
         }
         break;
      case 7:
         if(s[0]=='#') {
            if(s[1]=='d') {
               if(s[2]=='e') {
                  if(s[3]=='f') {
                     if(s[4]=='i') {
                        if(s[5]=='n') {
                           if(s[6]=='e')return 95;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='b') {
            if(s[1]=='o') {
               if(s[2]=='o') {
                  if(s[3]=='l') {
                     if(s[4]=='e') {
                        if(s[5]=='a') {
                           if(s[6]=='n')return 69;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='c') {
            if(s[1]=='o') {
               if(s[2]=='m') {
                  if(s[3]=='p') {
                     if(s[4]=='i') {
                        if(s[5]=='l') {
                           if(s[6]=='e')return 102;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='d') {
            if(s[1]=='e') {
               if(s[2]=='f') {
                  if(s[3]=='a') {
                     if(s[4]=='u') {
                        if(s[5]=='l') {
                           if(s[6]=='t')return 73;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='e') {
            if(s[1]=='x') {
               if(s[2]=='p') {
                  if(s[3]=='l') {
                     if(s[4]=='a') {
                        if(s[5]=='i') {
                           if(s[6]=='n')return 114;
                        }
                     }
                  }
               }
               else if(s[2]=='t') {
                  if(s[3]=='e') {
                     if(s[4]=='n') {
                        if(s[5]=='d') {
                           if(s[6]=='s')return 103;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='f') {
            if(s[1]=='i') {
               if(s[2]=='n') {
                  if(s[3]=='a') {
                     if(s[4]=='l') {
                        if(s[5]=='l') {
                           if(s[6]=='y')return 118;
                        }
                     }
                  }
               }
            }
            else if(s[1]=='o') {
               if(s[2]=='r') {
                  if(s[3]=='e') {
                     if(s[4]=='a') {
                        if(s[5]=='c') {
                           if(s[6]=='h')return 92;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='p') {
            if(s[1]=='r') {
               if(s[2]=='e') {
                  if(s[3]=='p') {
                     if(s[4]=='a') {
                        if(s[5]=='r') {
                           if(s[6]=='e')return 101;
                        }
                     }
                  }
               }
               else if(s[2]=='i') {
                  if(s[3]=='v') {
                     if(s[4]=='a') {
                        if(s[5]=='t') {
                           if(s[6]=='e')return 106;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='r') {
            if(s[1]=='e') {
               if(s[2]=='t') {
                  if(s[3]=='u') {
                     if(s[4]=='r') {
                        if(s[5]=='n') {
                           if(s[6]=='s')return 110;
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='v') {
            if(s[1]=='i') {
               if(s[2]=='r') {
                  if(s[3]=='t') {
                     if(s[4]=='u') {
                        if(s[5]=='a') {
                           if(s[6]=='l')return 124;
                        }
                     }
                  }
               }
            }
         }
         break;
      case 8:
         if(s[0]=='R') {
            if(s[1]=='A') {
               if(s[2]=='N') {
                  if(s[3]=='D') {
                     if(s[4]=='_') {
                        if(s[5]=='M') {
                           if(s[6]=='A') {
                              if(s[7]=='X')return 86;
                           }
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='a') {
            if(s[1]=='b') {
               if(s[2]=='s') {
                  if(s[3]=='t') {
                     if(s[4]=='r') {
                        if(s[5]=='a') {
                           if(s[6]=='c') {
                              if(s[7]=='t')return 123;
                           }
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='d') {
            if(s[1]=='e') {
               if(s[2]=='l') {
                  if(s[3]=='e') {
                     if(s[4]=='g') {
                        if(s[5]=='a') {
                           if(s[6]=='t') {
                              if(s[7]=='e')return 113;
                           }
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='f') {
            if(s[1]=='u') {
               if(s[2]=='n') {
                  if(s[3]=='c') {
                     if(s[4]=='t') {
                        if(s[5]=='i') {
                           if(s[6]=='o') {
                              if(s[7]=='n')return 63;
                           }
                        }
                     }
                  }
               }
            }
         }
         break;
      case 9:
         if(s[0]=='n') {
            if(s[1]=='a') {
               if(s[2]=='m') {
                  if(s[3]=='e') {
                     if(s[4]=='s') {
                        if(s[5]=='p') {
                           if(s[6]=='a') {
                              if(s[7]=='c') {
                                 if(s[8]=='e')return 122;
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='p') {
            if(s[1]=='r') {
               if(s[2]=='o') {
                  if(s[3]=='t') {
                     if(s[4]=='e') {
                        if(s[5]=='c') {
                           if(s[6]=='t') {
                              if(s[7]=='e') {
                                 if(s[8]=='d')return 107;
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
         break;
      case 10:
         if(s[0]=='c') {
            if(s[1]=='o') {
               if(s[2]=='n') {
                  if(s[3]=='s') {
                     if(s[4]=='t') {
                        if(s[5]=='r') {
                           if(s[6]=='a') {
                              if(s[7]=='i') {
                                 if(s[8]=='n') {
                                    if(s[9]=='t')return 112;
                                 }
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
         else if(s[0]=='i') {
            if(s[1]=='n') {
               if(s[2]=='s') {
                  if(s[3]=='t') {
                     if(s[4]=='a') {
                        if(s[5]=='n') {
                           if(s[6]=='c') {
                              if(s[7]=='e') {
                                 if(s[8]=='o') {
                                    if(s[9]=='f')return 108;
                                 }
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
         break;

   }
   return 0;
}
