#
# Makefile for tks on Windows / Visual C++ platform
#
# (c) 2001-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

TARGET=tks.exe
TARGET_LIB=tks.lib


CXXFLAGS += -I../yac -DHAVE_CYGWIN $(EXTRAFLAGS) -fp:fast

ifeq ($(TKS_OPT_SIZE),y)
CFLAGS += -DTKS_OPT_SIZE
CXXFLAGS += -DTKS_OPT_SIZE
endif

EXTRAFLAGS = -DDX_SYSEXEC -DHAVE_WINREG -DDX_Z -DHAVE_ISOCPP -DHAVE_TLS
ifeq ($(BUILD_64),y)
EXTRAFLAGS += -DDX_X64
else
EXTRAFLAGS += -DTKS_JIT -DDX_X86 -DDX_RDTSC
endif
#EXTRAFLAGS += -DHAVE_URLMON
# note: TLS in YAC_Host::printf is thread-safe but increases .exe size by 128k (even when packed with UPX :()
EXTRAFLAGS += -DYAC_FORCE_NO_PRINTF_TLS
EXTRAFLAGS += -DAUTOLOAD_TKOPENGL

# for SetThreadSelectedCpuSets() (Thread::setCPUCore)
#  (note) as of 29Mar2019, this fxn is now resolved dynamically (for Win7 compatibility)
###ifeq ($(HAVE_WIN10),y)
EXTRAFLAGS += -DHAVE_WIN10
###endif

CXXFLAGS_EXE+= -DAUTOLOAD_TKOPENGL
CXXFLAGS_LIB+= -DTKS_LIB

ifeq ($(TKS_LIB_DEBUG),y)
CXXFLAGS_LIB+= -ZI -Gd -FS -D "_DEBUG"
endif

ifeq ($(TKS_VST),y)
EXTRAFLAGS += -DTKS_VST
endif

EXTRALIBS= urlmon.lib advapi32.lib uuid.lib kernel32.lib

ifeq ($(TKS_LIB),y)
ifeq ($(TKS_LIB_DEBUG),y)
EXTRALIBS += -MDd
else
EXTRALIBS += -MD
endif
endif


include make.objects


#
# Add zlib include/lib paths
#
ifneq ($(USE_SHARED_ZLIB),y)
CXXFLAGS += -I"$(ZLIB_SRC)"
ALL_OBJ += $(ZLIB_OBJ)
else
# windows only:
#CXXFLAGS += -I"$(ZLIB_BIN)/include"
#EXTRALIBS += "$(ZLIB_BIN)/lib/zdll.lib"
CXXFLAGS += -I"zlib-1.2.11/"
CXXFLAGS += -DZLIB_WINAPI
ifeq ($(BUILD_64),y)
EXTRALIBS += "zlib-1.2.11/lib/x64/zlibwapi.lib"
else
EXTRALIBS += "zlib-1.2.11/lib/x86/zlibwapi.lib"
endif
endif


#
# Platform dependent objects
#
PLAF_OBJ = TKS_Plugin_win32.o tks_debug_win32.o TKS_SharedBuffer_win32.o TKS_PerfCount.o TKS_PerfCount_win32.o TKS_Process_win32.o


ALL_OBJ+=$(PLAF_OBJ)
ALL_OBJ_LIB=$(addprefix lib/,$(ALL_OBJ))


#
# Note: The dummy libc should not be needed any longer since the zlib update
#
NEED_DUMMY_LIBC=
####NEED_DUMMY_LIBC=libc.lib


#
# Build scriptengine executable
#
$(TARGET): $(ALL_OBJ) $(NEED_DUMMY_LIBC)
	$(LD) $(LDFLAGS) -OUT:$(TARGET) $(ALL_OBJ) $(EXTRALIBS) $(NEED_DUMMY_LIBC)

bin:	$(TARGET)
	@ls -ld $(TARGET)
	@echo "Build finished at `date +%H:%M`."


#
# Build scriptengine lib (experimental)
#
$(TARGET_LIB): $(ALL_OBJ_LIB)
	$(LIB) $(LDFLAGS) -OUT:$(TARGET_LIB) $(ALL_OBJ_LIB) $(EXTRALIBS)

bin_lib: $(TARGET_LIB)
	@ls -ld $(TARGET_LIB)
	@echo "Lib Build finished at `date +%H:%M`."

.PHONY: lib
lib:
	$(m) clean ; $(m) -j$(NUM_JOBS) TKS_LIB=y bin_lib


#
# Install binary
#
#  (Note: on win32, everything is installed to the SITE directory)
#
install:
	$(MKDIR) "$(TKS_SITE_PREFIX)"
	$(CP) "$(TARGET)" "$(TKS_SITE_PREFIX)/"
#	$(CP) "$(TARGET).manifest" "$(TKS_SITE_PREFIX)/"
#	./tks install.tks
#	mv tks.sh.tmp $(TKS_PREFIX)/bin/tks
#	chmod 755 $(TKS_PREFIX)/bin/tks
	$(MKDIR) "$(TKS_SITE_PREFIX)/plugins"
	$(MKDIR) "$(TKS_SITE_PREFIX)/modules"
	$(MKDIR) "$(TKS_SITE_PREFIX)/libraries"
	$(MKDIR) "$(TKS_SITE_PREFIX)/applications"
	$(CP) "zlib-1.2.11/lib/x64/zlibwapi.dll" "$(TKS_SITE_PREFIX)/"
	$(CP) "../tksdl2/SDL2-2.32.4/lib/x64/release/SDL2.dll" "$(TKS_SITE_PREFIX)/"
	$(CP) "../tksdl_net/SDL_net-1.2.8/lib/x64/SDL_net.dll" "$(TKS_SITE_PREFIX)/"
	@echo "[...] Installed to $(TKS_SITE_PREFIX).";
	@echo "[...] ";
	@echo "[...]          Plugin directory is : $(TKS_SITE_PREFIX)/plugins/.";
	@echo "[...]          Module directory is : $(TKS_SITE_PREFIX)/modules/.";
	@echo "[...]         Library directory is : $(TKS_SITE_PREFIX)/libraries/.";
	@echo "[...]     Application directory is : $(TKS_SITE_PREFIX)/applications/.";
	@echo "[...] ";


#
# unfortunately, the msvc 2005 compiler/linker searches for a libc.lib if linking with
# a lib compiled with msvc 2003 / vc6.
# the solution, simply to satisfy the linker, is to provide a dummy libc.lib :)
#
libc.lib: dummy_libc.o
	$(LIB) -OUT:libc.lib dummy_libc.o -LIBPATH:"$(VCTK)/lib"


#
# install shared library (optional)
#  (note) n/a in Windows build
#
.PHONY: install_lib
install_lib:
	$(MKDIR) "$(TKS_LIB_PREFIX)"
	$(MKDIR) "$(TKS_INCLUDE_PREFIX)"
	cp inc_lib.h "$(TKS_INCLUDE_PREFIX)/tks_lib.h"
	cp $(TARGET_LIB) "$(TKS_LIB_PREFIX)/"
	@ls -ld "$(TKS_LIB_PREFIX)/$(TARGET_LIB)"


include makefile.common


#
# Rule for building object files
#
.cpp.o:
	$(CXX) $(CXXFLAGS) $(CXXFLAGS_EXE) $(OPTFLAGS) $(DBGFLAGS) -c $< -Fo"$@"

.c.o:
	$(CC) $(CXXFLAGS) $(CXXFLAGS_EXE) $(OPTFLAGS) $(DBGFLAGS) -c $< -Fo"$@"

lib/%.o : %.cpp
	$(CXX) $(CXXFLAGS) $(CXXFLAGS_LIB) $(OPTFLAGS) $(DBGFLAGS) -c $< -Fo"$@"

lib/%.o : %.c
	$(CC) $(CXXFLAGS) $(CXXFLAGS_LIB) $(OPTFLAGS) $(DBGFLAGS) -c $< -Fo"$@"

.s.o:
	$(AS) $(AFLAGS) $< -Fo"$@"
