#
# Makefile for tks
#
# (c) 2001-2026 Bastian Spiegel <bs@tkscript.de>
#


include ../install_macos.mk

TARGET= tks
TARGET_LIB= libtks.dylib

#debug-build:
#OPTFLAGS= -g

MINOPTFLAGS= -O2
#MINOPTFLAGS= -O1

CXXFLAGS+= -Wno-vla-cxx-extension

ifeq ($(TKS_OPT_SIZE),y)
CFLAGS+= -DTKS_OPT_SIZE
CXXFLAGS+= -DTKS_OPT_SIZE
LDFLAGS+= -Wl,-map,tks.map
LDFLAGS+= -dead_strip
endif

CXXFLAGS+= -DDX_SYSEXEC -DDX_Z -DHAVE_TLS -DHAVE_DLFCN -DHAVE_APPLE_QOS

CXXFLAGS_EXE+= -DAUTOLOAD_TKOPENGL
CXXFLAGS_LIB+= -fPIC -DTKS_LIB

ifeq ($(ARCH),X64)
CXXFLAGS+=-DDX_X64
else ifeq ($(ARCH),X86)
CXXFLAGS+= -DTKS_JIT -DDX_X86
else ifeq ($(ARCH),ARM64)
CXXFLAGS+= -DDX_ARM
CXXFLAGS+= -DDX_ARM64
else ifeq ($(ARCH),ARM32)
#CXXFLAGS+= -DTKS_JIT -DDX_ARM
CXXFLAGS+= -DDX_ARM
CXXFLAGS+= -DDX_ARM32
endif

CXXFLAGS+= -I../yac

include make.objects

PLAF_OBJ = TKS_Plugin_dlfcn.o tks_debug_stub.o TKS_SharedBuffer_linux.o TKS_Process_linux.o

ALL_OBJ+=$(PLAF_OBJ)
ALL_OBJ_LIB=$(addprefix lib/,$(ALL_OBJ))

#
# Build shared executable (otherwise the plugin loader may not work)
#
.PHONY: bin
bin:	$(ALL_OBJ)
	$(CXX) -o tks $(DBGFLAGS) $(LDFLAGS) $(ALL_OBJ) -lm -lz -ldl -lpthread
	@ls -ld tks
	@echo "Build finished at `date +%H:%M`."


#
# Build scriptengine lib
#
.PHONY: bin_lib
bin_lib: $(ALL_OBJ_LIB)
	$(CXX) -dynamiclib -o $(TARGET_LIB) $(ALL_OBJ_LIB) $(LDFLAGS) -lm -lz -ldl -lpthread
	@ls -ld $(TARGET_LIB)
	@echo "Lib Build finished at `date +%H:%M`."


.PHONY: lib
lib: clean_lib
	$(m) -j$(NUM_JOBS) TKS_LIB=y OPT_SIZE=$(OPT_SIZE) OPT_LTO=$(OPT_LTO) bin_lib


#
# Compress binary [gzip]
#
.PHONY: sz
sz: bin
	gzip -9 tks; ls -ld tks.gz ; gunzip tks.gz


#
# Build statically linked binary
#
static:	$(ALL_OBJ)
	$(CXX) -static -o tks $(LDFLAGS) $(ALL_OBJ) -lm -lz -ldl -lpthread
	@ls -ld tks
	@echo "Build finished at `date +%H:%M`."
        @echo "[...] warning: static builds seem to have problems loading shared objects (plugins)"


#
# Optimization seems to cause bugs
#
#TKS_CachedScript.o: TKS_CachedScript.cpp
#	$(CXX) $(CXXFLAGS) $(MINOPTFLAGS) $(DBGFLAGS) -c TKS_CachedScript.cpp -o TKS_CachedScript.o


#
# Install executable (tks.bin) and wrapper script (tks)
#
.PHONY: install
install:
	-rm -f "$(TKS_PREFIX)/tks.bin"
	cp -f tks "$(TKS_PREFIX)/tks.bin"
	-chmod 755 "$(TKS_PREFIX)/tks.bin"
	./tks install.tks
	-mv tks.sh.tmp "$(TKS_PREFIX)/tks"
	-chmod 755 "$(TKS_PREFIX)/tks"
	mkdir -p "$(TKS_SITE_PREFIX)"
	mkdir -p "$(TKS_SITE_PREFIX)/plugins"
	mkdir -p "$(TKS_SITE_PREFIX)/modules"
	mkdir -p "$(TKS_SITE_PREFIX)/libraries"
	mkdir -p "$(TKS_SITE_PREFIX)/applications"
	cp -f ../yac/ying.tks "$(TKS_SITE_PREFIX)/applications/"
	@echo "[...] Installed to $(TKS_PREFIX).";
	@echo "[...] ";
	@echo "[...]          Plugin directory is : $(TKS_SITE_PREFIX)/plugins/.";
	@echo "[...]          Module directory is : $(TKS_SITE_PREFIX)/modules/.";
	@echo "[...]         Library directory is : $(TKS_SITE_PREFIX)/libraries/.";
	@echo "[...]     Application directory is : $(TKS_SITE_PREFIX)/applications/.";
	@echo "[...] ";
	@echo "[...] Please use the $(TKS_PREFIX)/tks startscript.";
	@echo "[...] ";


#
# install shared library (optional)
#
.PHONY: install_lib
install_lib:
	mkdir -p "$(TKS_LIB_PREFIX)"
	mkdir -p "$(TKS_INCLUDE_PREFIX)"
	cp inc_lib.h "$(TKS_INCLUDE_PREFIX)/tks_lib.h"
	cp $(TARGET_LIB) "$(TKS_LIB_PREFIX)/"
	@ls -ld "$(TKS_LIB_PREFIX)/$(TARGET_LIB)"


include makefile.common


#
# Rule for building object files
#
.cpp.o:
	$(CXX) $(CXXFLAGS) $(CXXFLAGS_EXE) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

.c.o:
	$(CC) $(CXXFLAGS) $(CXXFLAGS_EXE) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

lib/%.o : %.cpp
	$(CXX) $(CXXFLAGS) $(CXXFLAGS_LIB) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

lib/%.o : %.c
	$(CC) $(CXXFLAGS) $(CXXFLAGS_LIB) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

.s.o:
	$(AS) $(AFLAGS) $< -o $@
