#
# Makefile for tks
# 
# (c) 2001-2026 Bastian Spiegel <bs@tkscript.de> 
#


include ../install_linux.mk

TARGET=tks
TARGET_LIB=libtks.so


#debug-build:
#OPTFLAGS= -g

MINOPTFLAGS= -O2
#MINOPTFLAGS= -O1

ifeq ($(TKS_OPT_SIZE),y)
CFLAGS += -DTKS_OPT_SIZE
CXXFLAGS += -DTKS_OPT_SIZE
endif

ifeq ($(BUILD_CLANG),y)
CXXFLAGS+= -Wno-vla-cxx-extension
endif

CXXFLAGS+= -DDX_SYSEXEC -DDX_Z -DHAVE_TLS -DHAVE_DLFCN

CXXFLAGS_EXE+= -DAUTOLOAD_TKOPENGL
CXXFLAGS_LIB+= -fPIC -DTKS_LIB

ifeq ($(ARCH),X64)
CXXFLAGS+=-DDX_X64
else ifeq ($(ARCH),X86)
CXXFLAGS+=  -DTKS_JIT -DDX_X86
else ifeq ($(ARCH),ARM64)
CXXFLAGS+= -DDX_ARM
CXXFLAGS+= -DDX_ARM64
else ifeq ($(ARCH),ARM32)
#CXXFLAGS+= -DTKS_JIT -DDX_ARM
CXXFLAGS+= -DDX_ARM
CXXFLAGS+= -DDX_ARM32
endif

CXXFLAGS+= -I../yac 


include make.objects

PLAF_OBJ = TKS_Plugin_dlfcn.o tks_debug_linux.o TKS_SharedBuffer_linux.o TKS_Process_linux.o

ifeq ($(CROSS_TARGET),OMAP3)
# only add if SAVE_CPUTABLE is defined
#CXXFLAGS += -DSAVE_CPUTABLE
#PLAF_OBJ += tkscputbl_src_arm.o
endif

ALL_OBJ+=$(PLAF_OBJ)
ALL_OBJ_LIB=$(addprefix lib/,$(ALL_OBJ))


#
# Build shared executable (otherwise the plugin loader may not work)
#
$(TARGET): $(ALL_OBJ)
	$(CXX) -o $(TARGET) $(LDFLAGS) $(ALL_OBJ) -lm -lz -ldl -lpthread

bin:	$(TARGET)
	@ls -ld $(TARGET)
	@echo "Build finished at `date +%H:%M`."


#
# Build scriptengine lib (experimental)
#
$(TARGET_LIB): $(ALL_OBJ_LIB)
	$(CXX) -shared -o $(TARGET_LIB) -Wl,-soname,$(TARGET_LIB) $(LDFLAGS) $(ALL_OBJ_LIB) -lm -lz -ldl -lpthread

bin_lib: $(TARGET_LIB)
	@ls -ld $(TARGET_LIB)
	@echo "Lib Build finished at `date +%H:%M`."

.PHONY: lib
lib: clean_lib
	$(m) -j$(NUM_JOBS) TKS_LIB=y OPT_SIZE=$(OPT_SIZE) OPT_LTO=$(OPT_LTO) bin_lib


#
# Optimization used to cause bugs in old GCC versions
#
#VMCore.o: VMCore.cpp
#	$(CXX) $(CXXFLAGS) $(MINOPTFLAGS) $(DBGFLAGS) -c VMCore.cpp -o VMCore.o


#
# Optimization used to cause bugs in old GCC versions
#
#TKS_CachedScript.o: TKS_CachedScript.cpp
#	$(CXX) $(CXXFLAGS) $(MINOPTFLAGS) $(DBGFLAGS) -c TKS_CachedScript.cpp -o TKS_CachedScript.o


#
# Install executable (tks.bin) and wrapper script (tks)
#
install:
	cp -f tks "$(TKS_PREFIX)/tks.bin"
	-chmod 755 "$(TKS_PREFIX)/tks.bin"
#	( export TKS_TARGET_PREFIX="$(TKS_TARGET_PREFIX)" ; export TKS_TARGET_SITE_PREFIX="$(TKS_TARGET_SITE_PREFIX)" ; ./tks install.tks )
	./tks install.tks
	-cp tks.sh.tmp "$(TKS_PREFIX)/tks"
	-rm -f tks.sh.tmp
	-chmod 755 "$(TKS_PREFIX)/tks"
	mkdir -p "$(TKS_SITE_PREFIX)"
	mkdir -p "$(TKS_SITE_PREFIX)/plugins"
	mkdir -p "$(TKS_SITE_PREFIX)/modules"
	mkdir -p "$(TKS_SITE_PREFIX)/libraries"
	mkdir -p "$(TKS_SITE_PREFIX)/applications"
	cp -f ../yac/ying.tks "$(TKS_SITE_PREFIX)/applications/"
	@echo "[...] Installed to $(TKS_PREFIX).";
	@echo "[...] ";
	@echo "[...]          Plugin directory is : $(TKS_SITE_PREFIX)/plugins/.";
	@echo "[...]          Module directory is : $(TKS_SITE_PREFIX)/modules/.";
	@echo "[...]         Library directory is : $(TKS_SITE_PREFIX)/libraries/.";
	@echo "[...]     Application directory is : $(TKS_SITE_PREFIX)/applications/.";
	@echo "[...] ";
	@echo "[...] Please use the $(TKS_PREFIX)/tks startscript.";
	@echo "[...] ";


#
# install shared library (optional)
#
.PHONY: install_lib
install_lib:
	mkdir -p "$(TKS_LIB_PREFIX)"
	mkdir -p "$(TKS_INCLUDE_PREFIX)"
	cp inc_lib.h "$(TKS_INCLUDE_PREFIX)/tks_lib.h"
	cp $(TARGET_LIB) "$(TKS_LIB_PREFIX)/"
	@ls -ld "$(TKS_LIB_PREFIX)/$(TARGET_LIB)"


#
# Build statically linked binary
#
static:	$(ALL_OBJ)
	$(CXX) -static -o tks $(LDFLAGS) $(ALL_OBJ) -lm -lz -ldl -lpthread
	@echo "Build finished at `date +%H:%M`."
        @echo "[...] warning: static builds seem to have problems loading shared objects (plugins)"


include makefile.common


#
# Rule for building object files
#
.cpp.o:
	$(CXX) $(CXXFLAGS) $(CXXFLAGS_EXE) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

.c.o:
	$(CC) $(CXXFLAGS) $(CXXFLAGS_EXE) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

lib/%.o : %.cpp
	$(CXX) $(CXXFLAGS) $(CXXFLAGS_LIB) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

lib/%.o : %.c
	$(CC) $(CXXFLAGS) $(CXXFLAGS_LIB) $(OPTFLAGS) $(DBGFLAGS) -c $< -o $@

.s.o:
	$(AS) $(AFLAGS) $< -o $@
