
#
# Show help
#
.PHONY: help
help:
	@echo "       help     : this page."
	@echo "       bin      : build dynamically linked exe."
	@echo "       upx       : build dynamically linked exe and compress it with UPX."
	@echo "       doc       : generate HTML API documentation";
	@echo "       yac       : rebuild API interface bindings"
	@echo "       static   : build statically linked exe."
	@echo "       clean    : remove object files."
	@echo "       realclean: clean and remove backup files."


#
# Re-scan YAC interface bindings and write ying_* files
#
.PHONY: yac
yac:
	$(TKS) app:ying -ng -nc api.cpp


#
# Compress binary [optional / deprecated]
#
.PHONY: upx
upx: bin
	$(UPX) -9 $(TARGET)


#
# Generate HTML API documentation
#
.PHONY: doc
doc:
	$(TKS) app:dog++ -pn core api.cpp >tks.ee
	(cd doc ; $(TKS) app:dog -fp "" ../tks.ee)


#
# special documentation target, internally used for the "BIG" documentation that covers tks+all plugins/libraries
#
.PHONY: ee
ee:
	$(TKS) app:dog++ -pn core api.cpp >../apidocs/ee/core.ee


#
# Remove object files and targets.
#
.PHONY: clean_lib
clean_lib:
	@echo "cleaning up lib.."
	$(RM) $(ALL_OBJ_LIB) $(TARGET_LIB)

.PHONY: clean
clean: clean_lib
	@echo "cleaning up.."
	$(RM) $(ALL_OBJ) $(TARGET)

#
# Make clean and remove backup files
#
.PHONY: realclean
realclean: clean clean_lib
	$(RM) `find . -name \*\~` $(TARGET) $(TARGET_LIB)
	$(RM) `$(FIND) . -name \*\~`
	$(RM) `$(FIND) . -name \*.ncb`
	$(RM) `$(FIND) . -name \*.pdb`
	$(RM) `$(FIND) . -name \*.exp`
	$(RM) `$(FIND) . -name \*.plg`
	$(RM) `$(FIND) . -name \*.obj`
	$(RM) `$(FIND) . -name \*.sbr`
	$(RM) `$(FIND) . -name \*.bsc`
	$(RM) `$(FIND) . -name \*.ilk`
	$(RM) -r `$(FIND) . -name \.vs`


#
# Copy to target via ssh / scp
#
.PHONY: deploy
deploy: bin
	scp ${SCP_FLAGS} tks ${SCP_USER}@${SCP_HOST}:${SCP_TKS_PREFIX}/bin/tks.bin
