#
# Makefile for tkzip plugin + Microsoft Visual C++ 2019 ToolKit
# 
# (c) 2020-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

LIBZIP=libzip-1.5.2
LIBZIP_SRC=$(LIBZIP)/lib/

ZLIB_SRC=zlib-1.2.11/

PLUGIN=tkzip

EXTRAFLAGS= -I$(ZLIB_SRC) -I$(LIBZIP_SRC) -DHAVE_WINDOWS_CRYPTO -Dstrcasecmp=_stricmp

EXTRALIBS= $(ZLIB_SRC)/lib/x64/zlibwapi.lib Advapi32.lib

include make.objects

ALL_OBJ += $(ZIP_OBJ)
ALL_OBJ += $(ZIP_OBJ_WIN32)

include ../plugin_msvc.mk
