#
# Makefile for tkbluetooth plugin on Windows / Visual C++ platform
#
# (c) 2018-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkbluetooth

EXTRAFLAGS= -D_WINSOCK_DEPRECATED_NO_WARNINGS

EXTRALIBS= Bthprops.lib Ws2_32.lib

PLAF_OBJ= \
	BlueToothClient_windows.o \
	BlueToothServer_windows.o

include make.objects

ALL_OBJ= $(COMMON_OBJ) $(PLAF_OBJ)

include ../build_msvc.mk
