#
# Makefile for tkbluetooth on Linux / GCC platform
# 
# (c) 2018 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkbluetooth

EXTRAFLAGS= 

EXTRALIBS= -lbluetooth

PLAF_OBJ= \
	BlueToothClient_linux.o \
	BlueToothServer_linux.o 

include make.objects

ALL_OBJ= $(COMMON_OBJ) $(PLAF_OBJ)

include ../plugin_linux.mk
