#
# Makefile for tkbluetooth plugin + Microsoft Visual C++ 2003 / 2005 / 2008 / 2017 ToolKit
# 
# (c) 2018 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkbluetooth

EXTRAFLAGS= -D_WINSOCK_DEPRECATED_NO_WARNINGS

EXTRALIBS= Bthprops.lib Ws2_32.lib

PLAF_OBJ= \
	BlueToothClient_windows.o \
	BlueToothServer_windows.o

include make.objects

ALL_OBJ= $(COMMON_OBJ) $(PLAF_OBJ)

include ../plugin_msvc.mk
