// ---- ying_tkbluetooth_BlueToothAddress.cpp: auto generated by YInG - the YAC interface generator (Wed, 5/Feb/2020 17:53:23)

sSI   YAC_CALL BlueToothAddress__getByte(void *, yacmemptr         );
sSI   YAC_CALL BlueToothAddress__setByte(void *, yacmemptr         );

// ------------------ YAC class "BlueToothAddress" reflection map (implementation) ------------------
sUI          YAC_VCALL BlueToothAddress::yacMemberGetNum                  (void) {return 0;}
const char **YAC_VCALL BlueToothAddress::yacMemberGetNames                (void) {return 0;}
const sUI   *YAC_VCALL BlueToothAddress::yacMemberGetTypes                (void) {return 0;}
const char **YAC_VCALL BlueToothAddress::yacMemberGetObjectTypes          (void) {return 0;}
const sU8  **YAC_VCALL BlueToothAddress::yacMemberGetOffsets              (void) {return (const sU8**)0;}
sUI          YAC_VCALL BlueToothAddress::yacMethodGetNum                  (void) {return 3;}
const char **YAC_VCALL BlueToothAddress::yacMethodGetNames                (void) {static const char *r[]={"operator", "getByte", "setByte"}; return r;}
const sUI   *YAC_VCALL BlueToothAddress::yacMethodGetNumParameters        (void) {static const sUI r[]={2, 1, 2}; return r;}
const sUI  **YAC_VCALL BlueToothAddress::yacMethodGetParameterTypes       (void) {static const sUI rt0[]={1,3};static const sUI rt1[]={1,};static const sUI rt2[]={1, 1,};static const sUI *r[]={rt0, rt1, rt2}; return r;}
const char***YAC_VCALL BlueToothAddress::yacMethodGetParameterObjectTypes (void) {static const char *rs0[]={0,"",};static const char *rs1[]={(const char*)0,};static const char *rs2[]={(const char*)0, (const char*)0,};static const char**r[]={rs0, rs1, rs2}; return r;}
const sUI   *YAC_VCALL BlueToothAddress::yacMethodGetReturnTypes          (void) {static const sUI r[]={4, 1, 1}; return r;}
const char **YAC_VCALL BlueToothAddress::yacMethodGetReturnObjectTypes    (void) {static const char *r[]={"", (const char*)0, (const char*)0}; return r;}
const void **YAC_VCALL BlueToothAddress::yacMethodGetAdr                  (void) {static const void *r[]={(void*)Object__operator, (void*)BlueToothAddress__getByte, (void*)BlueToothAddress__setByte}; return r;}
sUI          YAC_VCALL BlueToothAddress::yacConstantGetNum                (void) {return 0;}
const char **YAC_VCALL BlueToothAddress::yacConstantGetNames              (void) {static const char*r[]={""}; return r;}
const sUI   *YAC_VCALL BlueToothAddress::yacConstantGetTypes              (void) {static const sUI r[]={0}; return r;}
yacmemptr    YAC_VCALL BlueToothAddress::yacConstantGetValues             (void) {static sUI r[]={0,};yacmemptr m; m.ui=(sUI*)r; return m;}

YAC_C(BlueToothAddress, "BlueToothAddress");

sSI   YAC_CALL BlueToothAddress__getByte(void *_o, yacmemptr _args           ) {return (sSI)((BlueToothAddress*)_o)->getByte(_args.mem[0].si);}
sSI   YAC_CALL BlueToothAddress__setByte(void *_o, yacmemptr _args           ) {return (sSI)((BlueToothAddress*)_o)->setByte(_args.mem[0].si, _args.mem[1].si);}
