
include ../install_macos.mk

PLUGIN=tkfileutils

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= tkfileutils_linux.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include makefile.common

include ../plugin_macos.mk
