#
# Makefile for tkfileutils plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2010 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkfileutils

EXTRAFLAGS= -fp:fast

EXTRALIBS= 

PLAF_OBJ= tkfileutils_win32.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include makefile.common

include ../plugin_msvc.mk
