#
# Makefile for tkfileutils plugin on Linux / GCC platform
# 
# (c) 2010 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkfileutils

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= tkfileutils_linux.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include makefile.common

include ../plugin_linux.mk
