#
# Makefile for tkfileutils plugin on Windows / Visual C++ platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkfileutils

EXTRAFLAGS= -fp:fast

EXTRALIBS=

PLAF_OBJ= tkfileutils_win32.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include makefile.common

include ../build_msvc.mk
