#
# Makefile for tkfileutils plugin on macOS / Clang platform
#
# (c) 2023-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tkfileutils

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ= tkfileutils_linux.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include makefile.common

include ../build_macos.mk
