#
# Makefile for tkfileutils plugin on Linux / GCC / Clang platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkfileutils

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ= tkfileutils_linux.o

include make.objects

ALL_OBJ += $(PLAF_OBJ)

include makefile.common

include ../build_linux.mk
