#
# Makefile for tkui plugin on macOS
# 
# (c) 2023-2025 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tkui

EXTRAFLAGS=
EXTRAFLAGS_OBJC= -Wno-deprecated-declarations

EXTRALIBS= -framework Carbon -framework Cocoa

PLAF_OBJ= TKUI_CommonDialogs_macos_objc.o TKUI_CommonDialogs_macos.o

include make.objects

include makefile.common

include ../plugin_macos.mk
