#
# Makefile for tkui plugin on Windows / Visual C++ platform
#
# (c) 2005-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkui

EXTRAFLAGS=

EXTRALIBS= uuid.lib comdlg32.lib

PLAF_OBJ= TKUI_CommonDialogs_win32.o

include make.objects

include makefile.common

include ../build_msvc.mk
