#
# Makefile for tkui plugin on MingW / GCC platform
# 
# (c) 2005-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tkui

EXTRAFLAGS= 

EXTRALIBS= -luuid -lcomdlg32

PLAF_OBJ= TKUI_CommonDialogs_win32.o

include make.objects

include makefile.common

include ../plugin_mingw.mk
