#
# Makefile for tkui plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2005-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkui

EXTRAFLAGS= 

EXTRALIBS= uuid.lib comdlg32.lib

PLAF_OBJ= TKUI_CommonDialogs_win32.o

include make.objects

include makefile.common

include ../plugin_msvc.mk
