#
# Common toplevel makefile targets for TKS and plugins
#
#  This file gets included by makefile.[msvc | mingw | linux | macosx]
#
#  m, PLUGINS and TKS_ZIP_PREFIX must be defined before including this file.
#
#

.PHONY: help
help:
	@echo "         all_clean : Clean tks and plugin targets"
	@echo "           all_bin : Build tks and plugin targets"
	@echo "           all_upx : Compress all executables and DLLs using UPX"
	@echo "       all_install : Install tks and plugin targets"
	@echo "           all_zip : Create source distribution packages (.zip) in directory \"$(TKS_ZIP_PREFIX)\""
	@echo " "
	@echo "           tks_bin : Build tks binary"
	@echo "       plugins_bin : Build plugins"
	@echo "     plugins_clean : Remove targets and intermediate build files"
	@echo "       plugins_zip : Create plugin source distribution packages (.zip) in directory \"$(TKS_ZIP_PREFIX)\""
	@echo "        plugins_ee : Export plugin documentation (in DOG format)"
	@echo "       plugins_yac : (Re-)build YAC interface files";
	@echo " "


# (note) the ALL_PLUGINS list is used by the 'all_zip' target (see makefile.<platform> for per-platform plugin build selection)

# core plugins
ALL_PLUGINS= yingtest__
ALL_PLUGINS+= tksdl__
ALL_PLUGINS+= tksdl12-compat__
ALL_PLUGINS+= tksdl2__
ALL_PLUGINS+= tkopengl__
ALL_PLUGINS+= tkfreetype2__
ALL_PLUGINS+= tkui__
ALL_PLUGINS+= tkfileutils__
ALL_PLUGINS += tkminnie__
ALL_PLUGINS += tkmath__

# other plugins
ALL_PLUGINS += tkoldmath__
ALL_PLUGINS += tkbluetooth__
ALL_PLUGINS += tksdl_net__
ALL_PLUGINS += tkdist2d__
ALL_PLUGINS += tkzip__
ALL_PLUGINS += tksqlite__
#ALL_PLUGINS += tkreplay__

# graphics plugins (not used by ST2)
ALL_PLUGINS += tkchipmunk__
ALL_PLUGINS += tkfreeglut__
ALL_PLUGINS += tktriangulate__
ALL_PLUGINS += polyraster__

# audio plugins (not used by ST2)
ALL_PLUGINS += eqxmms__
ALL_PLUGINS += tksidplay2__
ALL_PLUGINS += tkfreeverb__
ALL_PLUGINS += tksmdi__
ALL_PLUGINS += tkspeexdsp__

# ST2 audio plugins
ALL_PLUGINS += tkanalogrytm__
ALL_PLUGINS += tkclap__
ALL_PLUGINS += tkmidi__
ALL_PLUGINS += tkmidi_alsa__
ALL_PLUGINS += tkmidi_portmidi__
ALL_PLUGINS += tkportaudio__
ALL_PLUGINS += tkportaudio_alsa__
ALL_PLUGINS += tkradiastools__
ALL_PLUGINS += tksampler__
ALL_PLUGINS += tksampleedit__
####ALL_PLUGINS += tksynth__
ALL_PLUGINS += tkvst2__
ALL_PLUGINS += tkvst2_stub__
ALL_PLUGINS += tkvst2_nogui__
ALL_PLUGINS += tkvst2_macos__
###PLUGINS += tkcustomsynth__
###PLUGINS += tkmacrosynth__
###PLUGINS += tksynthgenproxy__
ALL_PLUGINS += tkmidipipe__
ALL_PLUGINS += tksamplechain__


#
# script libraries + applications
#
ALL_TSL_TARGETS= debugtext_install librs_install libplot_install libplot-fs_install

ALL_TKX_TARGETS= dog_install org_install md_install graph_install tksdl_examples_install


#
# all targets
#
.PHONY: all
all: tks plugins

.PHONY: all_clean
all_clean: tks_clean yac_clean plugins_clean clean_tags

.PHONY: clean
clean: all_clean

.PHONY: 

.PHONY: all_bin
all_bin:
	+$(m) -j $(NUM_JOBS) tks_bin
	+$(m) -j $(NUM_JOBS) plugins_bin
	@echo "tks + plugins build finished at `date +%H:%M`."

.PHONY: bin
bin: all_bin

# (todo) remove
.PHONY: all_upx
all_upx: tks_upx plugins_upx



#
# Clean CTAGS, GTAGS, cscope databases (tags.sh rebuilds them)
#
.PHONY: clean_tags
clean_tags:
	$(RM) cscope.out
	$(RM) cscope.in.out
	$(RM) cscope.po.out
	$(RM) GPATH
	$(RM) GRTAGS
	$(RM) GTAGS
	$(RM) BROWSE


#
# plugin targets
#
.PHONY: plugins
plugins: $(subst __,,$(PLUGINS))

.PHONY: plugins_clean
plugins_clean: $(subst __,_clean,$(PLUGINS))

.PHONY: plugins_bin
plugins_bin: $(subst __,_bin,$(PLUGINS))
	@echo "plugins_bin build finished at `date +%H:%M`."

.PHONY: plugins_upx
plugins_upx: $(subst __,_upx,$(PLUGINS))

.PHONY: plugins_install
plugins_install: $(subst __,_install,$(PLUGINS))

.PHONY: plugins_ee
plugins_ee: $(subst __,_ee,$(PLUGINS))

.PHONY: plugins_yac
plugins_yac: $(subst __,_yac,$(PLUGINS))

.PHONY: plugins_zip
plugins_zip: $(subst __,_zip,$(ALL_PLUGINS))



#
# yac (use Cygwin shell!)
#
.PHONY: yac_clean
yac_clean:
	$(RM) -fr `find yac -name \*~`

yac_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/yac.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/yac.zip" yac

#
# Create snapshot of build environment
#
ALL_MAKEFILES= makefile.common makefile.linux makefile.msvc makefile.macos
ALL_MKINCLUDES= install_linux.mk install_msvc.mk install_macos.mk build_common.mk build_common_gcc.mk build_linux.mk build_macos.mk build_msvc.mk setenv_msvc.sh setenv_linux.sh setenv_linux_poky.sh setenv_linux_raspbian_32.sh setenv_linux_raspbian_64.sh setenv_macos_arm64.sh setenv_macos_x86_64.sh

tks_build_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tks-build.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tks-build.zip" $(ALL_MAKEFILES) $(ALL_MKINCLUDES)


#
# Example source packages
#  (more examples can be found in the plugin packages)
#
all_examples_zip: tks_examples_zip gkraft_zip retrovaders2_zip equalize_it_zip

tks_examples_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tks-examples.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tks-examples.zip" tks-examples/

gkraft_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/gkraft.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/gkraft.zip" tks-projects/games/gkraft

retrovaders2_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/retrovaders2.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/retrovaders2.zip" tks-projects/games/retrovaders2

equalize_it_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/equalize_it.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/equalize_it.zip" tks-projects/other/equalize_it_dev


#
# Script libraries
#
all_tsl_zip: debugtext_zip tkunit_zip libplot_zip libplot-fs_zip librs_zip

.PHONY: debugtext_zip
debugtext_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/debugtext.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/debugtext.zip" tks-projects/libs/debugtext/

.PHONY: debugtext_install
debugtext_install:
	$(m) -C tks-projects/libs/debugtext/ install

.PHONY: tkunit_zip
tkunit_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkunit.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkunit.zip" tkunit/

.PHONY: libplot_zip
libplot_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/libplot.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/libplot.zip" tks-projects/libs/libplot/

.PHONY: libplot_install
libplot_install:
	$(m) -C tks-projects/libs/libplot/ install

.PHONY: libplot-fs_zip
libplot-fs_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/libplot-fs.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/libplot-fs.zip" tks-projects/libs/libplot-fs/

.PHONY: libplot-fs_install
libplot-fs_install:
	$(m) -C tks-projects/libs/libplot-fs/ install

.PHONY: librs_zip
librs_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/librs.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/librs.zip" tks-projects/libs/librs/

.PHONY: librs_install
librs_install:
	$(m) -C tks-projects/libs/librs/ install


#
# Script applications
#
all_app_zip: dog_zip rio_zip org_zip md_zip svg_loader_zip shadervg_zip gledit_zip racer_zip graph_zip

.PHONY: dog_zip
dog_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/dog.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/dog.zip" tks-projects/tools/dog/

.PHONY: dog_install
dog_install:
	$(MAKE) -C tks-projects/tools/dog install

.PHONY: rio_zip
rio_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/rio.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/rio.zip" tks-projects/libs/rio/

.PHONY: org_zip
org_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/org.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/org.zip" tks-projects/tools/org/

.PHONY: org_install
org_install:
	$(MAKE) -C tks-projects/tools/org install

.PHONY: md_zip
md_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/md.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/md.zip" tks-projects/tools/md/

.PHONY: md_install
md_install:
	$(MAKE) -C tks-projects/tools/md install

.PHONY: svg_loader_zip
svg_loader_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/svg_loader.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/svg_loader.zip" tks-projects/tools/svg_loader/

#.PHONY: svg_loader_install
#svg_loader_install:
#	$(MAKE) -C tks-projects/svg_loader install

.PHONY: shadervg_zip
shadervg_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/shadervg.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/shadervg.zip" tks-projects/libs/shadervg/

#.PHONY: shadervg_install
#shadervg_install:
#	$(MAKE) -C tks-projects/shadervg install

.PHONY: gledit_zip
gledit_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/gledit.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/gledit.zip" tks-projects/apps/gledit/

.PHONY: racer_zip
racer_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/racer.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/racer.zip" tks-projects/games/racer/

.PHONY: graph_zip
graph_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/graph.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/graph.zip" tks-projects/tools/graph/

.PHONY: graph_install
graph_install:
	$(MAKE) -C tks-projects/tools/graph install


.PHONY: tksdl_examples_install
tksdl_examples_install:
	$(MAKE) -C tks-examples/tksdl install


#
# tks
#
.PHONY: tks
tks:
	$(m) -j $(NUM_JOBS) -C tks-source realclean ; $(m) -j $(NUM_JOBS) -C tks-source bin

.PHONY: tks_clean
tks_clean:
	$(m) -j $(NUM_JOBS) -C tks-source realclean

.PHONY: tks_lib
tks_lib:
	$(m) -j $(NUM_JOBS) -C tks-source lib
	$(m) -j $(NUM_JOBS) -C tks-source clean

.PHONY: tks_bin
tks_bin: tks_lib
	$(m) -j $(NUM_JOBS) -C tks-source bin

tks_upx:
	$(m) -j $(NUM_JOBS) -C tks-source upx

tks_install:
	$(m) -j $(NUM_JOBS) -C tks-source install_lib
	$(m) -j $(NUM_JOBS) -C tks-source install

tks_ee:
	$(m) -j $(NUM_JOBS) -C tks-source ee

tks_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tks-source.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tks-source.zip" tks-source


#
# yingtest
#
.PHONY: yingtest
yingtest:
	$(m) -j $(NUM_JOBS) -C yingtest realclean ; $(m) -j $(NUM_JOBS) -C yingtest bin

yingtest_clean:
	$(m) -j $(NUM_JOBS) -C yingtest realclean

yingtest_bin:
	$(m) -j $(NUM_JOBS) -C yingtest bin

yingtest_upx:
	$(m) -j $(NUM_JOBS) -C yingtest upx

yingtest_install:
	$(m) -j $(NUM_JOBS) -C yingtest install

yingtest_ee:
	$(m) -j $(NUM_JOBS) -C yingtest ee

yingtest_yac:
	$(m) -j $(NUM_JOBS) -C yingtest yac

yingtest_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/yingtest.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/yingtest.zip" yingtest


#
# tksdl
#
.PHONY: tksdl
tksdl:
	$(m) -j $(NUM_JOBS) -C tksdl realclean ; $(m) -j $(NUM_JOBS) -C tksdl bin

tksdl_clean:
	$(m) -j $(NUM_JOBS) -C tksdl realclean

tksdl_bin:
	$(m) -j $(NUM_JOBS) -C tksdl bin

tksdl_upx:
	$(m) -j $(NUM_JOBS) -C tksdl upx

tksdl_install:
	$(m) -j $(NUM_JOBS) -C tksdl install

tksdl_ee:
	$(m) -j $(NUM_JOBS) -C tksdl ee

tksdl_yac:
	$(m) -j $(NUM_JOBS) -C tksdl yac

tksdl_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksdl.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksdl.zip" tksdl


#
# tksdl12-compat
#
.PHONY: tksdl12-compat
tksdl12-compat:
	$(m) -j $(NUM_JOBS) -C tksdl12-compat realclean ; $(m) -j $(NUM_JOBS) -C tksdl12-compat bin

tksdl12-compat_clean:
	$(m) -j $(NUM_JOBS) -C tksdl12-compat realclean

tksdl12-compat_bin:
	$(m) -j $(NUM_JOBS) -C tksdl12-compat bin

tksdl12-compat_upx:
	$(m) -j $(NUM_JOBS) -C tksdl12-compat upx

tksdl12-compat_install:
	$(m) -j $(NUM_JOBS) -C tksdl12-compat install

tksdl12-compat_ee:
	$(m) -j $(NUM_JOBS) -C tksdl12-compat ee

tksdl12-compat_yac:
	$(m) -j $(NUM_JOBS) -C tksdl12-compat yac

tksdl12-compat_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksdl12-compat.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksdl12-compat.zip" tksdl12-compat


#
# tksdl2
#
.PHONY: tksdl2
tksdl2:
	$(m) -j $(NUM_JOBS) -C tksdl2 realclean ; $(m) -j $(NUM_JOBS) -C tksdl2 bin

tksdl2_clean:
	$(m) -j $(NUM_JOBS) -C tksdl2 realclean

tksdl2_bin:
	$(m) -j $(NUM_JOBS) -C tksdl2 bin

tksdl2_upx:
	$(m) -j $(NUM_JOBS) -C tksdl2 upx

tksdl2_install:
	$(m) -j $(NUM_JOBS) -C tksdl2 install

tksdl2_ee:
	$(m) -j $(NUM_JOBS) -C tksdl2 ee

tksdl2_yac:
	$(m) -j $(NUM_JOBS) -C tksdl2 yac

tksdl2_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksdl2.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksdl2.zip" tksdl2


#
# tksdl_net
#
.PHONY: tksdl_net
tksdl_net:
	$(m) -j $(NUM_JOBS) -C tksdl_net realclean ; $(m) -j $(NUM_JOBS) -C tksdl_net bin

tksdl_net_clean:
	$(m) -j $(NUM_JOBS) -C tksdl_net realclean

tksdl_net_bin:
	$(m) -j $(NUM_JOBS) -C tksdl_net bin

tksdl_net_upx:
	$(m) -j $(NUM_JOBS) -C tksdl_net upx

tksdl_net_install:
	$(m) -j $(NUM_JOBS) -C tksdl_net install

tksdl_net_ee:
	$(m) -j $(NUM_JOBS) -C tksdl_net ee

tksdl_net_yac:
	$(m) -j $(NUM_JOBS) -C tksdl_net yac

tksdl_net_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksdl_net.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksdl_net.zip" tksdl_net


#
# tkopengl
#
.PHONY: tkopengl
tkopengl:
	$(m) -j $(NUM_JOBS) -C tkopengl realclean ; $(m) -j $(NUM_JOBS) -C tkopengl bin

tkopengl_clean:
	$(m) -j $(NUM_JOBS) -C tkopengl realclean

tkopengl_bin:
	$(m) -j $(NUM_JOBS) -C tkopengl bin

tkopengl_upx:
	$(m) -j $(NUM_JOBS) -C tkopengl upx

tkopengl_install:
	$(m) -j $(NUM_JOBS) -C tkopengl install

tkopengl_ee:
	$(m) -j $(NUM_JOBS) -C tkopengl ee

tkopengl_yac:
	$(m) -j $(NUM_JOBS) -C tkopengl yac

tkopengl_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkopengl.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkopengl.zip" tkopengl


#
# tkcg (deprecated, use GLSL instead)
#
.PHONY: tkcg
tkcg:
	$(m) -j $(NUM_JOBS) -C tkcg realclean ; $(m) -j $(NUM_JOBS) -C tkcg bin

tkcg_clean:
	$(m) -j $(NUM_JOBS) -C tkcg realclean

tkcg_bin:
	$(m) -j $(NUM_JOBS) -C tkcg bin

tkcg_upx:
	$(m) -j $(NUM_JOBS) -C tkcg upx

tkcg_install:
	$(m) -j $(NUM_JOBS) -C tkcg install

tkcg_ee:
	$(m) -j $(NUM_JOBS) -C tkcg ee

tkcg_yac:
	$(m) -j $(NUM_JOBS) -C tkcg yac

tkcg_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkcg.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkcg.zip" tkcg


#
# tkfreetype2
#
.PHONY: tkfreetype2
tkfreetype2:
	$(m) -j $(NUM_JOBS) -C tkfreetype2 realclean ; $(m) -j $(NUM_JOBS) -C tkfreetype2 bin

tkfreetype2_clean:
	$(m) -j $(NUM_JOBS) -C tkfreetype2 realclean

tkfreetype2_bin:
	$(m) -j $(NUM_JOBS) -C tkfreetype2 bin

tkfreetype2_upx:
	$(m) -j $(NUM_JOBS) -C tkfreetype2 upx

tkfreetype2_install:
	$(m) -j $(NUM_JOBS) -C tkfreetype2 install

tkfreetype2_ee:
	$(m) -j $(NUM_JOBS) -C tkfreetype2 ee

tkfreetype2_yac:
	$(m) -j $(NUM_JOBS) -C tkfreetype2 yac

tkfreetype2_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkfreetype2.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkfreetype2.zip" tkfreetype2


#
# tkui
#
.PHONY: tkui
tkui:
	$(m) -j $(NUM_JOBS) -C tkui realclean ; $(m) -j $(NUM_JOBS) -C tkui bin

tkui_clean:
	$(m) -j $(NUM_JOBS) -C tkui realclean

tkui_bin:
	$(m) -j $(NUM_JOBS) -C tkui bin

tkui_upx:
	$(m) -j $(NUM_JOBS) -C tkui upx

tkui_install:
	$(m) -j $(NUM_JOBS) -C tkui install

tkui_ee:
	$(m) -j $(NUM_JOBS) -C tkui ee

tkui_yac:
	$(m) -j $(NUM_JOBS) -C tkui yac

tkui_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkui.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkui.zip" tkui


#
# tkfreeglut
#
.PHONY: tkfreeglut
tkfreeglut:
	$(m) -j $(NUM_JOBS) -C tkfreeglut realclean ; $(m) -j $(NUM_JOBS) -C tkfreeglut bin

tkfreeglut_clean:
	$(m) -j $(NUM_JOBS) -C tkfreeglut realclean

tkfreeglut_bin:
	$(m) -j $(NUM_JOBS) -C tkfreeglut bin

tkfreeglut_upx:
	$(m) -j $(NUM_JOBS) -C tkfreeglut upx

tkfreeglut_install:
	$(m) -j $(NUM_JOBS) -C tkfreeglut install

tkfreeglut_ee:
	$(m) -j $(NUM_JOBS) -C tkfreeglut ee

tkfreeglut_yac:
	$(m) -j $(NUM_JOBS) -C tkfreeglut yac

tkfreeglut_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkfreeglut.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkfreeglut.zip" tkfreeglut


#
# tkmath
#
.PHONY: tkmath
tkmath:
	$(m) -j $(NUM_JOBS) -C tkmath realclean ; $(m) -j $(NUM_JOBS) -C tkmath bin

tkmath_clean:
	$(m) -j $(NUM_JOBS) -C tkmath realclean

tkmath_bin:
	$(m) -j $(NUM_JOBS) -C tkmath bin

tkmath_upx:
	$(m) -j $(NUM_JOBS) -C tkmath upx

tkmath_install:
	$(m) -j $(NUM_JOBS) -C tkmath install

tkmath_ee:
	$(m) -j $(NUM_JOBS) -C tkmath ee

tkmath_yac:
	$(m) -j $(NUM_JOBS) -C tkmath yac

tkmath_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkmath.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkmath.zip" tkmath


#
# tkoldmath
#
.PHONY: tkoldmath
tkoldmath:
	$(m) -j $(NUM_JOBS) -C tkoldmath realclean ; $(m) -j $(NUM_JOBS) -C tkoldmath bin

tkoldmath_clean:
	$(m) -j $(NUM_JOBS) -C tkoldmath realclean

tkoldmath_bin:
	$(m) -j $(NUM_JOBS) -C tkoldmath bin

tkoldmath_upx:
	$(m) -j $(NUM_JOBS) -C tkoldmath upx

tkoldmath_install:
	$(m) -j $(NUM_JOBS) -C tkoldmath install

tkoldmath_ee:
	$(m) -j $(NUM_JOBS) -C tkoldmath ee

tkoldmath_yac:
	$(m) -j $(NUM_JOBS) -C tkoldmath yac

tkoldmath_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkoldmath.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkoldmath.zip" tkoldmath


#
# eqxmms
#
.PHONY: eqxmms
eqxmms:
	$(m) -j $(NUM_JOBS) -C eqxmms realclean ; $(m) -j $(NUM_JOBS) -C eqxmms bin

eqxmms_clean:
	$(m) -j $(NUM_JOBS) -C eqxmms realclean

eqxmms_bin:
	$(m) -j $(NUM_JOBS) -C eqxmms bin

eqxmms_upx:
	$(m) -j $(NUM_JOBS) -C eqxmms upx

eqxmms_install:
	$(m) -j $(NUM_JOBS) -C eqxmms install

eqxmms_ee:
	$(m) -j $(NUM_JOBS) -C eqxmms ee

eqxmms_yac:
	$(m) -j $(NUM_JOBS) -C eqxmms yac

eqxmms_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/eqxmms.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/eqxmms.zip" eqxmms


#
# tkchipmunk
#
.PHONY: tkchipmunk
tkchipmunk:
	$(m) -j $(NUM_JOBS) -C tkchipmunk realclean ; $(m) -j $(NUM_JOBS) -C tkchipmunk bin

tkchipmunk_clean:
	$(m) -j $(NUM_JOBS) -C tkchipmunk realclean

tkchipmunk_bin:
	$(m) -j $(NUM_JOBS) -C tkchipmunk bin

tkchipmunk_upx:
	$(m) -j $(NUM_JOBS) -C tkchipmunk upx

tkchipmunk_install:
	$(m) -j $(NUM_JOBS) -C tkchipmunk install

tkchipmunk_ee:
	$(m) -j $(NUM_JOBS) -C tkchipmunk ee

tkchipmunk_yac:
	$(m) -j $(NUM_JOBS) -C tkchipmunk yac

tkchipmunk_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkchipmunk.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkchipmunk.zip" tkchipmunk


#
# tkmidi
#
.PHONY: tkmidi
tkmidi:
	$(m) -j $(NUM_JOBS) -C tkmidi realclean ; $(m) -j $(NUM_JOBS) -C tkmidi bin

tkmidi_clean:
	$(m) -j $(NUM_JOBS) -C tkmidi realclean

tkmidi_bin:
	$(m) -j $(NUM_JOBS) -C tkmidi bin

tkmidi_upx:
	$(m) -j $(NUM_JOBS) -C tkmidi upx

tkmidi_install:
	$(m) -j $(NUM_JOBS) -C tkmidi install

tkmidi_ee:
	$(m) -j $(NUM_JOBS) -C tkmidi ee

tkmidi_yac:
	$(m) -j $(NUM_JOBS) -C tkmidi yac

tkmidi_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkmidi.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkmidi.zip" tkmidi


#
# tkmidi_alsa
#
.PHONY: tkmidi_alsa
tkmidi_alsa:
	$(m) -j $(NUM_JOBS) -C tkmidi_alsa realclean ; $(m) -j $(NUM_JOBS) -C tkmidi_alsa bin

tkmidi_alsa_clean:
	$(m) -j $(NUM_JOBS) -C tkmidi_alsa realclean

tkmidi_alsa_bin:
	$(m) -j $(NUM_JOBS) -C tkmidi_alsa bin

tkmidi_alsa_upx:
	$(m) -j $(NUM_JOBS) -C tkmidi_alsa upx

tkmidi_alsa_install:
	$(m) -j $(NUM_JOBS) -C tkmidi_alsa install

tkmidi_alsa_ee:
	$(m) -j $(NUM_JOBS) -C tkmidi_alsa ee

tkmidi_alsa_yac:
	$(m) -j $(NUM_JOBS) -C tkmidi_alsa yac

tkmidi_alsa_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkmidi_alsa.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkmidi_alsa.zip" tkmidi_alsa


#
# tkmidi_portmidi
#
.PHONY: tkmidi_portmidi
tkmidi_portmidi:
	$(m) -j $(NUM_JOBS) -C tkmidi_portmidi realclean ; $(m) -j $(NUM_JOBS) -C tkmidi_portmidi bin

tkmidi_portmidi_clean:
	$(m) -j $(NUM_JOBS) -C tkmidi_portmidi realclean

tkmidi_portmidi_bin:
	$(m) -j $(NUM_JOBS) -C tkmidi_portmidi bin

tkmidi_portmidi_upx:
	$(m) -j $(NUM_JOBS) -C tkmidi_portmidi upx

tkmidi_portmidi_install:
	$(m) -j $(NUM_JOBS) -C tkmidi_portmidi install

tkmidi_portmidi_ee:
	$(m) -j $(NUM_JOBS) -C tkmidi_portmidi ee

tkmidi_portmidi_yac:
	$(m) -j $(NUM_JOBS) -C tkmidi_portmidi yac

tkmidi_portmidi_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkmidi_portmidi.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkmidi_portmidi.zip" tkmidi_portmidi


#
# tksmdi
#
.PHONY: tksmdi
tksmdi:
	$(m) -j $(NUM_JOBS) -C tksmdi realclean ; $(m) -j $(NUM_JOBS) -C tksmdi bin

tksmdi_clean:
	$(m) -j $(NUM_JOBS) -C tksmdi realclean

tksmdi_bin:
	$(m) -j $(NUM_JOBS) -C tksmdi bin

tksmdi_upx:
	$(m) -j $(NUM_JOBS) -C tksmdi upx

tksmdi_install:
	$(m) -j $(NUM_JOBS) -C tksmdi install

tksmdi_ee:
	$(m) -j $(NUM_JOBS) -C tksmdi ee

tksmdi_yac:
	$(m) -j $(NUM_JOBS) -C tksmdi yac

tksmdi_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksmdi.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksmdi.zip" tksmdi


#
# tkportaudio
#
.PHONY: tkportaudio
tkportaudio:
	$(m) -j $(NUM_JOBS) -C tkportaudio realclean ; $(m) -j $(NUM_JOBS) -C tkportaudio bin

tkportaudio_clean:
	$(m) -j $(NUM_JOBS) -C tkportaudio realclean

tkportaudio_bin:
	$(m) -j $(NUM_JOBS) -C tkportaudio bin

tkportaudio_upx:
	$(m) -j $(NUM_JOBS) -C tkportaudio upx

tkportaudio_install:
	$(m) -j $(NUM_JOBS) -C tkportaudio install

tkportaudio_ee:
	$(m) -j $(NUM_JOBS) -C tkportaudio ee

tkportaudio_yac:
	$(m) -j $(NUM_JOBS) -C tkportaudio yac

tkportaudio_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkportaudio.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkportaudio.zip" tkportaudio


#
# tkportaudio_oss
#
.PHONY: tkportaudio_oss
tkportaudio_oss:
	$(m) -j $(NUM_JOBS) -C tkportaudio_oss realclean ; $(m) -j $(NUM_JOBS) -C tkportaudio_oss bin

tkportaudio_oss_clean:
	$(m) -j $(NUM_JOBS) -C tkportaudio_oss realclean

tkportaudio_oss_bin:
	$(m) -j $(NUM_JOBS) -C tkportaudio_oss bin

tkportaudio_oss_upx:
	$(m) -j $(NUM_JOBS) -C tkportaudio_oss upx

tkportaudio_oss_install:
	$(m) -j $(NUM_JOBS) -C tkportaudio_oss install

tkportaudio_oss_ee:
	$(m) -j $(NUM_JOBS) -C tkportaudio_oss ee

tkportaudio_oss_yac:
	$(m) -j $(NUM_JOBS) -C tkportaudio_oss yac

tkportaudio_oss_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkportaudio_oss.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkportaudio_oss.zip" tkportaudio_oss


#
# tkportaudio_alsa
#
.PHONY: tkportaudio_alsa
tkportaudio_alsa:
	$(m) -j $(NUM_JOBS) -C tkportaudio_alsa realclean ; $(m) -j $(NUM_JOBS) -C tkportaudio_alsa bin

tkportaudio_alsa_clean:
	$(m) -j $(NUM_JOBS) -C tkportaudio_alsa realclean

tkportaudio_alsa_bin:
	$(m) -j $(NUM_JOBS) -C tkportaudio_alsa bin

tkportaudio_alsa_upx:
	$(m) -j $(NUM_JOBS) -C tkportaudio_alsa upx

tkportaudio_alsa_install:
	$(m) -j $(NUM_JOBS) -C tkportaudio_alsa install

tkportaudio_alsa_ee:
	$(m) -j $(NUM_JOBS) -C tkportaudio_alsa ee

tkportaudio_alsa_yac:
	$(m) -j $(NUM_JOBS) -C tkportaudio_alsa yac

tkportaudio_alsa_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkportaudio_alsa.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkportaudio_alsa.zip" tkportaudio_alsa


#
# tksampler
#
.PHONY: tksampler
tksampler:
	$(m) -j $(NUM_JOBS) -C tksampler realclean ; $(m) -j $(NUM_JOBS) -C tksampler bin

tksampler_clean:
	$(m) -j $(NUM_JOBS) -C tksampler realclean

tksampler_bin:
	$(m) -j $(NUM_JOBS) -C tksampler bin

tksampler_upx:
	$(m) -j $(NUM_JOBS) -C tksampler upx

tksampler_install:
	$(m) -j $(NUM_JOBS) -C tksampler install

tksampler_ee:
	$(m) -j $(NUM_JOBS) -C tksampler ee

tksampler_yac:
	$(m) -j $(NUM_JOBS) -C tksampler yac

tksampler_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksampler.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksampler.zip" tksampler


#
# tksampleedit
#
.PHONY: tksampleedit
tksampleedit:
	$(m) -j $(NUM_JOBS) -C tksampleedit realclean ; $(m) -j $(NUM_JOBS) -C tksampleedit bin

tksampleedit_clean:
	$(m) -j $(NUM_JOBS) -C tksampleedit realclean

tksampleedit_bin:
	$(m) -j $(NUM_JOBS) -C tksampleedit bin

tksampleedit_upx:
	$(m) -j $(NUM_JOBS) -C tksampleedit upx

tksampleedit_install:
	$(m) -j $(NUM_JOBS) -C tksampleedit install

tksampleedit_ee:
	$(m) -j $(NUM_JOBS) -C tksampleedit ee

tksampleedit_yac:
	$(m) -j $(NUM_JOBS) -C tksampleedit yac

tksampleedit_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksampleedit.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksampleedit.zip" tksampleedit


#
# tksidplay2
#
.PHONY: tksidplay2
tksidplay2:
	$(m) -j $(NUM_JOBS) -C tksidplay2 realclean ; $(m) -j $(NUM_JOBS) -C tksidplay2 bin

tksidplay2_clean:
	$(m) -j $(NUM_JOBS) -C tksidplay2 realclean

tksidplay2_bin:
	$(m) -j $(NUM_JOBS) -C tksidplay2 bin

tksidplay2_upx:
	$(m) -j $(NUM_JOBS) -C tksidplay2 upx

tksidplay2_install:
	$(m) -j $(NUM_JOBS) -C tksidplay2 install

tksidplay2_ee:
	$(m) -j $(NUM_JOBS) -C tksidplay2 ee

tksidplay2_yac:
	$(m) -j $(NUM_JOBS) -C tksidplay2 yac

tksidplay2_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksidplay2.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksidplay2.zip" tksidplay2


#
# tkfreeverb
#
.PHONY: tkfreeverb
tkfreeverb:
	$(m) -j $(NUM_JOBS) -C tkfreeverb realclean ; $(m) -j $(NUM_JOBS) -C tkfreeverb bin

tkfreeverb_clean:
	$(m) -j $(NUM_JOBS) -C tkfreeverb realclean

tkfreeverb_bin:
	$(m) -j $(NUM_JOBS) -C tkfreeverb bin

tkfreeverb_upx:
	$(m) -j $(NUM_JOBS) -C tkfreeverb upx

tkfreeverb_install:
	$(m) -j $(NUM_JOBS) -C tkfreeverb install

tkfreeverb_ee:
	$(m) -j $(NUM_JOBS) -C tkfreeverb ee

tkfreeverb_yac:
	$(m) -j $(NUM_JOBS) -C tkfreeverb yac

tkfreeverb_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkfreeverb.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkfreeverb.zip" tkfreeverb


#
# tkanalogrytm
#
.PHONY: tkanalogrytm
tkanalogrytm:
	$(m) -j $(NUM_JOBS) -C tkanalogrytm realclean ; $(m) -j $(NUM_JOBS) -C tkanalogrytm bin

tkanalogrytm_clean:
	$(m) -j $(NUM_JOBS) -C tkanalogrytm realclean

tkanalogrytm_bin:
	$(m) -j $(NUM_JOBS) -C tkanalogrytm bin

tkanalogrytm_upx:
	$(m) -j $(NUM_JOBS) -C tkanalogrytm upx

tkanalogrytm_install:
	$(m) -j $(NUM_JOBS) -C tkanalogrytm install

tkanalogrytm_ee:
	$(m) -j $(NUM_JOBS) -C tkanalogrytm ee

tkanalogrytm_yac:
	$(m) -j $(NUM_JOBS) -C tkanalogrytm yac

tkanalogrytm_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkanalogrytm.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkanalogrytm.zip" tkanalogrytm libanalogrytm


#
# tksynth
#
.PHONY: tksynth
tksynth:
	$(m) -j $(NUM_JOBS) -C tksynth realclean ; $(m) -j $(NUM_JOBS) -C tksynth bin

tksynth_clean:
	$(m) -j $(NUM_JOBS) -C tksynth realclean

tksynth_bin:
	$(m) -j $(NUM_JOBS) -C tksynth bin

tksynth_upx:
	$(m) -j $(NUM_JOBS) -C tksynth upx

tksynth_install:
	$(m) -j $(NUM_JOBS) -C tksynth install

tksynth_ee:
	$(m) -j $(NUM_JOBS) -C tksynth ee

tksynth_yac:
	$(m) -j $(NUM_JOBS) -C tksynth yac

tksynth_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksynth.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksynth.zip" tksynth


#
# tkdist2d
#
.PHONY: tkdist2d
tkdist2d:
	$(m) -j $(NUM_JOBS) -C tkdist2d realclean ; $(m) -j $(NUM_JOBS) -C tkdist2d bin

tkdist2d_clean:
	$(m) -j $(NUM_JOBS) -C tkdist2d realclean

tkdist2d_bin:
	$(m) -j $(NUM_JOBS) -C tkdist2d bin

tkdist2d_upx:
	$(m) -j $(NUM_JOBS) -C tkdist2d upx

tkdist2d_install:
	$(m) -j $(NUM_JOBS) -C tkdist2d install

tkdist2d_ee:
	$(m) -j $(NUM_JOBS) -C tkdist2d ee

tkdist2d_yac:
	$(m) -j $(NUM_JOBS) -C tkdist2d yac

tkdist2d_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkdist2d.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkdist2d.zip" tkdist2d


#
# polyraster
#
.PHONY: polyraster
polyraster:
	$(m) -j $(NUM_JOBS) -C polyraster realclean ; $(m) -j $(NUM_JOBS) -C polyraster bin

polyraster_clean:
	$(m) -j $(NUM_JOBS) -C polyraster realclean

polyraster_bin:
	$(m) -j $(NUM_JOBS) -C polyraster bin

polyraster_upx:
	$(m) -j $(NUM_JOBS) -C polyraster upx

polyraster_install:
	$(m) -j $(NUM_JOBS) -C polyraster install

polyraster_ee:
	$(m) -j $(NUM_JOBS) -C polyraster ee

polyraster_yac:
	$(m) -j $(NUM_JOBS) -C polyraster yac

polyraster_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/polyraster.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/polyraster.zip" polyraster


#
# tkfileutils
#
.PHONY: tkfileutils
tkfileutils:
	$(m) -j $(NUM_JOBS) -C tkfileutils realclean ; $(m) -j $(NUM_JOBS) -C tkfileutils bin

tkfileutils_clean:
	$(m) -j $(NUM_JOBS) -C tkfileutils realclean

tkfileutils_bin:
	$(m) -j $(NUM_JOBS) -C tkfileutils bin

tkfileutils_upx:
	$(m) -j $(NUM_JOBS) -C tkfileutils upx

tkfileutils_install:
	$(m) -j $(NUM_JOBS) -C tkfileutils install

tkfileutils_ee:
	$(m) -j $(NUM_JOBS) -C tkfileutils ee

tkfileutils_yac:
	$(m) -j $(NUM_JOBS) -C tkfileutils yac

tkfileutils_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkfileutils.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkfileutils.zip" tkfileutils


#
# tkvst2
#
.PHONY: tkvst2
tkvst2:
	$(m) -j $(NUM_JOBS) -C tkvst2 realclean ; $(m) -j $(NUM_JOBS) -C tkvst2 bin

tkvst2_clean:
	$(m) -j $(NUM_JOBS) -C tkvst2 realclean

tkvst2_bin:
	$(m) -j $(NUM_JOBS) -C tkvst2 bin

tkvst2_upx:
	$(m) -j $(NUM_JOBS) -C tkvst2 upx

tkvst2_install:
	$(m) -j $(NUM_JOBS) -C tkvst2 install

tkvst2_ee:
	$(m) -j $(NUM_JOBS) -C tkvst2 ee

tkvst2_yac:
	$(m) -j $(NUM_JOBS) -C tkvst2 yac

tkvst2_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkvst2.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkvst2.zip" tkvst2


#
# tkvst2_stub
#
.PHONY: tkvst2_stub
tkvst2_stub:
	$(m) -j $(NUM_JOBS) -C tkvst2_stub realclean ; $(m) -j $(NUM_JOBS) -C tkvst2_stub bin

tkvst2_stub_clean:
	$(m) -j $(NUM_JOBS) -C tkvst2_stub realclean

tkvst2_stub_bin:
	$(m) -j $(NUM_JOBS) -C tkvst2_stub bin

tkvst2_stub_upx:
	$(m) -j $(NUM_JOBS) -C tkvst2_stub upx

tkvst2_stub_install:
	$(m) -j $(NUM_JOBS) -C tkvst2_stub install

tkvst2_stub_ee:
	$(m) -j $(NUM_JOBS) -C tkvst2_stub ee

tkvst2_stub_yac:
	$(m) -j $(NUM_JOBS) -C tkvst2_stub yac

tkvst2_stub_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkvst2_stub.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkvst2_stub.zip" tkvst2_stub


#
# tkvst2_nogui
#
.PHONY: tkvst2_nogui
tkvst2_nogui:
	$(m) -j $(NUM_JOBS) -C tkvst2_nogui realclean ; $(m) -j $(NUM_JOBS) -C tkvst2_nogui bin

tkvst2_nogui_clean:
	$(m) -j $(NUM_JOBS) -C tkvst2_nogui realclean

tkvst2_nogui_bin:
	$(m) -j $(NUM_JOBS) -C tkvst2_nogui bin

tkvst2_nogui_upx:
	$(m) -j $(NUM_JOBS) -C tkvst2_nogui upx

tkvst2_nogui_install:
	$(m) -j $(NUM_JOBS) -C tkvst2_nogui install

tkvst2_nogui_ee:
	$(m) -j $(NUM_JOBS) -C tkvst2_nogui ee

tkvst2_nogui_yac:
	$(m) -j $(NUM_JOBS) -C tkvst2_nogui yac

tkvst2_nogui_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkvst2_nogui.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkvst2_nogui.zip" tkvst2_nogui


#
# tkvst2_macos
#
.PHONY: tkvst2_macos
tkvst2_macos:
	$(m) -j $(NUM_JOBS) -C tkvst2_macos realclean ; $(m) -j $(NUM_JOBS) -C tkvst2_macos bin

tkvst2_macos_clean:
	$(m) -j $(NUM_JOBS) -C tkvst2_macos realclean

tkvst2_macos_bin:
	$(m) -j $(NUM_JOBS) -C tkvst2_macos bin

tkvst2_macos_upx:
	$(m) -j $(NUM_JOBS) -C tkvst2_macos upx

tkvst2_macos_install:
	$(m) -j $(NUM_JOBS) -C tkvst2_macos install

tkvst2_macos_ee:
	$(m) -j $(NUM_JOBS) -C tkvst2_macos ee

tkvst2_macos_yac:
	$(m) -j $(NUM_JOBS) -C tkvst2_macos yac

tkvst2_macos_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkvst2_macos.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkvst2_macos.zip" tkvst2_macos


#
# tkclap
#
.PHONY: tkclap
tkclap:
	$(m) -j $(NUM_JOBS) -C tkclap realclean ; $(m) -j $(NUM_JOBS) -C tkclap bin

tkclap_clean:
	$(m) -j $(NUM_JOBS) -C tkclap realclean

tkclap_bin:
	$(m) -j $(NUM_JOBS) -C tkclap bin

tkclap_upx:
	$(m) -j $(NUM_JOBS) -C tkclap upx

tkclap_install:
	$(m) -j $(NUM_JOBS) -C tkclap install

tkclap_ee:
	$(m) -j $(NUM_JOBS) -C tkclap ee

tkclap_yac:
	$(m) -j $(NUM_JOBS) -C tkclap yac

tkclap_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkclap.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkclap.zip" tkclap


#
# tkradiastools
#
.PHONY: tkradiastools
tkradiastools:
	$(m) -j $(NUM_JOBS) -C tkradiastools realclean ; $(m) -j $(NUM_JOBS) -C tkradiastools bin

tkradiastools_clean:
	$(m) -j $(NUM_JOBS) -C tkradiastools realclean

tkradiastools_bin:
	$(m) -j $(NUM_JOBS) -C tkradiastools bin

tkradiastools_upx:
	$(m) -j $(NUM_JOBS) -C tkradiastools upx

tkradiastools_install:
	$(m) -j $(NUM_JOBS) -C tkradiastools install

tkradiastools_ee:
	$(m) -j $(NUM_JOBS) -C tkradiastools ee

tkradiastools_yac:
	$(m) -j $(NUM_JOBS) -C tkradiastools yac

tkradiastools_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkradiastools.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkradiastools.zip" tkradiastools


#
# tkcustomsynth (st2)
#
.PHONY: tkcustomsynth
tkcustomsynth:
	$(m) -j $(NUM_JOBS) -C tkcustomsynth realclean ; $(m) -j $(NUM_JOBS) -C tkcustomsynth bin

tkcustomsynth_clean:
	$(m) -j $(NUM_JOBS) -C tkcustomsynth realclean

tkcustomsynth_bin:
	$(m) -j $(NUM_JOBS) -C tkcustomsynth bin

tkcustomsynth_upx:
	$(m) -j $(NUM_JOBS) -C tkcustomsynth upx

tkcustomsynth_install:
	$(m) -j $(NUM_JOBS) -C tkcustomsynth install

tkcustomsynth_ee:
	$(m) -j $(NUM_JOBS) -C tkcustomsynth ee

tkcustomsynth_yac:
	$(m) -j $(NUM_JOBS) -C tkcustomsynth yac

tkcustomsynth_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkcustomsynth.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkcustomsynth.zip" tkcustomsynth



#
# tkmacrosynth (st2)
#
.PHONY: tkmacrosynth
tkmacrosynth:
	$(m) -j $(NUM_JOBS) -C tkmacrosynth realclean ; $(m) -j $(NUM_JOBS) -C tkmacrosynth bin

tkmacrosynth_clean:
	$(m) -j $(NUM_JOBS) -C tkmacrosynth realclean

tkmacrosynth_bin:
	$(m) -j $(NUM_JOBS) -C tkmacrosynth bin

tkmacrosynth_upx:
	$(m) -j $(NUM_JOBS) -C tkmacrosynth upx

tkmacrosynth_install:
	$(m) -j $(NUM_JOBS) -C tkmacrosynth install

tkmacrosynth_ee:
	$(m) -j $(NUM_JOBS) -C tkmacrosynth ee

tkmacrosynth_yac:
	$(m) -j $(NUM_JOBS) -C tkmacrosynth yac

tkmacrosynth_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkmacrosynth.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkmacrosynth.zip" tkmacrosynth


#
# tksynthgenproxy (st2)
#
.PHONY: tksynthgenproxy
tksynthgenproxy:
	$(m) -j $(NUM_JOBS) -C tksynthgenproxy realclean ; $(m) -j $(NUM_JOBS) -C tksynthgenproxy bin

tksynthgenproxy_clean:
	$(m) -j $(NUM_JOBS) -C tksynthgenproxy realclean

tksynthgenproxy_bin:
	$(m) -j $(NUM_JOBS) -C tksynthgenproxy bin

tksynthgenproxy_upx:
	$(m) -j $(NUM_JOBS) -C tksynthgenproxy upx

tksynthgenproxy_install:
	$(m) -j $(NUM_JOBS) -C tksynthgenproxy install

tksynthgenproxy_ee:
	$(m) -j $(NUM_JOBS) -C tksynthgenproxy ee

tksynthgenproxy_yac:
	$(m) -j $(NUM_JOBS) -C tksynthgenproxy yac

tksynthgenproxy_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksynthgenproxy.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksynthgenproxy.zip" tksynthgenproxy


#
# tkmidipipe
#
.PHONY: tkmidipipe
tkmidipipe:
	$(m) -j $(NUM_JOBS) -C tkmidipipe realclean ; $(m) -j $(NUM_JOBS) -C tkmidipipe bin

tkmidipipe_clean:
	$(m) -j $(NUM_JOBS) -C tkmidipipe realclean

tkmidipipe_bin:
	$(m) -j $(NUM_JOBS) -C tkmidipipe bin

tkmidipipe_upx:
	$(m) -j $(NUM_JOBS) -C tkmidipipe upx

tkmidipipe_install:
	$(m) -j $(NUM_JOBS) -C tkmidipipe install

tkmidipipe_ee:
	$(m) -j $(NUM_JOBS) -C tkmidipipe ee

tkmidipipe_yac:
	$(m) -j $(NUM_JOBS) -C tkmidipipe yac

tkmidipipe_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkmidipipe.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkmidipipe.zip" tkmidipipe


#
# tksamplechain
#
.PHONY: tksamplechain
tksamplechain:
	$(m) -j $(NUM_JOBS) -C tksamplechain realclean ; $(m) -j $(NUM_JOBS) -C tksamplechain bin

tksamplechain_clean:
	$(m) -j $(NUM_JOBS) -C tksamplechain realclean

tksamplechain_bin:
	$(m) -j $(NUM_JOBS) -C tksamplechain bin

tksamplechain_upx:
	$(m) -j $(NUM_JOBS) -C tksamplechain upx

tksamplechain_install:
	$(m) -j $(NUM_JOBS) -C tksamplechain install

tksamplechain_ee:
	$(m) -j $(NUM_JOBS) -C tksamplechain ee

tksamplechain_yac:
	$(m) -j $(NUM_JOBS) -C tksamplechain yac

tksamplechain_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksamplechain.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksamplechain.zip" tksamplechain


#
# tkbluetooth
#
.PHONY: tkbluetooth
tkbluetooth:
	$(m) -j $(NUM_JOBS) -C tkbluetooth realclean ; $(m) -j $(NUM_JOBS) -C tkbluetooth bin

tkbluetooth_clean:
	$(m) -j $(NUM_JOBS) -C tkbluetooth realclean

tkbluetooth_bin:
	$(m) -j $(NUM_JOBS) -C tkbluetooth bin

tkbluetooth_upx:
	$(m) -j $(NUM_JOBS) -C tkbluetooth upx

tkbluetooth_install:
	$(m) -j $(NUM_JOBS) -C tkbluetooth install

tkbluetooth_ee:
	$(m) -j $(NUM_JOBS) -C tkbluetooth ee

tkbluetooth_yac:
	$(m) -j $(NUM_JOBS) -C tkbluetooth yac

tkbluetooth_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkbluetooth.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkbluetooth.zip" tkbluetooth


#
# tktriangulate
#
.PHONY: tktriangulate
tktriangulate:
	$(m) -j $(NUM_JOBS) -C tktriangulate realclean ; $(m) -j $(NUM_JOBS) -C tktriangulate bin

tktriangulate_clean:
	$(m) -j $(NUM_JOBS) -C tktriangulate realclean

tktriangulate_bin:
	$(m) -j $(NUM_JOBS) -C tktriangulate bin

tktriangulate_upx:
	$(m) -j $(NUM_JOBS) -C tktriangulate upx

tktriangulate_install:
	$(m) -j $(NUM_JOBS) -C tktriangulate install

tktriangulate_ee:
	$(m) -j $(NUM_JOBS) -C tktriangulate ee

tktriangulate_yac:
	$(m) -j $(NUM_JOBS) -C tktriangulate yac

tktriangulate_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tktriangulate.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tktriangulate.zip" tktriangulate


#
# tkzip
#
.PHONY: tkzip
tkzip:
	$(m) -j $(NUM_JOBS) -C tkzip realclean ; $(m) -j $(NUM_JOBS) -C tkzip bin

tkzip_clean:
	$(m) -j $(NUM_JOBS) -C tkzip realclean

tkzip_bin:
	$(m) -j $(NUM_JOBS) -C tkzip bin

tkzip_upx:
	$(m) -j $(NUM_JOBS) -C tkzip upx

tkzip_install:
	$(m) -j $(NUM_JOBS) -C tkzip install

tkzip_ee:
	$(m) -j $(NUM_JOBS) -C tkzip ee

tkzip_yac:
	$(m) -j $(NUM_JOBS) -C tkzip yac

tkzip_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkzip.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkzip.zip" tkzip


#
# tksqlite
#
.PHONY: tksqlite
tksqlite:
	$(m) -j $(NUM_JOBS) -C tksqlite realclean ; $(m) -j $(NUM_JOBS) -C tksqlite bin

tksqlite_clean:
	$(m) -j $(NUM_JOBS) -C tksqlite realclean

tksqlite_bin:
	$(m) -j $(NUM_JOBS) -C tksqlite bin

tksqlite_upx:
	$(m) -j $(NUM_JOBS) -C tksqlite upx

tksqlite_install:
	$(m) -j $(NUM_JOBS) -C tksqlite install

tksqlite_ee:
	$(m) -j $(NUM_JOBS) -C tksqlite ee

tksqlite_yac:
	$(m) -j $(NUM_JOBS) -C tksqlite yac

tksqlite_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tksqlite.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tksqlite.zip" tksqlite


#
# tkspeexdsp
#
.PHONY: tkspeexdsp
tkspeexdsp:
	$(m) -j $(NUM_JOBS) -C tkspeexdsp realclean ; $(m) -j $(NUM_JOBS) -C tkspeexdsp bin

tkspeexdsp_clean:
	$(m) -j $(NUM_JOBS) -C tkspeexdsp realclean

tkspeexdsp_bin:
	$(m) -j $(NUM_JOBS) -C tkspeexdsp bin

tkspeexdsp_upx:
	$(m) -j $(NUM_JOBS) -C tkspeexdsp upx

tkspeexdsp_install:
	$(m) -j $(NUM_JOBS) -C tkspeexdsp install

tkspeexdsp_ee:
	$(m) -j $(NUM_JOBS) -C tkspeexdsp ee

tkspeexdsp_yac:
	$(m) -j $(NUM_JOBS) -C tkspeexdsp yac

tkspeexdsp_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkspeexdsp.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkspeexdsp.zip" tkspeexdsp


#
# tkminnie
#
.PHONY: tkminnie
tkminnie:
	$(m) -j $(NUM_JOBS) -C minnie/tkminnie realclean ; $(m) -j $(NUM_JOBS) -C minnie/tkminnie bin

tkminnie_clean:
	$(m) -j $(NUM_JOBS) -C minnie/tkminnie realclean

tkminnie_bin:
	$(m) -j $(NUM_JOBS) -C minnie/tkminnie bin

tkminnie_upx:
	$(m) -j $(NUM_JOBS) -C minnie/tkminnie upx

tkminnie_install:
	$(m) -j $(NUM_JOBS) -C minnie/tkminnie install
	$(m) -C minnie/tools/mib install

tkminnie_ee:
	$(m) -j $(NUM_JOBS) -C minnie/tkminnie ee

tkminnie_yac:
	$(m) -j $(NUM_JOBS) -C minnie/tkminnie yac

tkminnie_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/minnie.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/minnie.zip" minnie


#
# tkreplay
#
.PHONY: tkreplay
tkreplay:
	$(m) -j $(NUM_JOBS) -C tks-projects/apps/remote clean ; $(m) -j $(NUM_JOBS) -C tks-projects/apps/remote bin

tkreplay_clean:
	$(m) -j $(NUM_JOBS) -C tks-projects/apps/remote clean

tkreplay_bin:
	$(m) -j $(NUM_JOBS) -C tks-projects/apps/remote bin

tkreplay_install:
	$(m) -j $(NUM_JOBS) -C tks-projects/apps/remote install

tkreplay_ee:
	$(m) -j $(NUM_JOBS) -C tks-projects/apps/remote/replay/tkreplay ee

tkreplay_yac:
	$(m) -j $(NUM_JOBS) -C tks-projects/apps/remote/replay/tkreplay yac

tkreplay_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/tkreplay.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/tkreplay.zip" tks-projects/apps/remote/


#
# synergy_replay
#
.PHONY: synergy_replay_zip
synergy_replay_zip:
	$(RM) "$(TKS_ZIP_PREFIX)/synergy_replay.zip" ; $(ZIP) -r -9 "$(TKS_ZIP_PREFIX)/synergy_replay.zip" synergy_replay


# ------------------------------------------------------------------------------

.PHONY: tsl_install
tsl_install:
	$(m) -j1 $(ALL_TSL_TARGETS)

.PHONY: tkx_install
tkx_install:
	$(m) -j1 $(ALL_TKX_TARGETS)

.PHONY: all_install_sync
all_install_sync: tks_install plugins_install tsl_install tkx_install
	@echo "tks + plugins + tsl + tkx install finished at `date +%H:%M`."

.PHONY: all_install
all_install:
	( if ! [ -e "$(TKS_PREFIX)/" ]; then mkdir -p "$(TKS_PREFIX)/"; fi )
	$(m) -j1 all_install_sync

.PHONY: all_ee
all_ee: tks_ee plugins_ee

.PHONY: all_zip
all_zip: tks_zip tks_build_zip yac_zip plugins_zip all_tsl_zip all_app_zip all_examples_zip synergy_replay_zip $(EXTRA_ZIP_TARGETS)
	@echo "all_zip finished at `date +%H:%M`."

.PHONY: zip
zip: all_zip

.PHONY: realclean
realclean: all_clean
	$(RM) `$(FIND) . -name \*\~ -o -name \*.o -o -name \*.obj -o -name \*.exp -o -name \*.plg -o -name \*.ncb -o -name \*.manifest -o -name .DS_Store -o -name \*.tmp` -o -name \*.map
