#
# Makefile for tksdl [sdl3] plugin on Linux / GCC / Clang platform
#
# (c) 2001-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tksdl

PLAF_OBJ= Clipboard_SDL3.o

EXTRAFLAGS = -DTKSDL_BUILD

EXTRAFLAGS += -DUSE_JOYSTICKS

include make.objects

EXTRAFLAGS += -I/usr/include -I/usr/local/include -I/usr/X11R6/include
EXTRAFLAGS += -DHAVE_X11 -DDX_GLSWAPINTERVALEXT -DHAVE_TIMERFD

EXTRALIBS= -lSDL3 -lGL -lX11 -lXext

include ../build_linux.mk
