
ALL_SRC= \
	Prophet08.tks \
	Prophet08.xfm

syntheditor_dsi_prophet08.tsl: $(ALL_SRC)
	tks -cl syntheditor_dsi_prophet08 && mv syntheditor_dsi_prophet08.tsl ../libraries/

.PHONY: clean
clean:
	rm -f syntheditor_dsi_prophet08.tsl
