#
# Makefile for tkchipmunk plugin on Windows / Visual C++ platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkchipmunk

#CHIPMUNK=Chipmunk-4.0.2
CHIPMUNK=Chipmunk2D-7.0.2

# fixes compiler warning with VC 12.0
CFLAGS += -D_ALLOW_KEYWORD_MACROS

EXTRAFLAGS= -I"$(CHIPMUNK)/src" -I"$(CHIPMUNK)/include"
EXTRAFLAGS += -DNDEBUG

EXTRALIBS=

PLAF_OBJ=

# Note: The sources need to be compiled as C++ as long as MSVC is not fully C99 compliant
CFLAGS += -Dinline=__inline $(EXTRAFLAGS) -TP

include make.objects

include ../build_msvc.mk
