#
# Makefile for tkchipmunk plugin on Linux / GCC platform
# 
# (c) 2008-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkchipmunk

CHIPMUNK=Chipmunk2D-7.0.2

EXTRAFLAGS= -I"$(CHIPMUNK)/src" -I"$(CHIPMUNK)/include" 

CFLAGS += -std=c99

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_linux.mk
