#
# Makefile for tkchipmunk plugin on MinGW / GCC platform
# 
# (c) 2008-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tkchipmunk

CHIPMUNK=Chipmunk-4.0.2

EXTRAFLAGS= -I"$(CHIPMUNK)/src" 
CFLAGS += -std=c99

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_mingw.mk
