#
# Makefile for tkchipmunk plugin on macOS / GCC platform
#
# (c) 2023-2025 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tkchipmunk

CHIPMUNK=Chipmunk2D-7.0.2

EXTRAFLAGS= -I"$(CHIPMUNK)/src" -I"$(CHIPMUNK)/include"

ifeq ($(RELEASE),y)
EXTRAFLAGS+= -DNDEBUG
endif

CFLAGS += -std=c99

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../plugin_macos.mk
