#
# Makefile for tkchipmunk plugin on Linux / GCC / Clang platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkchipmunk

CHIPMUNK=Chipmunk2D-7.0.2

EXTRAFLAGS= -I"$(CHIPMUNK)/src" -I"$(CHIPMUNK)/include"

CFLAGS += -std=c99

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_linux.mk
