// ---- ying_cp_CpPolyShape.cpp: auto generated by YInG - the YAC interface generator (Sun, 26/Sep/2021 12:44:11)

void* YAC_CALL CpPolyShape___getVerts(void *                       );
sSI   YAC_CALL CpPolyShape___initPoly(void *, yacmemptr            );
void  YAC_CALL CpPolyShape___New    (void *, yacmemptr, YAC_Value *);

// ------------------ YAC class "CpPolyShape" reflection map (implementation) ------------------
sUI          YAC_VCALL CpPolyShape::yacMemberGetNum                  (void) {return 0;}
const char **YAC_VCALL CpPolyShape::yacMemberGetNames                (void) {return 0;}
const sUI   *YAC_VCALL CpPolyShape::yacMemberGetTypes                (void) {return 0;}
const char **YAC_VCALL CpPolyShape::yacMemberGetObjectTypes          (void) {return 0;}
const sU8  **YAC_VCALL CpPolyShape::yacMemberGetOffsets              (void) {return (const sU8**)0;}
sUI          YAC_VCALL CpPolyShape::yacMethodGetNum                  (void) {return 4;}
const char **YAC_VCALL CpPolyShape::yacMethodGetNames                (void) {static const char *r[]={"operator", "getVerts", "initPoly", "New"}; return r;}
const sUI   *YAC_VCALL CpPolyShape::yacMethodGetNumParameters        (void) {static const sUI r[]={2, 0, 4, 4}; return r;}
const sUI  **YAC_VCALL CpPolyShape::yacMethodGetParameterTypes       (void) {static const sUI rt0[]={1,3};static const sUI rt1[]={0,};static const sUI rt2[]={3, 3, 3, 2,};static const sUI rt3[]={3, 3, 3, 2,};static const sUI *r[]={rt0, rt1, rt2, rt3}; return r;}
const char***YAC_VCALL CpPolyShape::yacMethodGetParameterObjectTypes (void) {static const char *rs0[]={0,"",};static const char *rs1[]={(const char*)0,};static const char *rs2[]={"CpBody", (const char*)0, (const char*)0, (const char*)0,};static const char *rs3[]={"CpBody", (const char*)0, (const char*)0, (const char*)0,};static const char**r[]={rs0, rs1, rs2, rs3}; return r;}
const sUI   *YAC_VCALL CpPolyShape::yacMethodGetReturnTypes          (void) {static const sUI r[]={4, 3, 1, 4}; return r;}
const char **YAC_VCALL CpPolyShape::yacMethodGetReturnObjectTypes    (void) {static const char *r[]={"", (const char*)0, (const char*)0, (const char*)0}; return r;}
const void **YAC_VCALL CpPolyShape::yacMethodGetAdr                  (void) {static const void *r[]={(void*)Object__operator, (void*)CpPolyShape___getVerts, (void*)CpPolyShape___initPoly, (void*)CpPolyShape___New}; return r;}
sUI          YAC_VCALL CpPolyShape::yacConstantGetNum                (void) {return 0;}
const char **YAC_VCALL CpPolyShape::yacConstantGetNames              (void) {static const char*r[]={""}; return r;}
const sUI   *YAC_VCALL CpPolyShape::yacConstantGetTypes              (void) {static const sUI r[]={0}; return r;}
yacmemptr    YAC_VCALL CpPolyShape::yacConstantGetValues             (void) {static sUI r[]={0,};yacmemptr m; m.ui=(sUI*)r; return m;}

YAC_C(CpPolyShape, "CpPolyShape");

void* YAC_CALL CpPolyShape___getVerts(void *_o                               ) {return (void*)((CpPolyShape*)_o)->_getVerts();}
sSI   YAC_CALL CpPolyShape___initPoly(void *_o, yacmemptr _args              ) {if(YAC_BCHK(_args.mem[0].o, clid_CpBody)){ return (sSI)((CpPolyShape*)_o)->_initPoly((CpBody*)_args.mem[0].o, _args.mem[1].o, _args.mem[2].o, _args.mem[3].f32);}return 0;}
void  YAC_CALL CpPolyShape___New    (void *_o, yacmemptr _args, YAC_Value *_r) {if(YAC_BCHK(_args.mem[0].o, clid_CpBody)){ ((CpPolyShape*)_o)->_New((CpBody*)_args.mem[0].o, _args.mem[1].o, _args.mem[2].o, _args.mem[3].f32, _r);}}
