#
# Makefile for tkmidi<alsa> plugin on Linux / GCC platform
# 
# (c) 2006-2014 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkmidi

EXTRAFLAGS= 

EXTRALIBS= -lasound

PLAF_OBJ= 

include make.objects

include ../plugin_linux.mk
