#
# Makefile for tkmidi<alsa> plugin on Linux / GCC / Clang platform
#
# (c) 2006-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkmidi

EXTRAFLAGS=

EXTRALIBS= -lasound

PLAF_OBJ=

include make.objects

include ../build_linux.mk
