#
# Dummy Makefile for tkmidi_alsa plugin on macOS platform (not really supported, just used for "yac" and "clean" targets)
# 
# (c) 2023 Bastian Spiegel <bs@tkscript.de> 
#
#

include ../install_macos.mk

PLUGIN=tkmidi

include make.objects

include ../plugin_macos.mk
