#
# Makefile for yingtest plugin on macOS / CLANG platform
# 
# (c) 2003-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=yingtest

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
