#
# Makefile for yingtest plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2003-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=yingtest

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
