#
# Makefile for yingtest plugin on Windows / Visual C++ platform
#
# (c) 2003-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=yingtest

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
