#
# Makefile for yingtest plugin on Linux / GCC / Clang platform
#
# (c) 2003-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=yingtest

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_linux.mk
