// ---- ying_test_MyEmptyClass.cpp: auto generated by YInG - the YAC interface generator (Wed, 14/Dec/2022 11:42:32)


// ------------------ YAC class "MyEmptyClass" reflection map (implementation) ------------------
sUI          YAC_VCALL MyEmptyClass::yacMemberGetNum                  (void) {return 0;}
const char **YAC_VCALL MyEmptyClass::yacMemberGetNames                (void) {return 0;}
const sUI   *YAC_VCALL MyEmptyClass::yacMemberGetTypes                (void) {return 0;}
const char **YAC_VCALL MyEmptyClass::yacMemberGetObjectTypes          (void) {return 0;}
const sU8  **YAC_VCALL MyEmptyClass::yacMemberGetOffsets              (void) {return (const sU8**)0;}
sUI          YAC_VCALL MyEmptyClass::yacMethodGetNum                  (void) {return 1;}
const char **YAC_VCALL MyEmptyClass::yacMethodGetNames                (void) {static const char *r[]={"operator"}; return r;}
const sUI   *YAC_VCALL MyEmptyClass::yacMethodGetNumParameters        (void) {static const sUI r[]={2}; return r;}
const sUI  **YAC_VCALL MyEmptyClass::yacMethodGetParameterTypes       (void) {static const sUI rt0[]={1,3};static const sUI *r[]={rt0}; return r;}
const char***YAC_VCALL MyEmptyClass::yacMethodGetParameterObjectTypes (void) {static const char *rs0[]={0,"",};static const char**r[]={rs0}; return r;}
const sUI   *YAC_VCALL MyEmptyClass::yacMethodGetReturnTypes          (void) {static const sUI r[]={4}; return r;}
const char **YAC_VCALL MyEmptyClass::yacMethodGetReturnObjectTypes    (void) {static const char *r[]={""}; return r;}
const void **YAC_VCALL MyEmptyClass::yacMethodGetAdr                  (void) {static const void *r[]={(void*)Object__operator}; return r;}
sUI          YAC_VCALL MyEmptyClass::yacConstantGetNum                (void) {return 0;}
const char **YAC_VCALL MyEmptyClass::yacConstantGetNames              (void) {static const char*r[]={""}; return r;}
const sUI   *YAC_VCALL MyEmptyClass::yacConstantGetTypes              (void) {static const sUI r[]={0}; return r;}
yacmemptr    YAC_VCALL MyEmptyClass::yacConstantGetValues             (void) {static sUI r[]={0,};yacmemptr m; m.ui=(sUI*)r; return m;}

YAC_C(MyEmptyClass, "MyEmptyClass");

