
NUM_JOBS:=10

MKFLAGS=
ifneq ($(OPT_SIZE),)
MKFLAGS+= OPT_SIZE=$(OPT_SIZE)
endif
ifneq ($(OPT_LTO),)
MKFLAGS+= OPT_LTO=$(OPT_LTO)
endif
ifneq ($(STFX_SKIP_NAMES_AND_RESETS),)
MKFLAGS+= STFX_SKIP_NAMES_AND_RESETS=$(STFX_SKIP_NAMES_AND_RESETS)
endif
ifneq ($(CYCLE_SKIP_UI),)
MKFLAGS+= CYCLE_SKIP_UI=$(CYCLE_SKIP_UI)
endif
ifneq ($(LOG),)
MKFLAGS+= LOG=$(LOG)
endif

.PHONY: clean
clean:
	+make -j$(NUM_JOBS) -C fx/fx_core                -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C fx/je_ringmod             -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C fx/je_wavefolder          -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C fx/lindenberg_research    -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C fx/obxd_vcf               -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C fx/schroederverb          -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C fx/sql_bootyshifter       -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C fx/valley_plateau         -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C osc/befaco_noise_plethora -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C osc/gm_rng_convolve       -f makefile.msvc clean
##	+make -j$(NUM_JOBS) -C osc/lofi_fm_stack_v1      -f makefile.msvc clean
##	+make -j$(NUM_JOBS) -C osc/fm_stack_v1           -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C osc/fm_stack_v2           -f makefile.msvc clean
	+make -j$(NUM_JOBS) -C cycle                     -f makefile.msvc clean

.PHONY: bin
bin:
	+make -j$(NUM_JOBS) -C fx/fx_core                -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C fx/je_ringmod             -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C fx/je_wavefolder          -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C fx/lindenberg_research    -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C fx/obxd_vcf               -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C fx/schroederverb          -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C fx/sql_bootyshifter       -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C fx/valley_plateau         -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C osc/befaco_noise_plethora -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C osc/gm_rng_convolve       -f makefile.msvc bin $(MKFLAGS)
##	+make -j$(NUM_JOBS) -C osc/lofi_fm_stack_v1      -f makefile.msvc bin $(MKFLAGS)
##	+make -j$(NUM_JOBS) -C osc/fm_stack_v1           -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C osc/fm_stack_v2           -f makefile.msvc bin $(MKFLAGS)
	+make -j$(NUM_JOBS) -C cycle                     -f makefile.msvc bin $(MKFLAGS)

.PHONY: install
install:
	mkdir -p ../../tks-projects/apps/eureka/voice_plugins/fx
	mkdir -p ../../tks-projects/apps/eureka/voice_plugins/osc
	+make -j$(NUM_JOBS) -C fx/fx_core                -f makefile.msvc install
	+make -j$(NUM_JOBS) -C fx/je_ringmod             -f makefile.msvc install
	+make -j$(NUM_JOBS) -C fx/je_wavefolder          -f makefile.msvc install
	+make -j$(NUM_JOBS) -C fx/lindenberg_research    -f makefile.msvc install
	+make -j$(NUM_JOBS) -C fx/obxd_vcf               -f makefile.msvc install
	+make -j$(NUM_JOBS) -C fx/schroederverb          -f makefile.msvc install
	+make -j$(NUM_JOBS) -C fx/sql_bootyshifter       -f makefile.msvc install
	+make -j$(NUM_JOBS) -C fx/valley_plateau         -f makefile.msvc install
	+make -j$(NUM_JOBS) -C osc/befaco_noise_plethora -f makefile.msvc install
	+make -j$(NUM_JOBS) -C osc/gm_rng_convolve       -f makefile.msvc install
##	+make -j$(NUM_JOBS) -C osc/lofi_fm_stack_v1      -f makefile.msvc install
##	+make -j$(NUM_JOBS) -C osc/fm_stack_v1           -f makefile.msvc install
	+make -j$(NUM_JOBS) -C osc/fm_stack_v2           -f makefile.msvc install
	+make -j$(NUM_JOBS) -C cycle                     -f makefile.msvc install
	@echo "voice-plugin install finished"

# utility target for copying auto-generated sources from Eureka plugin folder
.PHONY: update
update:
	+make -j$(NUM_JOBS) -C cycle                     -f makefile.msvc update
