
MKFLAGS=
ifneq ($(NUM_JOBS),)
MKFLAGS+= NUM_JOBS=$(NUM_JOBS)
endif
ifneq ($(OPT_SIZE),)
MKFLAGS+= OPT_SIZE=$(OPT_SIZE)
endif
ifneq ($(OPT_LTO),)
MKFLAGS+= OPT_LTO=$(OPT_LTO)
endif
ifneq ($(STFX_SKIP_NAMES_AND_RESETS),)
MKFLAGS+= STFX_SKIP_NAMES_AND_RESETS=$(STFX_SKIP_NAMES_AND_RESETS)
endif
ifneq ($(CYCLE_SKIP_UI),)
MKFLAGS+= CYCLE_SKIP_UI=$(CYCLE_SKIP_UI)
endif
ifneq ($(LOG),)
MKFLAGS+= LOG=$(LOG)
endif

m=make -f makefile.msvc

.PHONY: clean
clean:
	+$(m) -j$(NUM_JOBS) -C fx/fx_core                clean
	+$(m) -j$(NUM_JOBS) -C fx/je_ringmod             clean
	+$(m) -j$(NUM_JOBS) -C fx/je_wavefolder          clean
	+$(m) -j$(NUM_JOBS) -C fx/lindenberg_research    clean
	+$(m) -j$(NUM_JOBS) -C fx/obxd_vcf               clean
	+$(m) -j$(NUM_JOBS) -C fx/schroederverb          clean
	+$(m) -j$(NUM_JOBS) -C fx/sql_bootyshifter       clean
	+$(m) -j$(NUM_JOBS) -C fx/valley_plateau         clean
	+$(m) -j$(NUM_JOBS) -C osc/befaco_noise_plethora clean
	+$(m) -j$(NUM_JOBS) -C osc/gm_rng_convolve       clean
##	+$(m) -j$(NUM_JOBS) -C osc/lofi_fm_stack_v1      clean
##	+$(m) -j$(NUM_JOBS) -C osc/fm_stack_v1           clean
	+$(m) -j$(NUM_JOBS) -C osc/fm_stack_v2           clean
	+$(m) -j$(NUM_JOBS) -C cycle                     clean

.PHONY: bin
bin:
	+$(m) -j$(NUM_JOBS) -C fx/fx_core                bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C fx/je_ringmod             bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C fx/je_wavefolder          bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C fx/lindenberg_research    bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C fx/obxd_vcf               bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C fx/schroederverb          bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C fx/sql_bootyshifter       bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C fx/valley_plateau         bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C osc/befaco_noise_plethora bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C osc/gm_rng_convolve       bin $(MKFLAGS)
##	+$(m) -j$(NUM_JOBS) -C osc/lofi_fm_stack_v1      bin $(MKFLAGS)
##	+$(m) -j$(NUM_JOBS) -C osc/fm_stack_v1           bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C osc/fm_stack_v2           bin $(MKFLAGS)
	+$(m) -j$(NUM_JOBS) -C cycle                     bin $(MKFLAGS)

.PHONY: install
install:
	mkdir -p ../../tks-projects/apps/eureka/voice_plugins/fx
	mkdir -p ../../tks-projects/apps/eureka/voice_plugins/osc
	+$(m) -j$(NUM_JOBS) -C fx/fx_core                install
	+$(m) -j$(NUM_JOBS) -C fx/je_ringmod             install
	+$(m) -j$(NUM_JOBS) -C fx/je_wavefolder          install
	+$(m) -j$(NUM_JOBS) -C fx/lindenberg_research    install
	+$(m) -j$(NUM_JOBS) -C fx/obxd_vcf               install
	+$(m) -j$(NUM_JOBS) -C fx/schroederverb          install
	+$(m) -j$(NUM_JOBS) -C fx/sql_bootyshifter       install
	+$(m) -j$(NUM_JOBS) -C fx/valley_plateau         install
	+$(m) -j$(NUM_JOBS) -C osc/befaco_noise_plethora install
	+$(m) -j$(NUM_JOBS) -C osc/gm_rng_convolve       install
##	+$(m) -j$(NUM_JOBS) -C osc/lofi_fm_stack_v1      install
##	+$(m) -j$(NUM_JOBS) -C osc/fm_stack_v1           install
	+$(m) -j$(NUM_JOBS) -C osc/fm_stack_v2           install
	+$(m) -j$(NUM_JOBS) -C cycle                     install
	@echo "voice-plugin install finished"

# utility target for copying auto-generated sources from Eureka plugin folder
.PHONY: update
update:
	+$(m) -j$(NUM_JOBS) -C cycle                     update
