#
# Makefile for tkmath on macOS / Clang platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tkmath

EXTRAFLAGS= -DDX_USE_C99_COMPLEX -DHAVE_HYPOTF
# -DUSE_DYNAMIC_ORDER

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_macos.mk
