#
# Makefile for tkmath on Windows / Visual C++ platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkmath

EXTRAFLAGS= -DHAVE_HYPOTF
# -DUSE_DYNAMIC_ORDER

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
