#
# Makefile for tkmath on MingW / GCC platform
# 
# (c) 2008-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tkmath

EXTRAFLAGS= -DUSE_DYNAMIC_ORDER

EXTRALIBS= 

PLAF_OBJ=

include make.objects

include ../plugin_mingw.mk
