#
# Makefile for tkmath on Linux / GCC platform
# 
# (c) 2008-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkmath

EXTRAFLAGS= -DDX_USE_C99_COMPLEX
# -DUSE_DYNAMIC_ORDER

EXTRALIBS= 

PLAF_OBJ=

include make.objects

include ../plugin_linux.mk
