#
# Makefile for tkmath + Microsoft Visual C++ 2003/2005/2008 ToolKit
# 
# (c) 2008-2020 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkmath

EXTRAFLAGS=
# -DUSE_DYNAMIC_ORDER

EXTRALIBS= 

PLAF_OBJ=

include make.objects

include ../plugin_msvc.mk
