#
# Makefile for tksdl_net plugin on Linux / GCC platform
# 
# (c) 2001-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tksdl_net

PLAF_OBJ=

EXTRAFLAGS= -I/usr/include -I/usr/local/include
#-DDX_GLSWAPINTERVALEXT

EXTRALIBS= -lSDL -lSDL_net -lGL -lGLU -lX11 -lXext

include make.objects

include ../plugin_linux.mk
