#
# Makefile for tksdl_net plugin on macOS
# 
# (c) 2001-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tksdl_net

PLAF_OBJ=

EXTRAFLAGS= -I/usr/include -I/usr/local/include
#-DDX_GLSWAPINTERVALEXT

EXTRALIBS= -lSDL -lSDL_net

include make.objects

include ../plugin_macos.mk
