#
# Makefile for tksampler plugin on Windows / Visual C++ platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

#FORCE_NO_WINDDK=y

include ../install_msvc.mk

PLUGIN=tksampler

EXTRAFLAGS=
#EXTRAFLAGS+= -DTKSAMPLER_WAVEPATH

EXTRALIBS=

MKFLAGS= RELEASE=y
ifneq ($(OPT_SIZE),)
MKFLAGS+= OPT_SIZE=$(OPT_SIZE)
endif
ifneq ($(OPT_LTO),)
MKFLAGS+= OPT_LTO=$(OPT_LTO)
endif
ifneq ($(STFX_SKIP_NAMES_AND_RESETS),)
MKFLAGS+= STFX_SKIP_NAMES_AND_RESETS=$(STFX_SKIP_NAMES_AND_RESETS)
endif
ifneq ($(CYCLE_SKIP_UI),)
MKFLAGS+= CYCLE_SKIP_UI=$(CYCLE_SKIP_UI)
endif

PLAF_OBJ =

include make.objects

CLEAN_RULES   += clean_plugins
BIN_RULES     += bin_plugins
INSTALL_RULES += install_plugins

.PHONY: clean_plugins
clean_plugins:
	+make -j $(NUMJOBS) -C plugins -f makefile.msvc clean $(MKFLAGS)

.PHONY: bin_plugins
bin_plugins:
	+make -j $(NUMJOBS) -C plugins -f makefile.msvc bin $(MKFLAGS)

.PHONY: install_plugins
install_plugins:
	+make -C plugins -f makefile.msvc install $(MKFLAGS)

include ../build_msvc.mk

.PHONY: tbl
tbl:
	tks gen_plugin_alg_int.tks && touch StSampleVoice.cpp && make -f makefile.msvc $(MKFLAGS) -j1 bin && make -f makefile.msvc $(MKFLAGS) install

.PHONY: bin_sr
bin_sr:
	+make -f makefile.msvc STFX_SKIP_MAIN_INIT=1 STFX_SKIP_NAMES_AND_RESETS=1 CYCLE_SKIP_UI=1 $(MKFLAGS) bin
