#
# Makefile for tksampler plugin on macOS / Clang platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksampler

EXTRAFLAGS=
#EXTRAFLAGS+= -DTKSAMPLER_WAVEPATH

EXTRALIBS=

MKFLAGS= RELEASE=y
ifneq ($(OPT_SIZE),)
MKFLAGS+= OPT_SIZE=$(OPT_SIZE)
endif
ifneq ($(OPT_LTO),)
MKFLAGS+= OPT_LTO=$(OPT_LTO)
endif
ifneq ($(STFX_SKIP_NAMES_AND_RESETS),)
MKFLAGS+= STFX_SKIP_NAMES_AND_RESETS=$(STFX_SKIP_NAMES_AND_RESETS)
endif
ifneq ($(CYCLE_SKIP_UI),)
MKFLAGS+= CYCLE_SKIP_UI=$(CYCLE_SKIP_UI)
endif

PLAF_OBJ=

include make.objects

CLEAN_RULES   += clean_plugins
BIN_RULES     += bin_plugins
INSTALL_RULES += install_plugins

.PHONY: clean_plugins
clean_plugins:
	+make -j $(NUMJOBS) -C plugins -f makefile.macos $(MKFLAGS) clean 

.PHONY: bin_plugins
bin_plugins:
	+make -j $(NUMJOBS) -C plugins -f makefile.macos $(MKFLAGS) bin

.PHONY: install_plugins
install_plugins:
	+make -C plugins -f makefile.macos $(MKFLAGS) install

include ../build_macos.mk

.PHONY: bin_sr
bin_sr:
	+make -f makefile.macos STFX_SKIP_MAIN_INIT=1 STFX_SKIP_NAMES_AND_RESETS=1 CYCLE_SKIP_UI=1 $(MKFLAGS) bin
