#
# Makefile for tksampler plugin on Linux / GCC / Clang platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tksampler

EXTRAFLAGS=
#EXTRAFLAGS+= -DTKSAMPLER_WAVEPATH

EXTRALIBS=

MKFLAGS= RELEASE=y OPT_SIZE=$(OPT_SIZE) OPT_LTO=$(OPT_LTO)

PLAF_OBJ=

include make.objects

CLEAN_RULES   += clean_plugins
BIN_RULES     += bin_plugins
INSTALL_RULES += install_plugins

.PHONY: clean_plugins
clean_plugins:
	+make -j $(NUMJOBS) -C plugins -f makefile.linux clean $(MKFLAGS)

.PHONY: bin_plugins
bin_plugins:
	+make -j $(NUMJOBS) -C plugins -f makefile.linux bin $(MKFLAGS)

.PHONY: install_plugins
install_plugins:
	+make -C plugins -f makefile.linux install $(MKFLAGS)

include ../build_linux.mk

.PHONY: bin_sr
bin_sr:
	+make -f makefile.linux STFX_SKIP_MAIN_INIT=1 STFX_SKIP_NAMES_AND_RESETS=1 bin $(MKFLAGS)
