#
# Makefile for tksampler plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
#
# (c) 2009-2020 Bastian Spiegel <bs@tkscript.de>
#

#FORCE_NO_WINDDK=y

include ../install_msvc.mk

PLUGIN=tksampler

EXTRAFLAGS =

EXTRALIBS=

PLAF_OBJ =

include make.objects

CLEAN_RULES   += clean_plugins
BIN_RULES     += bin_plugins
INSTALL_RULES += install_plugins

.PHONY: clean_plugins
clean_plugins:
	make -j $(NUMJOBS) -C plugins -f makefile.msvc clean

.PHONY: bin_plugins
bin_plugins:
	make -j $(NUMJOBS) -C plugins -f makefile.msvc bin

.PHONY: install_plugins
install_plugins:
	make -C plugins -f makefile.msvc install

include ../plugin_msvc.mk

.PHONY: tbl
tbl:
	tks gen_plugin_alg_int.tks && touch StSampleVoice.cpp && make -f makefile.msvc -j1 bin && make -f makefile.msvc install
