#
# Makefile for tksampler plugin on Linux / GCC platform
#
# (c) 2009-2025 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tksampler

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

CLEAR_RULES   += clean_plugins
BIN_RULES     += bin_plugins
INSTALL_RULES += install_plugins

.PHONY: clean_plugins
clean_plugins:
	make -C plugins -f makefile.linux clean

.PHONY: bin_plugins
bin_plugins:
	make -C plugins -f makefile.linux bin

.PHONY: install_plugins
install_plugins:
	make -C plugins -f makefile.linux install

include ../plugin_linux.mk
