#
# Makefile for tksampler plugin on macOS / GCC platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksampler

EXTRAFLAGS=
#EXTRAFLAGS+= -DTKSAMPLER_WAVEPATH

EXTRALIBS=

PLAF_OBJ=

include make.objects

CLEAN_RULES   += clean_plugins
BIN_RULES     += bin_plugins
INSTALL_RULES += install_plugins

.PHONY: clean_plugins
clean_plugins:
	make -j $(NUMJOBS) -C plugins -f makefile.macos clean

.PHONY: bin_plugins
bin_plugins:
	make -j $(NUMJOBS) -C plugins -f makefile.macos bin

.PHONY: install_plugins
install_plugins:
	make -C plugins -f makefile.macos install

include ../plugin_macos.mk
