#
# Makefile for tksampler plugin on macOS / Clang platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksampler

EXTRAFLAGS=
#EXTRAFLAGS+= -DTKSAMPLER_WAVEPATH
ifeq ($(TKSAMPLER_SKIP_ALG),y)
EXTRAFLAGS += -DTKSAMPLER_SKIP_ALG
endif

EXTRALIBS=

MKFLAGS= RELEASE=y
ifneq ($(NUM_JOBS),)
MKFLAGS+= NUM_JOBS=$(NUM_JOBS)
endif
ifneq ($(OPT_SIZE),)
MKFLAGS+= OPT_SIZE=$(OPT_SIZE)
endif
ifneq ($(OPT_LTO),)
MKFLAGS+= OPT_LTO=$(OPT_LTO)
endif
ifneq ($(STFX_SKIP_NAMES_AND_RESETS),)
MKFLAGS+= STFX_SKIP_NAMES_AND_RESETS=$(STFX_SKIP_NAMES_AND_RESETS)
endif
ifneq ($(CYCLE_SKIP_UI),)
MKFLAGS+= CYCLE_SKIP_UI=$(CYCLE_SKIP_UI)
endif

PLAF_OBJ=

include make.objects

CLEAN_RULES   += clean_plugins
BIN_RULES     += bin_plugins
INSTALL_RULES += install_plugins

.PHONY: clean_plugins
clean_plugins:
	+$(m) -j $(NUM_JOBS) -C plugins $(MKFLAGS) clean 

.PHONY: bin_plugins
bin_plugins:
	+$(m) -j $(NUM_JOBS) -C plugins $(MKFLAGS) bin

.PHONY: install_plugins
install_plugins:
	+$(m) -C plugins $(MKFLAGS) install

include ../build_macos.mk

.PHONY: bin_sr
bin_sr:
	+$(m) STFX_SKIP_MAIN_INIT=1 STFX_SKIP_NAMES_AND_RESETS=1 CYCLE_SKIP_UI=1 TKSAMPLER_SKIP_ALG=y $(MKFLAGS) bin
