#
# Makefile for tksampler plugin on MinGW / GCC platform
# 
# (c) 2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tksampler

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_mingw.mk
