#
# Makefile for tktriangulate plugin on Linux / GCC / Clang platform
#
# (c) 2018-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tktriangulate

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_linux.mk
