#
# Makefile for tktriangulate plugin on macOS / Clang platform
#
# (c) 2018-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tktriangulate

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_macos.mk
