#
# Makefile for tktriangulate plugin + Microsoft Visual C++ 2003 / 2005 / 2008 / 2017 ToolKit
# 
# (c) 2018 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tktriangulate

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
