#
# Makefile for tktriangulate plugin on macOS / GCC platform
# 
# (c) 2018-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tktriangulate

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
