#
# Makefile for tktriangulate plugin on Windows / Visual C++ platform
#
# (c) 2018-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tktriangulate

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
