#
# Makefile for tktriangulate plugin on Linux / GCC platform
# 
# (c) 2018-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tktriangulate

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_linux.mk
