#
# Makefile for tkfreeglut plugin on macOS / GCC platform
# 
# (c) 2008-2024 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tkfreeglut

EXTRAFLAGS += -I/usr/include -I/usr/local/include -DGL_SILENCE_DEPRECATION
EXTRALIBS= -L/usr/lib -L/usr/local/lib -framework OpenGL -lm -lpng -lz

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
