#
# Makefile for tkfreeglut plugin on MingW / GCC platform
# 
# (c) 2008-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tkfreeglut

EXTRAFLAGS= 

EXTRALIBS= -luuid -lopengl32 -lglu32

PLAF_OBJ= 

include make.objects

include ../plugin_mingw.mk
