#
# Makefile for tkfreeglut plugin on Windows / Visual C++ platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkfreeglut

EXTRAFLAGS =

EXTRALIBS= uuid.lib opengl32.lib glu32.lib

PLAF_OBJ =

include make.objects

include ../build_msvc.mk
