#
# Makefile for tkfreeglut plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2008-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkfreeglut

EXTRAFLAGS = 

EXTRALIBS= uuid.lib opengl32.lib glu32.lib

PLAF_OBJ = 

include make.objects

include ../plugin_msvc.mk
