#
# Makefile for tkfreeglut plugin on Linux / GCC / Clang platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkfreeglut

EXTRAFLAGS= -I/usr/include -I/usr/local/include -I/usr/X11R6/include

EXTRALIBS= -L/usr/lib -L/usr/local/lib -L/usr/X11R6/lib -lGL -lGLU -lm -lX11 -lXext

PLAF_OBJ=

include make.objects

include ../build_linux.mk
