#
# Makefile for tkfreetype2 plugin on Windows / Visual C++ platform
#
# (c) 2001-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkfreetype2

FREETYPESRC=freetype-2.12.1

EXTRAFLAGS= -I"$(FREETYPESRC)/include" -I"$(FREETYPESRC)/include/freetype"
EXTRAFLAGS += -DFT_DEBUG_LEVEL_ERROR -DFT_DEBUG_LEVEL_TRACE -DFT2_BUILD_LIBRARY

EXTRALIBS=

PLAF_OBJ=

include make_freetype.objects

include make.objects

ALL_OBJ += $(FT_OBJ)

include ../build_msvc.mk
