// ---- auto generated by YInG - the YAC interface generator (Wed, 31/Jul/2019 21:22:33)
#ifndef __YAC__freetype_h__
#define __YAC__freetype_h__

sUI                                          clid_NativeFT2Face;
YAC_Template <NativeFT2Face>                   *t_NativeFT2Face;

void YAC_CALL YAC_Init_freetype(YAC_Host *_host) {
	// --------------------------------- classes ---------------------------------
	   t_NativeFT2Face            =new YAC_Template <NativeFT2Face>(_host);
	clid_NativeFT2Face            =                t_NativeFT2Face->ctemplate.class_ID;
	// -------------------------------- functions --------------------------------

}

void YAC_CALL YAC_Exit_freetype(YAC_Host *_host) {
	delete t_NativeFT2Face;
}

#endif
