// solid, dotted, dashed and stacked ellipse shapes

style {
  bgcolor          = #eee
  shape            = ellipse
  blend            = srcover
  border_width     = 2
  border_color     = #666
  shape_ellipse_rx = 40
  shape_ellipse_ry = 0
  ipad_v           = 8
  stack_off        = 0.5,4
  stack_alpha_dcy  = 0.7
  align            = left,top
}

graph {
  layout = fixed
  ipad   = 8,16,8,16

  row="b"

  b [border_style=dotted]

}
