// even more simplified debug version of test23d.gr

style def {
   bgcolor=#ddd;
   fgcolor=#007;
}

style sub {
   bgcolor=#e4e4c8;
   fgcolor=#022;
}

style subtable {
   bgcolor=#f4e4c8;
   fgcolor=#022;
   text_pos="left";
}

graph {
   grid    = 24,4
   //rotate = true;
   bgcolor = #fffff8e0

   style=sub;
   1 "Sub 1";
   2 "Sub 2";
   3 "Sub 3" {
     layout=table;

     style=subtable;
     row="a b c";
     row="defgh";
     row="i j  ";
     row="k    ";
   } ;
   1->2;
   1->3;
}
