// "pad", "align" and "border*" node attribute test

style {
   pad              = 8   // pad_t only, replicated to pad_l / pad_b / pad_r
   edge_bend        = 15%
   bgcolor          = #ddd
   fgcolor          = #666
   border_style     = solid
   border_width     = 1.5
   border_color     = #020
   arrow_snap       = 75%
   edge_width_start = 0.1
   edge_width_end   = 2
   edge_width_exp   = -1.5
}

style ctr {
   pad          = "28;24;28;24"
   bgtint       = #10405f9f
   shape        = round
   border_style = solid
   border_width = 1.75
   border_color = #f00
   ipad         = 4
   icon         = "penguin"
}

layout=fixed
zero_margin=0
pad=2;4;2;4

row="abc";
row="def";
row="ghi";

a "Top / Left"   [align="right;centery"        border_dir="right;bottom"];
b "Top / Center" [align="center"               border_dir="bottom"];
c "Top / Right"  [align="left;centery"         border_dir="left;bottom"];

d "Center / Left"  [align="right;centery"      border_dir="right"];
e "center\nnode"   [class=ctr align="expand"   border_dir="all"];
f "Center / Right" [align="left;centery"       border_dir="left"]

g "Bottom / Left"   [align="right;centery"     border_dir="right;top"];
h "Bottom / Center" [align="center"            border_dir="top"];
i "Bottom / Right"  [align="left;centery"      border_dir="left;top"];

a->e
b->e
c->e
d->e
f->e
g->e
h->e
i->e
