// - ipl subtree from Cycle patch
// - flip-cell optimization

style def {
  bgcolor=#eee
  fgcolor=#111
  arrow_fgcolor=#e12
}

graph {
  grid       = 96,8
  flip_x_opt = true
  flip_y_opt = true
  slant      = true

  b "input b" [bgcolor=#77a fgcolor=#fff]
  1b "1b.tri2mul"
  2b "2b.tri1" [bgcolor=#beb]
  3b "3b.tri1mul"
  4b "4b.tri2" [bgcolor=#beb]
  5b "5b.tri2.freq"
  6b "6b.tri2.freq.c"
  7b "7b.tri2.freq.c2"  // debug
  8b "8b.dbg1" [bgcolor=#fff6ed]
  9b "9b.dbg2" [bgcolor=#fff6ed]

  2b->3b
  3b->4b
  4b->1b
  1b->b
  5b->4b
  6b->5b
  7b->6b
  8b->6b
  9b->7b
}
