// toplevel diagram test

style def {
  bgcolor            = #eee
  shape              = round
  shape_round_amount = 20%
  shape_round_limit  = 5
  border_width       = 1.5
  pad_r              = 0
  ipad               = 3
  arrow_len          = 9
  arrow_ilen         = 20%
  arrow_angle        = 30
  edge_width         = 1.5
  align              = center
}

style invis {
  def
  shape       = none
  label_style = none
  align       = left,centery
  pad_h       = 0
  s           = 0,16
  pad_l       = 0
}

style lb {
  shape        = rect
  bgcolor      = #f9f9f9
  border_width = 0
  font         = small
}

style rcurve {
  edge_shape=rcurve
}


grid         = 20,16
layout       = fixed;
xmajor       = true;
zero_margin  = false;
row_padding  = 8;
col_padding  = 16;
ipad         = 4;

style=def;
row="a1 b     ";
row="a   3 d e";
row="a2 c     ";
row="a        ";
row="a  g  f  ";
row="a     X  ";
row="a4    h  ";

label_class=lb

a "MBI" [rotate=ccw align=centerx,expandy pad_v=0 pad_l=0 w=48]

style=invis
1
2
3 [s=12 pad_l=16 helper=true]
4 [s=0,16]
X [s=16]

style=def
b "Attribute\nFetch\nUnit"  [pad_b=0]
c "Texture\nFetch\nUnit"    [pad_t=0]
d "Shader"                  [ipad=6,8,6,8 shape=rhomb shape_rhomb_tx=16 shape_rhomb_ty=8 border_width=2 bgtint=#1000ff00]
e "Special\nFunction\nUnit" [pad_v=0 pad_l=24]
f "Crossbar"
g "Scratch\nRAM"
h "Render\nOutput\nUnit"

1->b
2->c
4<>h

b--3 [class=rcurve]
c--3 [class=rcurve]

3->d
d<>e

d->f "Shader result\nstream"
f->g
f->h "Reorder\ndata"
