// "bgfill" node attribute and round shape test

style def {
   pad                = 4,6,4,6
   bgfill             = false
   border_shape       = round
   shape_round_amount = 30%
   shape_round_aspect = "2"
   shape_round_limit  = 8
   border_style       = solid
   border_width       = 0.75
   font               = big8
   fgcolor            = #444
   arrow_angle        = 25
   arrow_len          = 12
   arrow_ilen         = 20%
   ipad               = 1,4,1,4
}

style padt {
  def
  pad_t = 20
}

style esmall {
  def
  arrow_angle = 33
  arrow_len   = 6
}

graph {
   grid        = 16,12
   layout      = fixed;
   col_padding = 2;
   zero_margin = true;
   xmajor_tail = false;
   xmajor_head = true;

   style=def  row="a   b c"
   style=padt row=" d e f"

   a "node a";
   b "node b";
   c "node c";

   f [ipad=2,8,2,8]

   a->b
   b->c

   style=esmall
   d->e
   a->d
   b<>f [arrow_snap=1 arrow_fgcolor_rev=#888
         arrow_angle_rev=30 arrow_len_rev=8
         ]
   e->f [bend=20%]
   f->c [xmajor_tail=true xmajor_head=false]
}
