// "pixel_layout=grid" row+col span and layout weights test. auto-find spans. invisible layout-helper nodes.

style {
  align              = expand
  arrow_len          = 8
  arrow_ilen         = 0.3
  border_width       = 1
  shape              = round//rect
  shape_round_amount = 40%
  shape_round_limit  = 10
  shape_round_aspect = 5
  // bg_pattern           = checker_1
  // bg_pattern           = zigzag_3
     bg_pattern           = dot_4
  /* bg_pattern           = lines_4 */
  /* bg_pattern           = lines_5 */
  /* bg_pattern           = stars_1 */
  /* bg_pattern           = zigzag_4 */
  bg_pattern_intensity = 0.15
}

style invis {
  shape = none
  label_style = none
}

style lb {
  bgcolor      = #ffe
  border_width = 0.5
  border_color = #d4d4d4
  ipad         = "0;1;0;1"
  shape        = rect
  font         = small
  text_pos     = center
}

grid         = 12,12
layout       = fixed;
pixel_layout = grid;
zero_margin  = true;
row_padding  = 16;
col_padding  = 32;
bgcolor      = #fafcf9

row="g d";
row="abd";
row="a d";
row="acd";
row="f d";
row="eee";

a [bgcolor=#fdd w="128" h="80%"  align=center]
b [bgcolor=#dfd s="64,64"        align=center]
c [bgcolor=#ddf s="64,64"        align=center]
d [bgcolor=#dff s="32,100%"      align=centery,right]
e [bgcolor=#ffd w="100%" h="32"  align="centery" pad=24,0,0,0]
f [class=invis s="32,32"]
g [class=invis s="32,32"]

label_class=lb

a->b "a->b"
a->c "a->c"

b->d "b->d"
c->d "c->d"

a.>e "a.>e" [bend=20%]
c=>e "c=>e" [bend=20%]
d>>e "d>>e" [bend=20%]
