// solid, dotted, dashed and stacked rhomb shapes

style {
  bgcolor         = #eee
  shape           = rhomb
  blend           = srcover
  border_width    = 2
  border_color    = #666
  w               = 53
  shape_rhomb_tx  = 16
  shape_rhomb_ty  = 2
  ipad_v          = 6
  stack_alpha_dcy = 0.7
}

graph {
  layout = fixed
  ipad   = 8,16,8,16

  row="abc"
  row="def"
  
  a [border_style=solid]
  b [border_style=dotted]
  c [border_style=dashed]
  a->b->c

  d [border_style=solid  stack=3 stack_alpha_exp=0.9]
  e [border_style=dotted stack=3 stack_alpha_exp=1.7]
  f [border_style=dashed stack=3 stack_alpha_exp=2.3]
  d->e->f
}
