// auto col/row spans and id-renaming

style def {
  bgcolor      = #eee
  fgcolor      = #000
  shape        = round
  border_width = 1
  border_color = #999
  align        = expand
  w = 16
}

style invis {
  bgfill = false
  shape = none
  label_style = none
  s = 1,20
}

layout       = fixed
ipad         = 0
zero_margin  = true;
row_padding  = 0;
col_padding  = 0;

row="aab ";
row="cdbf";  // (note) rows that just contain continued spans will not increase pixel width / height
row="cdbg";  //           => must add invisible layout helper node OR force pixel width / height
row="eee ";

style=invis f g

style=def
a [id=bt_a]  // rename "a" to "bt_a"
b [id=bt_b]  // rename "b" to "bt_b"
c [id=bt_c]  // rename "c" to "bt_c"
d [id=bt_d]  // rename "d" to "bt_d"
e [id=bt_e]  // rename "e" to "bt_e"
