// table layout test (alternative long-id row syntax, nested sub-graph in table cell, nested table in sub-graph)

style default {
   fgcolor = #000000;
   bgcolor = #eeeeee;
}

style sub {
   bgcolor = #e4e4c8;
   fgcolor = #022;
}

style subtable {
   bgcolor  = #f4e4c8;
   fgcolor  = #022;
   text_pos = left
}

graph {
   grid = 24,8
   //rotate = true;

   style=sub;
   1 "Sub 1";
   2 "Sub 2";
   3 "Sub 3" {
     layout=table;

     style=subtable;
     row="a b c";
     row="defgh";
     row="i j  ";
     row="k    ";
   };
   1->2;
   1->3;
}
