// UI test

style {
  bgcolor = #eee
}

style CheckBox {
  fillBG      = 0
  iconSuffix  = _dark
  bgcolor     = #f9f9f9
}

grid        = 12,8
flatten     = false
layout      = fixed
zero_margin = true
col_padding = 4
row_padding = 0.75
pad         = 8
ipad        = 4,4,4,4

row="abegj"
row="hc  j"
row="fd  j"
row="   ii"

a[w=150](Slider min=0 max=100 step=1
                bgtint=#0800ff00 fgtint=#400f604f align=top,left pad=0)
b       (CheckBox caption="Option A" selected=1)
c       (CheckBox caption="Option B" selected=1)
d       (CheckBox caption="Option C" selected=1)
e       (FloatParam cols=5 min=-10 max=10 step=1 mousePrecision=1 value=5)
f       (ComboBox options="One;Two;Three;Four"
                  bgtint=#18307fbf textPlacement=LEFT)
g[sh=3 align=expandy pad=0,4,0,0](Scroller vertical=1 min=0 max=100 step=1
                                           bgtint=#184888ff fgtint=#280f4f60)
h "First in SGX"  [sgx=lb1 align=right,baseline font=smaller]
i "Second in SGX" [sgx=lb1 align=left,baseline  font=smaller]
j[s=32](Dial min=0 max=100 reset=50 value=25
             fillbg=0 bgtint=#1800eeee fgtint=#ff000000)
