// table layout test (alternative long-id row syntax)

style default {
  fgcolor = #000000
  bgcolor = #eeeeee
  align = "expandx;baseliney"
  text_pos = "left"
}

style tbl_def {
  default
}

style tbl_hdr {
  default
     //fgcolor = #ffffcc
     //bgcolor = #000000
  border_style = solid
  border_width = "1.5"
  border_color = #888
  border_dir   = bottom
}

style tbl_inv {
  default
  fgcolor = #ffffff
  bgcolor = #000000
}

style tbl_small {
  default
  fgcolor = #555555
  bgcolor = #eeeeee
}

style tbl_big {
  default
  fgcolor = #557777
  bgcolor = #eeffff
}

grid = 32,16

a->b [fgcolor=#ccc];

b [pad_r=36];

// (note) table sub graphs look like a single cell to other graphs
// (note) layouting merely affects the _inner_ node placement of the sub graph cell
graph T {
   layout=table;  // enable table mode

   // table layout:
   style=tbl_hdr; row="nodeA|     |nodeB|     |nodeC";
   style=tbl_def; row="nodeD|nodeE|nodeF|nodeG|nodeH";
   style=tbl_def; row="nodeI|     |nodeJ|     |     ";
   style=tbl_def; row="nodeK|     |     |     |     ";

   // table cell details:
   nodeA "Header Cell A" [bgcolor=#eef2ee font=big7 ];
   nodeB "Header Cell B" [bgcolor=#def2f2 font=big7 border_dir="bottom;left"];
   nodeC "Header Cell C" [bgcolor=#f2f2de font=big7 border_dir="bottom;left"];

   style=tbl_small;
   nodeD "Small Cell D" [bgcolor=#e0f0e0 font=small];
   nodeE "Small Cell E" [bgcolor=#d0f0f0 font=small];
   nodeF "Cell F"       [class=tbl_inv   font=small];
   nodeG "Small Cell G" [bgcolor=#f0e0e0 font=small];
   nodeH "Small Cell H" [bgcolor=#e0e0d0 font=small];

   style=tbl_big;
   nodeI "Big Cell I" [bgcolor=#d0d0d0 font=big5 align="left;baseline"];
   nodeJ "Big Cell J" [bgcolor=#c0d8d8 font=big3 align="left;baseline"];
}

b->T [arrow_angle=26 arrow_len=12 arrow_ilen=0% arrow_snap=1 fgcolor=#bcc arrow_border_color=#cdd arrow_border_width="0.5"];
