// stacks

style def {
  bgcolor=#eee
  border_width=1.5
  shape=rect
}

layout=fixed

style=def;
row="abc"
row="def"

a->b->c
d->e->f

b [stack=3]

f [stack=3 stack_off=6,7] {
  layout       = table
  shape        = rect
  border_width = 1
  ipad         = 1

  row="ab"
  row="c "

  a "CONST"          [border_width=1 border_dir=right font=small bgtint=#20eeee00]
  b "REGS"           [border_width=0 font=small bgtint=#20eeee00]
  c "Shader Unit(s)" [border_width=1 border_dir=top ipad=8]
}
