// "pixel_layout=grid" row+col span and layout weights test. invisible connection "port" nodes.

style def {
  align                = expand
  arrow_len            = 8
  arrow_ilen           = 0.3
  border_width         = 1
  shape                = round
  shape_round_amount   = 40%
  shape_round_limit    = 10
  shape_round_aspect   = 5
  pad_l                = 64
  pad_r                = 0
  bg_pattern           = stars_1
  bg_pattern_intensity = 0.06
}

style invis {
  def
  shape       = none
  label_style = none
  align       = left,centery
  pad_l       = 0
  pad_r       = 0
}

style lb {
  bgcolor      = #ffe
  border_width = 0.5
  border_color = #d4d4d4
  ipad         = "0;1;0;1"
  shape        = rect
  font         = small
  text_pos     = center
  label_style  = default
}

gradient darklight {
  #ffffffff
  0.5  = #80ffffff
  0.6  = #10ffffff
  0.7  = #00000000
  0.75 = #10333333
  0.85 = #08000000
         #40000000
}

grid         = 16,16
layout       = fixed;
zero_margin  = true;
row_padding  = 16;
col_padding  = 8;
bgcolor      = #fafcf9;

style=def;
row="g  d";
row="a  d";
row="a1bd";
row="a  d";
row="a2cd";
row="a  d";
row="f  d";
row="eeee";

a [bgcolor=#fdd w=96 h=95%   align=center]
b [bgcolor=#dfd s=64,64      align=center pad_b=0 pad_l=48]
c [bgcolor=#ddf s=64,64      align=center pad_t=0 pad_l=48]
d [bgcolor=#dff s=32,100%    align=centery,right]
e [bgcolor=#ffd w=100% h=32  align=centery pad=24,0,0,0 bg_pattern=lines_4 bg_gradient=darklight bg_gradient_shape=v ]

style=invis
1 [s="0.0001,16"]
2 [s=0,16]
f [s=32,32]
g [s=32,32]

label_class=lb

1->b "a->b"
2->c "a->c"

b->d "b->d"
c->d "c->d"

a.>e "a.>e" [bend=20%]
c=>e "c=>e" [bend=20%]
d>>e "d>>e" [bend=20%]
