// sub-graph test
//  - reverse edge
//  - do not unfold sub graph
//  - inherit node bgtint from parent graph

style def {
  bgcolor      = #ddd
  fgcolor      = #000
  ipad         = "2;6;2;6"
  border_width = 0.5
}

style sub {
  def
}

graph {
  grid = 48,4
  ipad = 4

  a "Node A" [ipad="1;6;1;6"]
  b "Node B" [shape=round ipad=3 align=centerx,baseline border_width=2]
  c "Node C" [ipad="1;6;1;6"]

  graph d {
    unfold       = false;
    bgcolor      = #eefef4
    bgtint       = #eceefef4  // (note) alpha channel = tint amount
    shape        = round;
    border_width = 0.5
    border_color = #55666a
    slant        = true
    ipad         = 4

    style=sub
    1 "Sub 1" [pad=0 bgcolor=#6cc0ff align=center shape_round_amount=40%]
    2 "Sub 2"
    3 "Sub Three"
    4 "Sub 4"
    5 "Sub 5"

    1<-2  // reverse edge
    3->1
    4->3
    5->4
  }

  c "Node C"  // already declared, just assign new label

  a->b [arrow_snap=90%]
  b->c

  d->b
}
