
style def {
  bgcolor      = #ddd
  fgcolor      = #111
  shape        = round
  border_width = 1
  border_color = #999
}

style yellow {
  bgcolor=#eec
  fgcolor=#111
}

grid         = 64,6
cell_spacing = 4
slant        = 1
ipad         = 2

a "Ah"
b "Bee" [class=yellow]
c "Ce"
e "Eh"  [class=yellow]
f       [class=yellow]
h "Ha"

a->b->c->d

e->b[bend=75%]
f->e[bend=75%]

g->c[bend=75%]
h->g[bend=75%]
