// gradients

style {
  bgtint       = #eee
  shape        = round
  border_width = 1.5
  s            = 64,64
}

gradient greenblue {
  #6f66ff99
  #6f6699ff
}

gradient greenblue_multi {
         #af2255aa
  0.05 = #af4477dd
  0.35 = #af8ace8a
         #af4679df
  0.85 = #ff408060
         #ff167f39
}

gradient blueyellow {
  #7040a0f0
  #70f0f0a0
}

gradient blueyellow_multi {
  #a0303000
  #a05080b0
}

gradient darklight {
  #ffffffff
  0.4 = #a0ffffff
  0.6 = #10ffffff
  0.7 = #10000000
  #50000000
}

layout = fixed
row="abc"
row="def"
a->b->c
c->d[arrow_snap=80%]
d->e->f

a[bg_gradient=greenblue             bg_gradient_shape=v
  border_gradient=greenblue_multi   border_gradient_shape=v
  border_color=#aaa
  ]
b[bg_gradient=blueyellow            bg_gradient_shape=h
  border_gradient=blueyellow_multi  border_gradient_shape=h
  border_color=#666
  ]
c[bg_gradient=darklight             bg_gradient_shape=r
  border_color=#000
  bgcolor=#eec
  ]

d[bg_gradient=darklight     bg_gradient_shape=h
  border_color=#888
  bgcolor=#eec
  bg_pattern=lines_4        bg_pattern_intensity=0.2
  border_pattern=checker_1  border_pattern_intensity=0.9
  ]

e[bg_gradient=darklight     bg_gradient_shape=v
  border_color=#888
  bgcolor=#eec
  bg_pattern=lines_4        bg_pattern_intensity=0.2
  border_pattern=checker_1  border_pattern_intensity=0.9
  ]

f[bg_gradient=darklight     bg_gradient_shape=r
  border_color=#888
  bgcolor=#eec
  bg_pattern=lines_4        bg_pattern_intensity=0.2
  border_pattern=checker_1  border_pattern_intensity=0.9
  ]
