// - ipl subtree from Cycle patch
// - flip-cell optimization

style def {
  bgcolor = #ffe
  fgcolor = #111
  arrow_shape     = line
  arrow_fgcolor   = #d00
  arrow_linewidth = 2
  arrow_angle     = 30
  arrow_len       = 5
}

graph {
  grid = 64,4
  flip_x_opt = true
  // slant      = true

  b "input b" [bgcolor=#eef]
  1b "1b.tri2mul"
  2b "2b.tri1" [bgcolor=#efe]
  3b "3b.tri1mul"
  4b "4b.tri2" [bgcolor=#efe]
  5b "5b.tri2.freq"
  6b "6b.tri2.freq.c"

  2b->3b
  3b->4b
  4b->1b
  1b->b
  5b->4b
  6b->5b
}
