// "pixel_layout=grid" row+col span and layout weights test.

style {
  align              = expand
  arrow_len          = 8
  arrow_ilen         = 0.3
  border_width       = 1.5
  shape              = round
  shape_round_amount = 40%
  shape_round_limit  = 10
  shape_round_aspect = 5
  // bg_pattern           = checker_1
  // bg_pattern           = zigzag_3
  // bg_pattern           = dot_4
  /* bg_pattern           = lines_4 */
  /* bg_pattern           = lines_5 */
  /* bg_pattern           = stars_1 */
  bg_pattern           = zigzag_4
  bg_pattern_intensity = 0.05
}

style lb {
  bgcolor      = #ffe
  border_width = 0.5
  border_color = #d4d4d4
  ipad         = "0;1;0;1"
  shape        = rect
  font         = small
  text_pos     = center
}

layout       = fixed;
pixel_layout = grid;
zero_margin  = false;
row_padding  = 32;
col_padding  = 32;

row="abd";
row=" c ";
row="e  "

a [bgcolor=#fdd w="128" h="70%"  align=center sh=2]
b [bgcolor=#dfd s="64,96"        align=center]
c [bgcolor=#ddf s="100%,96"      align=center]
d [bgcolor=#dff s="32,86%"       align=center sh=2]
e [bgcolor=#ffd w="100%" h="32"  align="centery" sw=3]

label_class=lb

a->b "a->b"
a->c "a->c"

b->d "b->d"
c->d "c->d"

a.>e "a.>e" [bend=20%]
c=>e "c=>e" [bend=20%]
d>>e "d>>e" [bend=20%]
