// table layout test (alternative long-id row syntax,
//  nested sub-graph in table cell, nested table in sub-graph)

style default {
  bgcolor = #eeeeee
  fgcolor = #000000
}

style tbl_hdr {
  bgcolor      = #eee
  fgcolor      = #777
  border_style = solid
  border_width = "1"
  border_color = #666
  border_dir   = bottom
  align        = expandx
}

style tbl_def {
  default
}

style tbl_inv {
  bgcolor = #000000
  fgcolor = #ffffff
}

style tbl_small {
  bgcolor = #eeeeee
  fgcolor = #555555
  font    = small
}

style tbl_big {
  bgcolor = #eeffff
  fgcolor = #557777
  font    = big7
}

style tbl_k {
  default
  font     = small
  text_pos = right
}

style def {
   bgcolor = #ddd;
   fgcolor = #007;
}

style sub {
   bgcolor = #e4e4c8;
   fgcolor = #022;
}

style subtable_b {
   bgcolor      = #fff8e0;
}

style subtable_3 {
   bgcolor      = #f4e4c8;
   fgcolor      = #022;
   text_pos     = left;
   shape        = rect;
   border_width = 0;
}

palette arrow {
   red = #d51
}

grid = 24,8

a[align=top]->b [arrow_fgcolor=arrow.red bend=30%]

// (note) table sub graphs look like a single cell to other graphs
// (note) layouting merely affects the _inner_ node placement of the sub graph cell
graph T {
   layout       = table;
   border_width = 1;
   ipad         = 1.0
   
   // table layout:
   style=tbl_hdr;   row="nodeA|     |nodeB|     |nodeC";
   style=tbl_def;   row="nodeD|nodeE|nodeF|nodeG|nodeH";
   style=tbl_big;   row="nodeI|     |nodeJ|     |     ";
   style=tbl_def;   row="nodeK|     |     |     |     ";

   // table cell details:
   nodeA "Header Cell A" [bgcolor=#eef2ee];
   nodeB "Header Cell B" [bgcolor=#def2f2];
   nodeC "Header Cell C" [bgcolor=#f2f2de];

   nodeD "Small Cell D" [bgcolor=#e0f0e0 align=baseline];
   nodeE "Small Cell E" [bgcolor=#d0f0f0 align=baseline];
   nodeF "Cell F"       [class=tbl_inv align="left;top" pad=0];
   nodeG "Small Cell G" [class=tbl_def] {
      cell_slant  = true;
      zero_margin = false; // allow padding at the sides
      ipad        = "2;0;2;0"
      bgtint      = #04000000

      a "Node A" [class=tbl_small align=bottom];

      graph b {
         unfold       = false
         rotate       = true;
         shape        = round;
         border_style = solid;
         border_width = 1;
         border_color = #f00;
         pad          = "4;4;4;4"
         ipad         = "3;6;3;6"

         style=sub;
         1 "Sub 1" [shape_round_amount=42% border_width=1 border_color=#eeeed8];
         2 "Sub 2" [shape_round_amount=42% border_width=1 border_color=#eeeed8];
         3 [class=subtable_3];
         3 "Sub 3" {
           layout             = table;
           ipad               = "2;4;2;4";
           shape              = round;
           shape_round_amount = 20%;
           shape_round_limit  = 7;
           border_style       = solid;
           border_width       = 1;
           border_color       = #000;

           style=subtable_3; row="a b c";
           style=subtable_3; row="defgh";
           style=subtable_3; row="i j  ";
           style=subtable_3; row="k    ";

           f "f..";
         } ;
         3 [class=subtable_3]; // merge bgcolor
         1->2;
         1->3;
      }

      b [class=subtable_b pad_l=4]  // merge bgcolor

      style=tbl_small;
      c "Node C" [pad_l=16 align=bottom];

      a->b [arrow_fgcolor=arrow.red arrow_snap=75%];
      b->c [arrow_fgcolor=arrow.red arrow_snap=75%];
   }
   nodeH "Small Cell H" [bgcolor=#d0d0c0 align=bottom];

   style=tbl_big;
   nodeI "Big Cell I" [bgcolor=#d0d0d0];
   nodeJ "Big Cell J" [bgcolor=#c0d8d8];

   nodeK [class=tbl_k];
}

b->T [arrow_fgcolor=arrow.red  arrow_snap=65%];
