// sub-graph test
//  - flip-cell optimization
//  - reverse edge

style def {
  bgcolor = #e0e0e0
  fgcolor = #022
  shape = round
  border_width = 1
  border_color = #aaa
}

style sub {
  bgcolor = #e4e4c8
  fgcolor = #022
  shape = round
  border_width = 1
  border_color = #888
}

graph {
  grid = 48,6
  ipad = 4
  flip_x_opt = 1

  a;b;c

  graph d {
    unfold = true
    rotate = false

    style=sub
    1 "one"
    1<-2  // reverse edge
    3->1
    4->3
    5->4
  }

  style=def

  a->b
  b->c

  d->b
}
