// sub-graph test
//  - flip-cell optimization
//  - reverse edge
//  - x-flip sub graph
//  - (implicit) sub-graph anchor='1' (top-left node)

style {
  bgcolor       = #ee9
  fgcolor       = #000
  arrow_fgcolor = #f23
  edge_shape    = line
  border_style  = solid
  border_width  = 1
  border_color  = #777
  align         = expand
}

graph {
  grid       = 48,6
  flip_x_opt = true
  slant      = true

  a;b;c

  graph d {
    unfold = true
    flip_x = true

    1<-2  // reverse edge
    3->1
    4->3
    5->4

    3 "three"
  }

  a "ay"
  b "bee"
  c "node c"  // already declared, just assign new label

  a->b
  b->c

  d->b
}
