
style def {
  shape = round;
  border_width = 1.0;
  shape_round_amount = 20%;
  shape_round_aspect = "2";
  shape_round_limit  = 8;
  ipad  = 2;
  pad   = 2;
}

style def_node {
  def
  bgcolor = #46a;
  fgcolor = #fff;
}

style subgraph_io {
  port_s            = "12;8"
  port_bgcolor      = #575
  port_fgcolor      = #ffa
  port_border_color = #ff555555
  port_border_width = 0.5
  port_font         = big11
}

style subgraph {
  subgraph_io
  grid    = 2
     //layout  = fixed;
  layout  = none
  unfold  = false;
  ipad    = 4;
  pad     = 0;
}

graph GA {
  class=subgraph;
  bgcolor=#f42;

  node_style=def_node;
  a [label="GA.a"]
  b [label="GA.b"]

  ports {
    margin = "50%;50%;50%;50%"
    i1:t
    i2:t
    o1:b
    o2:b
  }

} 

graph GB {
  class=subgraph;
  bgcolor=#f70

  node_style=def_node;
  a [label="GB.a"]

  ports {
    margin = "50%;50%;50%;50%"
    i1:t
    i2:t
    o1:b
    o2:b
  }

} 

graph GC {
  class=subgraph;
  bgcolor=#b9d

  node_style=def_node;
  a [label="GC.a"]

  ports {
    margin = "50%;50%;50%;50%"
    i:t
    o:b
  }

} 

grid         = 0
layout       = none
pixel_layout = fixed
flatten      = true
ipad         = 0 //2,4,2,4
s            = 512,384
  shape = none;
  border_width = 4;

style=def

GA [class=subgraph p="50;110" s="100;30" ];

GB [class=subgraph p="140;20" s="100;30" ];

GC [class=subgraph p="220;100" s="100;30" ];

B [class=def_node caption="B test" p="20;20"];

GA:i1 -> B
