// edge styles (normal ->, dotted .>, dashed =>, bold >>, invisible ~>
//  - '+' adds line break after 'f' during initial layout

style node {
  bgcolor = #445
  fgcolor = #fff
  shape = round
  border_width = 1
  border_color = #555
  ipad = "2;6;2;6"
}

style edge {
  bgcolor          = #000
  fgcolor          = #aaa
  arrow_len        = 10
  arrow_fgcolor    = #a56
  edge_width_start = 3
  edge_width_end   = 1
}

grid         = 64,16
cell_spacing = 4

node_style = node;
edge_style = edge;

a b c d e f g h +;
1 2 3 4 5 6      ;

a->b;
b.>c;
c=>d;
d>>e;
e~>f;
f--g;
g<>h;

6<-5;
5<.4;
4<=3;
3<<2;
2<~1;

1->f
