// sub-graph test
//  - reverse edge
//  - x-flip sub graph
//  - sub-graph anchor='2'

style def {
  bgcolor = #ddd
  fgcolor = #000
  shape = round
  border_width = 1
  border_color = #999
}

style sub {
  def
  bgcolor = #ddeae0
}

graph {
  grid = 48,8
  // ipad = "2;4;2;4"

  a "Node A";b "Node B";c "nOdE C"

  graph d {
    unfold=true
    //flip_x=true
    anchor=2

    style=sub
    1 "Sub 1"
    2 "Sub 2"
    3 "Sub Three"
    4 "Sub 4"
    5 "Sub 5"

    1<-2  // reverse edge
    3->1
    4->3
    5->4
  }

  c "Node C"  // already declared, just assign new label

  a->b
  b->c

  d->b
}
