// solid, dotted, dashed and stacked tri shapes

style {
  bgcolor           = #ddd
  shape             = tri
  blend             = srcover
  border_width      = 2
  border_color      = #666
  shape_tri_ax      = 0
  shape_tri_ay      = 0
  ipad              = 20,20,8,20
  stack_off         = 3,4.5
  stack_alpha_dcy   = 0.7
  sgx               = mytri
  align             = left,top
  font              = small
}

graph {
  layout = fixed
  shape = rect
  ipad   = 8,16,8,16
  zero_margin = 1

  row="abc"
  row="def"
  
  a [border_style=solid]
  b [border_style=dotted]
  c [border_style=dashed]
  a->b->c

  d [border_style=solid  stack=3 stack_alpha_exp=0.9]
  e [border_style=dotted stack=3 stack_alpha_exp=1.7]
  f [border_style=dashed stack=3 stack_alpha_exp=2.3]
  d->e->f
}
