// - ipl subtree from Cycle patch
// - test node labels

style def {
  bgcolor=#eee7e0
  fgcolor=#111
}

graph {
  grid  = 96,8
  slant = 1

  b "input b" [bgcolor=#eef]
  1b "1b.tri2mul"
  2b "2b.tri1" [bgcolor=#efe]
  3b "3b.tri1mul"
  4b "4b.tri2" [bgcolor=#efe]
  5b "5b.tri2.freq"
  6b "6b.tri2.freq.c"
  8b "8b.trix.freq"   // debug
  9b "9b.trix.freq.c" // debug

  t "input t" [bgcolor=#eef]
  7tmod "7t.mod"

  2b->3b
  3b->4b
  4b->1b
  1b->b
  5b->4b[edge_bend=35%]
  6b->5b

  7tmod->t
}
