// "pixel_layout=grid" row span test.

style {
   //shape        = rect
  align        = expand
  arrow_len    = 8
  arrow_ilen   = 0.3
  border_width = 1
}

grid         = 16,16
layout       = fixed;
pixel_layout = grid;
zero_margin  = false;
row_padding  = 32
col_padding  = 32

row="ab";
row=" c";

a [bgcolor=#fdd s="128,128" align=center sh=2]
b [bgcolor=#dfd s="64,96"]
c [bgcolor=#ddf s="64,96"]

a->b
a->c
