// solid, dotted, dashed and stacked hexagon shapes

style {
  bgcolor           = #ddd
  shape             = hexagon
  blend             = srcover
  border_width      = 2
  border_color      = #666
  shape_hexagon_ax  = 2
  shape_hexagon_ay  = 4
  ipad              = 2
  stack_off         = 3.5,3.5
  stack_alpha_dcy   = 0.7
  s                 = 35,50
  align             = left,top
  font              = small
}

graph {
  layout = fixed
  shape = rect
  ipad   = 8,16,8,16
  zero_margin = 1

  row="abc"
  row="def"
  
  a [border_style=solid]
  b [border_style=dotted]
  c [border_style=dashed]
  a->b->c

  d [border_style=solid  stack=5 stack_alpha_exp=0.9]
  e [border_style=dotted stack=5 stack_alpha_exp=1.7]
  f [border_style=dashed stack=5 stack_alpha_exp=2.3]
  d->e->f
}
