// table layout test (alternative long-id row syntax, nested sub-graph in table cell)

style default {
  fgcolor = #000000
  bgcolor = #eeeeee
}

style tbl_def {
  default
}

style tbl_hdr {
   //fgcolor = #ffffcc
   //bgcolor = #000000
  border_style = solid
  border_width = 3
  border_color = #666
  border_dir   = bottom
}

style tbl_inv {
  fgcolor = #ffffff
  bgcolor = #000000
}

style tbl_small {
  fgcolor = #555555
  bgcolor = #eeeeee
}

style tbl_big {
  fgcolor = #557777
  bgcolor = #eeffff
}

style def {
   bgcolor = #ddd;
   fgcolor = #007;
}
     
style sub {
   bgcolor = #e4e4c8;
   fgcolor = #022;
   shape = round
      //ipad = "2;6;2;6"
}

grid = 24,8

a->b

// (note) table sub graphs look like a single cell to other graphs
// (note) layouting merely affects the _inner_ node placement of the sub graph cell
graph T {
   layout=table;  // enable table mode

   // table layout:
   style=tbl_hdr; row="nodeA|     |nodeB|     |nodeC";
   style=tbl_def; row="nodeD|nodeE|nodeF|nodeG|nodeH";
   style=tbl_def; row="nodeI|     |nodeJ|     |     ";
   style=tbl_def; row="nodeK|     |     |     |     ";

   // table cell details:
   
   nodeA "Header Cell A" [bgcolor=#eef2ee];
   nodeB "Header Cell B" [bgcolor=#def2f2];
   nodeC "Header Cell C" [bgcolor=#f2f2de];

   style=tbl_small;
   nodeD "Small Cell D" [bgcolor=#e0f0e0];
   nodeE "Small Cell E" [bgcolor=#d0f0f0];
   nodeF "Cell F"       [class=tbl_inv];
   nodeG "Small Cell G" [bgcolor=#f6f4f0] {
      cell_slant = 1;
     
      a "Node A";
     
      graph b {
         rotate = true;

         style=sub;
         1 "Sub 1";
         2 "Sub 2";
         3 "Sub 3";
         1->2;
         1->3;
       }
     
      style=def;
      c "Node C";
     
      a->b;
      b->c;
   }
   nodeH "Small Cell H" [bgcolor=#e0e0d0];

   style=tbl_big;
   nodeI "Big Cell I" [bgcolor=#d0d0d0];
   nodeJ "Big Cell J" [bgcolor=#c0d8d8];
}

b->T
