// port margins

include diagram.gi

col_padding=20
row_padding=20

style def {  // (note) update style 'def' (initially declared in 'diagram.gi')
  bgcolor = #eef8fa
  edge_width         = 3.5
  edge_width_start   = 0.25
  edge_width_end     = 3
  edge_width_left    = 2.0
  edge_width_right   = 2.0
  edge_fgtint_left   = #6ffcfcfc
  edge_fgtint_right  = #6ffcfcfc
}

style=def;
row="abc"
row="def"
row="geh"
row="ijk"

e [s=128] ports {
  margin = 25%,80%,75%,40%
  t1:t t2:t t3:t
  l1:l l2:l
  b1:b b2:b b3:b
  r1:r r2:r
}

a->e:t1 b->e:t2 c->e:t3
d->e:l1 g->e:l2
f->e:r1 h->e:r2
i->e:b1 j->e:b2 k->e:b3
