
style {
//  bgcolor = #1ee
//  bgfill = 0
}

style def {
   pad                = 4,6,4,6
   bgcolor            = #0af
   bgfill             = 0
   border_shape       = round
   shape_round_amount = 30%
   shape_round_aspect = "2"
   shape_round_limit  = 8
   border_style       = solid
   border_width       = 0.75
   font               = big8
   fgcolor            = #444
   arrow_angle        = 25
   arrow_len          = 12
   arrow_ilen         = 20%
   ipad               = 1,4,1,4
}

style sub {
  def
  bgcolor            = #0FF
  bgfill             = 1
  ipad               = 1
//  row_padding  = 2
//  col_padding  = 2
  pad = 1
}

style sub_widget {
  sub
  border_shape = none
  ipad = 1
  align=top,expandx
  bgcolor=#fff
  bgfill=0
  shape = rect
}

style conn {
  def
  align=top,centerx
  bgcolor=#faa
  bgfill=1
  shape=rect
  border_shape=rect
}

style CheckBox {
  fillBG      = 0
  iconSuffix  = _dark
  //bgcolor     = #f9f9f9
  //bgcolor = #f00
}

style edge {
 edge_width_start=0.5
 edge_width_end=2
}

grid        = 8
//flatten     = false
layout      = fixed
zero_margin = true
//col_padding = 8
//row_padding = 8.75
//pad         = 8
//ipad        = 4,4,4,4
  ipad   = 8,16,8,16


graph A {
   //class        = sub
  layout       = fixed
  zero_margin  = true
  unfold       = false
  border_width = 1
  border_shape = round
  shape        = round
//  bgcolor      = #ff0
//  bgfill       = 1
  //bgcolor      = #0f0
  //bgfill       = 1
  pad          = 0
  ipad         = 7
  align        = left,top

  style=sub
  row="a"
  row="b"
  row="c"
  
  style=sub_widget
  a       (CheckBox caption="Option A" selected=1)
  b       (FloatParam cols=5 min=-10 max=10 step=1 mousePrecision=1 value=5)
  c       (ComboBox options="Sin;Tri;Saw;Pul"
                    bgtint=#18307fbf textPlacement=LEFT)
}

A ports {
  margin = 25%,80%,50%,40%
  f:t ph:t
  out:b
  out2:b
}


style=def
//pad    = 16,16,16,16
//col_padding = 64
//row_padding = 8.75

//row="i "
row="A "
//row="o "
row="BC"

A [ align=left,top ]
B [ s="160;100" pad_t=50 pad_r=60 ]

//i [ class=conn ]
//o [ class=conn ]

//B { pad_t=20 }
   
edge_style=edge
A:out->B
//B<-o
A:out2->C
B->C

