// style class test

style base {
  fgcolor=#000000;
  bgcolor=#eeeeee;
}

style red {
  base // inherit from style class 'base'
  fgcolor = #7f0000;
}

style green {
  base // inherit from style class 'base'
  fgcolor = #007f00;
}

graph {
  grid = 24,8

  a "Node A"  // uses first declared style class ('base')

  style=red   // select style class for following nodes
  b "Node B"

  style=green
  c "Node C"

  a->b->c
}
