// hw_toplevel

include diagram.gi

zero_margin = false

// row_padding=0
col_padding=0
ipad=12
//flatten=0

graph m {
  layout       = fixed
  zero_margin  = false
  unfold       = false
  border_width = 0
  row_padding  = 8
  col_padding  = 32
  pad          = 0
  ipad         = 0
  bgfill       = false
  align        = left
  border_shape = none
  bgcolor      = #f9f9f9

  style=def
  row="a b c";
  row="a b d";

  a "SBI"         [align=left,expandy s=48,144 pad_h=0 pad_l=15]
  b "Register"    [align=centerx,expandy]
  c "Control"     [align=expandx,top]
  d "Scratch DMA" [align=expandx,bottom]

  a<>b
  c<>b
  d<>b
}

graph l {
  layout       = fixed
  zero_margin  = true
  unfold       = false
  row_padding  = 0
  col_padding  = 0
  border_width = 0
  pad          = 0
  ipad         = 0
  //bgcolor=#f00
  border_shape = none
  bgcolor      = #f9f9f9

  row="STUV"

  S "Shader Core 0" [sgx=shcore font=small]
  T "Shader Core 1" [sgx=shcore font=small]
  U "Shader Core 2" [sgx=shcore font=small]
  V "..."           [sgx=shcore font=small]
}

style=def // can skip
row="mmmmm pppp  ";
row="mmmmm oooo  ";
row="mmmmm nnnn  ";
row="a0 b  cccc  ";
row="a     dddd  ";
row="a     eeee g";
row="a1 h  ffff  ";
row="a i   ffff  ";
row="a  j  ffff  ";
row="a k   4444  ";
row="a     5678  ";
row="a2   3llllA9";
row="aB          "

style=invis
0 [pad_h=0 w=0 align=left,centery]
1 [pad_h=0 w=0 align=left,centery]
2 [pad_h=0 w=0 align=left,centery]
3 [pad_h=0 w=0]
4 [pad=0 s=4     align=center shape=round bgcolor=#000 helper=true]
5 [pad=0 s=16,0  align=centerx,bottom]
6 [pad=0 s=16,0  align=centerx,bottom]
7 [pad=0 s=16,0  align=centerx,bottom]
8 [pad=0 s=16,0  align=centerx,bottom]
9 [pad=0 s=16,16 align=center helper=true]
A [pad=0 s=0,16  align=left,centery]
B [pad=0 s=16,16 helper=true]


style=def
a "MBI"                  [align=right,expandy w=48 pad=0]
b "ZSCache"              [align=right,centery]
c "ZSUnit"               [sgx=zs]
d "Multisample Assembly" [sgx=zs]
e "Address Encoder"      [sgx=zs]
f "Dispatcher"           [h=75% pad_h=0 align=center ipad_l=6 ipad_r=6 bg_pattern=zigzag_4 bg_pattern_intensity=8%] //shape=rhomb
g "Fast Clear"           [pad_h=0]
h "Vertex Assembly"      []
i "Index Cache"          []
j "Primitive Assembly"   []
k "Scratch\nRAM"         [pad_b=16]
l                        [pad=0 border_width=0 align=top]
m                        [align=left,centery pad_r=60]
n "ZSFIFO"               [pad_b=24]
o "ZSScheduler"          [pad_b=24]
p "Rasterizer"           [pad_b=24]

p->o "Stamp" [pad_r=20]
o->n "Stamp" [pad_r=20]
n->c "Stamp" [pad_r=20]

o->b "Prefetch" [xmajor_head=false edge_shape=rcurve pad_b=62.5]

0<>b
b<>c

c->d->e->f "Stamp"
e->g "Tile" [pad_t=15]

f->4 "Coordinate Data\nContext Data\nMemory Write" [arrow_shape=none pad_l=50]
4->5 [xmajor_tail=true edge_shape=rcurve]
4->6 [xmajor_tail=true edge_shape=rcurve]
4->7 [xmajor_tail=true edge_shape=rcurve]
4->8 [xmajor_tail=true xmajor_head=false edge_shape=rcurve]

g->9 "Tile" [pad_r=18 xmajor_head=true arrow_shape=none]
9->A

1<>h
h->f "Vertex Stamp"
i<>h [xmajor_tail=false xmajor_head=true]
i->j [xmajor_tail=false]
j->f "Primitive Stamp"
k<>3

2<>3 "Attribute Fetch\nTexture Fetch\nFB read/write"
