style base {
  bgcolor      = #eee
  fgcolor      = #000
  shape        = round
  border_width = 1.5
  ipad         = 2,5,2,5
}

style red {
  base  // inherit attributes from style 'base'
  tint = #40f00000
}

style green {
  base  // inherit attributes from style 'base'
  tint = #4000f000
}

style cyan {
  base  // inherit attributes from style 'base'
  tint = #2000f0f0
}

grid=12,12

a [class=red]
b [class=green]
a -> b [class=cyan]
