// table layout test (alternative long-id row syntax, nested sub-graph in table cell, nested table in sub-graph)

style default {
  fgcolor = #000000
  bgcolor = #eeeeee
  shape = round
  border_width = 1
  border_color = #555
  ipad = "2;6;2;6"
}

style tbl_hdr {
  fgcolor = #ffffcc
  bgcolor = #000000
}

style tbl_inv {
  fgcolor = #ffffff
  bgcolor = #000000
}

style tbl_small {
  fgcolor = #555555
  bgcolor = #eeeeee
}

style tbl_big {
  fgcolor = #557777
  bgcolor = #eeffff
}

style def {
   bgcolor=#ddd;
   fgcolor=#007;
}
     
style sub {
   default
   bgcolor=#e4e4c8;
   fgcolor=#022;
}

style subtable {
   bgcolor=#f4e4c8;
   fgcolor=#022;
}
    
graph {
   grid = 24,4
   //rotate = true;

   style=sub;
   1 "Sub 1";
   2 "Sub 2";
   3 "Sub 3" /*{
     layout=table;

     style=subtable;
     row="a b c";
     row="defgh";
     row="i j  ";
     row="k    ";
   } */;
   1->2;
   1->3;
}
     
