// "tint" and border_blend attribute test

style def {
  bgcolor = #eee
  fgcolor = #444
}

style def_node {
  def
  border_width  = 2

  // border_blend  = srcover
  // border_blend  = dstcolor
  // border_blend  = additive
  border_blend  = srccolor
     border_alpha  = 74
     //border_alpha  = 255
  ipad          = "3;4;3;4"
}

style def_edge {
  def
  arrow_fgcolor = #666
}

style subgraph {
  def_node
  bgcolor           = #ccc
  shape             = round
  shape_round_limit = 10
  border_width      = 2
  border_color      = #777
  col_padding       = 14
  row_padding       = 0
}

style graph_a {
  subgraph
  tint = #18ff0000
}

style graph_b {
  subgraph
  tint = #1800ff00
}

style graph_c {
  subgraph
  tint = #180000ff
}

style sub {
  def_node
  // pad="8;40;8;0"
  pad  = 8
  ipad = "4;8;4;8"
}

style sub_b {
  sub
}

style sub_a {
  sub
}

style sub_c {
  sub
}

style edge_big {
  edge_shape         = none
  arrow_len          = 16
  arrow_fgcolor      = #f0f0ee
  arrow_border_color = #888
  arrow_border_width = 1.0
}

style lb {
  def
  bgcolor       = #f0f0e7
  border_width  = 0.5
  border_color  = #888
  label_fgcolor = #888
  shape         = rect
  font          = tiny
  ipad          = 1
  tint          = 0
}

style lb_big {
  lb
  font = big9
  ipad = "0;6;0;6"
}


// --------- main graph -----------
graph {
   grid    = 32,12
   bgcolor = #eee

   // inherited by edges
   label_class=lb

   a [class=graph_a]
   a {
     unfold = false
     pad = 0
     //ipad = 16 // xxx

     style=sub_a
     1->2
     1->3
     3->2
   }

   b [class=graph_b]
   b {
     layout = fixed
     unfold = false
     pad = "0;60;0;0"
     ipad = "4;5;4;5"

     row="1 2"
     row=" 3"

     style=sub_b
     1->2 "label test" [fgtint=#d0000000]
     1->3 [xmajor_tail=0]
     3->2 [xmajor_head=0]
   }

   c [class=graph_c]
   c {
     unfold = false
     flip_x = true
     pad    = "0;60;0;0"

     style=sub_c
     1->2
     1->3
     3->2
   }

   edge_style  = edge_big
   label_class = lb_big
   a -> b"a->b" <- c"b<-c"

}
