// tinted, dashed and stacked ellipse shapes

style {
  bgcolor          = #d9d9d9
  fgcolor          = #fff
  shape            = ellipse
  blend            = srcover
  border_width     = 2
  border_style     = dashed
  border_color     = #666
  shape_ellipse_rx = 40
  shape_ellipse_ry = 0
  ipad_v           = 8
  stack            = 3
  stack_off        = 0.5,4
  stack_alpha_dcy  = 0.7
  stack_alpha_exp  = 2.3
  align            = left,top
}

graph {
  layout = fixed
  ipad   = 8,16,8,16
  bgcolor = #f9f9f9

  row="abc"
  row="def"

  a [bgtint=#90ff0000 border_tint=#40ff0000]
  b [bgtint=#90ffff60 border_tint=#40ffff60]
  c [bgtint=#908080ff border_tint=#408080ff]

  d [bgtint=#90ff7f00 border_tint=#40ff7f00]
  e [bgtint=#907fff60 border_tint=#407fff60]
  f [bgtint=#90c080ff border_tint=#40c080ff]

}
