// simplified debug version of test23d.gr

style def {
   bgcolor=#ddd;
   fgcolor=#007;
}

style sub {
   bgcolor=#e4e4c8;
   fgcolor=#022;
}

style subtable {
   bgcolor=#f4e4c8;
}

style subtable_node {
   subtable
   fgcolor=#022;
   text_pos="left";
}

grid = 24,4
//cell_slant = 1;

a "Node A";

graph b {
   unfold = false;
   //rotate = true;
   bgcolor=#fffff8e0;

   style=sub;

   1 "Sub 1";
   2 "Sub 2";
   3 "Sub 3" {
     layout=table;
     class=subtable;

     style=subtable_node;
     row="a b c";
     row="defgh";
     row="i j  ";
     row="k    ";
   } ;
   1->2;
   1->3;
 }

class=def;
c "Node C";

a->b;
b->c;
