// solid, dotted, dashed and stacked diamond shapes

style {
  bgcolor          = #eee
  shape            = diamond
  blend            = srcover
  border_width     = 2
  border_color     = #666
  shape_diamond_rx = 16
  shape_diamond_ry = 16
  ipad             = 16
  stack_off        = 0.5,5
  stack_alpha_dcy  = 0.7
}

graph {
  layout = fixed
  ipad   = 8,16,8,16

  row="abc"
  row="def"
  
  a [border_style=solid]
  b [border_style=dotted]
  c [border_style=dashed]
  a->b->c

  d [border_style=solid  stack=3 stack_alpha_exp=0.9]
  e [border_style=dotted stack=3 stack_alpha_exp=1.7]
  f [border_style=dashed stack=3 stack_alpha_exp=2.3]
  d->e->f
}
