
// debug test46b.gr

style {
////  bgcolor = #1ee
////  bgfill = 0
}

style defx {
  pad                = 4,6,4,6
  bgcolor            = #f00
  bgfill             = 0
  border_shape       = round
  shape_round_amount = 30%
  shape_round_aspect = "2"
  shape_round_limit  = 8
  border_style       = solid
  border_width       = 0.75
  font               = big8
  fgcolor            = #444
  arrow_angle        = 25
  arrow_len          = 12
  arrow_ilen         = 20%
  ipad               = 1,4,1,4
}

style sub2 {
  defx
  bgcolor            = #FF9
  bgfill             = 1
  ipad               = 1
  pad = 1
  bg_pattern=checker_1
  port_s = 12
  //port_s = "12;12"
  //port_w = 12
  //port_h = 12
}

style sub2_graph {
  sub2
}

style sub2_widget {
  sub2
  border_shape = none
  ipad = 1
  align=top,expandx
  bgcolor=#fff
  bgfill=0
  shape = rect
}

style conn {
  defx
  align=top,centerx
  bgcolor=#faa
  bgfill=1
  shape=rect
  border_shape=rect
}

graph B {
  grid         = 0
  class        = sub2_graph
  layout       = fixed
  //zero_margin  = true
  unfold       = false
  //s = "160;120"
  border_width = 0.75
  border_shape = round
  shape        = round
  pad          = 0
  ipad         = 4

  style=sub2_widget
  row="b"
  
  b  (BezierEdit align=expand reqSizeScaled="96;54" dragRotate=0 scaleTblOffY=7)
} 


grid         = 0
layout       = none
pixel_layout = fixed
flatten      = true
ipad         = 8,16,8,16
s            = "512;384"

style=defx
row="B"

B [ class=sub2 p="80;120" ]

  
