// DEBUG table layout test (alternative long-id row syntax, nested sub-graph in table cell)

style default {
  fgcolor = #000000
  bgcolor = #eeeeee
}

style tbl_def {
  default
}

style tbl_hdr {
   //fgcolor = #ffffcc
   //bgcolor = #000000
  border_style = solid
  border_width = 3
  border_color = #666
  border_dir   = bottom
}

style tbl_inv {
  fgcolor = #ffffff
  bgcolor = #000000
}

style tbl_small {
  fgcolor = #555555
  bgcolor = #eeeeee
}

style tbl_big {
  fgcolor = #557777
  bgcolor = #eeffff
}

style def {
   bgcolor = #ddd;
   fgcolor = #007;
}
     
style sub {
   bgcolor = #e4e4c8;
   fgcolor = #022;
   shape = round
      //ipad = "2;6;2;6"
}

b

// (note) table sub graphs look like a single cell to other graphs
// (note) layouting merely affects the _inner_ node placement of the sub graph cell
graph T {
   layout=table;  // enable table mode
   bgcolor = #f00

   // table layout:
   style=tbl_def; row="nodeF|";

   // table cell details:
   
   style=tbl_small;
   nodeF "Cell F" [class=tbl_inv pad=20];

}

b->T
