// style class test
//  - node and edge default styles
//  - per-node attribs and styles
//  - per-edge styles

style base {
  fgcolor=#000000;
  bgcolor=#eeeeee;
}

style red {
  base // inherit from style class 'base'
  fgcolor = #700;
}

style green {
  base // inherit from style class 'base'
  fgcolor = #070;
}

style cyan {
  base // inherit from style class 'base'
  fgcolor = #077;
}

style edge_base {
  fgcolor=#000000;
}

style edge_blue {
  edge_base;
  fgcolor=#0000c0;
}

style edge_cyan {
  edge_base;
  fgcolor=#00a0a0;
}

graph {
  grid = 32,1

  style=base
  a "Node A"                // uses first declared style class ('base')
  style=red                 // select style class for following nodes and edges (no effect)
  b "Node B" [class=green]  // assign style 'green' to 'b' but don't change default style
  style=cyan                // select style class for following nodes and edges (affects node 'd')
  c "Node C" [class=red]    // assign style 'red' to 'c' but don't change default style
  d "Node D"                // uses style class 'cyan'
  edge_style=edge_base      // select style class for following edges (affects 'b->c')

  a->b[class=edge_blue]->c->d[class=edge_cyan]  // assign style 'edge_blue' to edge a->b and style 'edge_cyan' to edge c->d. b->c uses style 'edge_base'
}
