// - ipl subtree from Cycle patch
// - test node labels, initial node spacing and flip cell optimization

style def {
  bgcolor=#eeeef4
  fgcolor=#111
}

graph {
  grid         = 96,8
  cell_spacing = 4
  flip_x_opt   = true
  slant        = true

  b "input b" [bgcolor=#bbe]
  1b "1b.tri2mul"
  2b "2b.tri1" [bgcolor=#beb]
  3b "3b.tri1mul"
  4b "4b.tri2" [bgcolor=#beb]
  5b "5b.tri2.freq"
  6b "6b.tri2.freq.c"
  8b "8b.trix.freq"   // debug
  9b "9b.trix.freq.c" // debug

  t "input t" [bgcolor=#bbe]
  7tmod "7t.mod"

  2b->3b
  3b->4b
  4b->1b
  1b->b
  5b->4b
  6b->5b
  8b->1b
  9b->8b

  7tmod->t
}
