// sub-graph test

style def {
  bgcolor=#ddd
  fgcolor=#007

  shape = round
  border_width = 1
  border_color = #555
  ipad = "2;6;2;6"

  align=baseline
}

style sub {
  def
  bgcolor=#e4e4c8
  fgcolor=#022
}

graph {
  grid = 24,8
  ipad = "4;4;4;4"
  cell_slant = 1

  a "Node A"

  graph b {
    unfold=true
    rotate=true

    style=sub
    1 "Sub 1"
    2 "Sub 2"
    3 "Sub 3"
    1->2
    1->3
  }

  style=def
  c "Node C"

  a->b
  b->c
}
