// hw_toplevel debug 2

include diagram.gi

grid        = 16,16
row_padding = 0
col_padding = 8
ipad        = 12
//flatten=0

style=def;

graph l {
  layout       = fixed
  zero_margin  = true
  unfold       = false
  row_padding  = 0
  col_padding  = 0
  border_width = 0
  pad          = 0
  bgcolor      = #f00

  row="STUV"

  S "Shader Core 0" [font=small]  // sgx=shcore
  T "Shader Core 1" [font=small]
  U "Shader Core 2" [font=small]
  V "..."           [font=small]
}

row="eeeeg";
row="ffffh";
row="ffff ";
row="ffff ";
row="llll ";

style=def
e "Address Encoder" [pad=0 align=center]
f "Dispatcher" [h=75% pad=0 align=right]
g "Fast Clear" [pad=0]
h [pad=0]

l [pad=0]

//e->f "Stamp"
//e->g
