
// (note) tests (experimental) pixel_layout=fixed (absolute positioning)

style {
////  bgcolor = #1ee
////  bgfill = 0
}

style defx {
  pad                = 4,6,4,6
  bgcolor            = #f00
  bgfill             = 0
  border_shape       = round
  shape_round_amount = 30%
  shape_round_aspect = "2"
  shape_round_limit  = 8
  border_style       = solid
  border_width       = 0.75
  font               = big8
  fgcolor            = #444
  arrow_angle        = 25
  arrow_len          = 12
  arrow_ilen         = 20%
  ipad               = 1,4,1,4
}

style sub1 {
  defx
  bgcolor  = #0af
  bgfill   = 1
  ipad     = 1
  pad      = 1
  port_s   = "12;8"
  port_bgcolor = #f80
  port_fgcolor = #310
  port_border_color = #ffff0000
  port_border_width = 1
  port_font         = big11
}

style sub1_graph {
  sub1
//  w = 400
//  h = 300
}

style sub1_widget {
  sub1
  border_shape = none
  ipad         = 1
  align        = top,expandx
  bgcolor      = #fff
  bgfill       = 0
  shape        = rect
}

style sub2 {
  defx
  bgcolor           = #FF9
  bgfill            = 1
  ipad              = 1
  pad               = 1
  bg_pattern        = checker_1
  port_s            = "8;8"
  port_bgcolor      = #f55
  port_fgcolor      = #ffa
  port_border_color = #ff555555
  port_border_width = 0.5
  port_font         = big11
}

style sub2_graph {
  sub2
}

style sub2_widget {
  sub2
  border_shape = none
  ipad         = 1
  align        = top,expandx
  bgcolor      = #fff
  bgfill       = 0
  shape        = rect
}

style conn {
  defx
  align        = top,centerx
  bgcolor      = #faa
  bgfill       = 1
  shape        = rect
  border_shape = rect
}

style CheckBox {
  fillBG      = 0
  iconSuffix  = _dark
}

style edge {
  edge_width_start = 0.5
  edge_width_end   = 2
  //arrow_snap = 90%
}



graph A {
  layout       = fixed
  zero_margin  = true
  unfold       = false
  border_width = 1
  border_shape = round
  shape        = round
  pad          = 0
  ipad         = 7

  style=sub1_widget
  row="a"
  row="b"
  row="c"

 // iconpadtop=10
  a       (CheckBox caption="Option A" selected=1 )
  b       (FloatParam cols=5 min=-10 max=10 step=1 mousePrecision=1 value=5 bgtint=#1000aaff)
  c       (ComboBox options="Sin;Tri;Saw;Pul"
                    bgtint=#1800aaff arrowTextBg=1 textPlacement=LEFT)
}

A ports {
  margin = "60%;80%;50%;40%"
  f:t ph:t
  out:b
  out2:b
}


graph B {
  class        = sub2_graph
  layout       = fixed
  //zero_margin  = true
  unfold       = false
  //s = "160;120"
  border_width = 0.75
  border_shape = round
  shape        = round
  pad          = 0
  ipad         = 4

  style=sub2_widget
  row="b"

  b  (BezierEdit align=expand reqSizeScaled="96;54" dragRotate=0 scaleTblOffY=7)
}

B ports {
  margin = "50%;60%;50%;50%"
  i:t j:t
  o1:b
  out2:l o3:l
}


grid         = 0
layout       = none
pixel_layout = fixed
flatten      = true
ipad         = 0 //2,4,2,4
s            = 512,384

style=defx
row="A "
row="BC"

A [ class=sub1 align=left,top p="40;80"]
B [ class=sub2 p="92;222" ]
C [ class=defx p="30;230" ]

edge_style=edge
A:out2=>B:i
A:out->C
B:out2->C [edge_fgcolor=#f08030]
B:o3->C [edge_fgcolor=#d06a17]
