
style {
  pad_t        = 8
  pad_b        = 8
  text_pos     = baseline
  align        = "expand;baseline"
  edge_bend    = 30%
  border_style = solid
  border_width = 2
  border_color = #555
  shape        = rect
  tail_snap_y  = 0
}

grid        = 24,1
zero_margin = false

A->B->C

A [bgcolor=#eaa font=big8 border_color=#a55]
B [bgcolor=#aea font=big6 border_color=#5a5 ipad_r=3 ]
C [bgcolor=#aae font=big5 border_color=#55a ipad="0;3;0;4"]
