// "pixel_layout=grid" row+col span and layout weights test.
//  invisible connection "port" nodes. edge_shape=rcurve.

style def {
  align                = expand
  arrow_len            = 9
  arrow_angle          = 25
  arrow_ilen           = 15%
  border_width         = 1.25
  border_color         = #666
  shape                = round
  shape_round_amount   = 40%
  shape_round_limit    = 10
  shape_round_aspect   = 5
  pad_l                = 64
  pad_r                = 0
  bg_pattern           = zigzag_4
  bg_pattern_intensity = 0.06
}

style invis {
  def
  shape       = none
  label_style = none
  align       = left,centery
  pad_h       = 0
}

style lb {
  bgcolor      = #ffe
  border_width = 0.5
  border_color = #d4d4d4
  ipad         = "0;1;0;1"
  shape        = rect
  font         = small
  text_pos     = center
  label_style  = default
}

gradient darklight {
  #ffffffff
  0.5  = #80ffffff
  0.6  = #10ffffff
  0.7  = #00000000
  0.75 = #10333333
  0.85 = #08000000
         #40000000
}

gradient darklightr {
  #20000000
  0.5  = #08000000
  0.6  = #10cccccc
  0.75 = #10ffffff
  0.85 = #20ffffff
         #ffffffff
}

gradient darklightr2 {
  #20000000
  0.5  = #08000000
  0.6  = #10cccccc
  0.75 = #10ffffff
  0.85 = #20ffffff
         #5fffffff
}

gradient darklightm {
         #20ffffff
  0.5  = #10ffffff
         #30000000
}

style bcd {
  bg_gradient        = darklightm
  bg_gradient_shape  = r
  shape_round_amount = 40%
  shape_round_limit  = 30
  bg_pattern         = lines_4
  pad_l              = 48
}

style rcurve {
  edge_shape=rcurve arrow_shape=none
}

style e {
  def
  bgcolor              = #dff
  bg_gradient          = darklightr
  bg_gradient_shape    = h
  bg_pattern_intensity = 0.04
  s                    = 32,100%
  align                = centery,right
  headpoint_amount     = 22%
  rotate               = cw
}

grid         = 16,16
bgcolor      = #fafcf9;
layout       = fixed;
xmajor       = true;
zero_margin  = true;
row_padding  = 16;
col_padding  = 8;

style=def;
row="h   e";
row="a   e";
row="a1 be";
row="a24ce";
row="a3 de";
row="a   e";
row="g   e";
row="fffff";

a "Rotated Node A" [rotate=ccw bgcolor=#fdd w=48 h=95% ipad_h=10
                    align=center
                    bg_gradient=darklightr2 bg_gradient_shape=h bg_pattern_intensity=0.04
                    ]
b [bgcolor=#fed s=48,32      align=center pad_b=0 class=bcd]
c [bgcolor=#dff s=48,32      align=center pad_v=6 class=bcd]
d [bgcolor=#ddf s=48,32      align=center pad_t=0 class=bcd]
e "Rotated Node E" [class=e]
f [bgcolor=#ffd w=100% h=32  align=centery pad=24,0,0,0
   bg_pattern=lines_4 bg_gradient=darklight bg_gradient_shape=v
   ]

style=invis
1 [s=0,16 align=bottom pad_v=4 ]
2 [s=0,16              pad_v=4 ]
3 [s=0,16 align=top    pad_v=4 ]
4 [s=4.5               pad_v=4 pad_l=48 shape=round bgcolor=#000 helper=true]
g [s=32,8]
h [s=32,8]

label_class=lb

1--4 "a->b" [class=rcurve pad_b=16 pad_r=0]
2--4 "a->c" [class=rcurve pad_r=0]
3--4 "a->d" [class=rcurve pad_t=16 pad_r=0]

4->b [bend=10% arrow_snap=90% xmajor_tail=false ]
4->c [bend=10%]
4:n->d [bend=10% arrow_snap=90%]

b->e "b->e" [bend=10%]
c->e "c->e" [bend=10%]
d->e "d->e" [bend=10%]

a.>f "a.>f" [bend=20%]

d=>f "d=>f" [bend=20%]
e>>f "e>>f" [bend=20% edge_width_start=0.5]
