// sub-graph test

style def {
  bgcolor      = #ddd
  fgcolor      = #111
  shape        = round
  border_width = 2
  border_color = #555
  ipad         = "1;4;1;4"
}

style sub {
  bgcolor      = #e4e4c8
  fgcolor      = #022
  shape        = round
  border_width = 1
  border_color = #999
  ipad         = "0.5;3;0.5;3"
}

graph {
   grid  = 24,8
   slant = 1;
   ipad  = "2;8;2;8";

   a "Node A";
   graph b {
      unfold = 1;
      rotate = 1;

      style=sub;
      1 "Sub 1";
      2 "Sub 2";
      1->2;
   }

   style=def;
   c "Node C";

   a->b;
   b->c;
}
