// sub graph short-form

style {
  bgcolor             = #eee
  fgcolor             = #111
  arrow_fgcolor       = #f45
  border_width        = 1
  border_color        = #aaa
  shape               = round
  ipad                = "2;4;2;4"
  edge_width          = 3.5
  edge_width_left     = 1.75
  edge_width_right    = 1.75
  edge_width_adaptive = false
  edge_fgtint_left    = #ffdcdcdc
  edge_fgtint_right   = #ffdcdcdc
}

graph {
  grid       = 32,8
  ipad       = 4
  rotate     = false;
  flip_y_opt = true;
  slant      = true;

  a->b;
  b->c {
     unfold = true;
     anchor = 1;
     1 -> 2 {
        unfold = true;
        rotate = true;
        flip_y = false;  // (todo) can't flip (anchor '1' would not be on top/bottom side when unfolding 'c')  => BUT: main graph flip_y_opt takes care of this
        anchor = x;

        x<-y<-z;
        x<-z;
     }
     1 -> 3 {
        unfold = true;
        flip_x = false;
        anchor = B;
        A {
           unfold = true;
           rotate = true;
           flip_y = false;
           k;
        }
        D {
           unfold = true;
           rotate = false;
           flip_y = false;
           p<-q;
        }
        A->B<-C;
        D->A;
     }
  }

}
