
TTF_NORMAL=../../../tkui/fonts/Tahoma.ttf
TTF_BOLD=../../../tkui/fonts/tahomabd.ttf

.PHONY: all
all:
	tks font_convert $(TTF_NORMAL) default normal 9
	tks font_convert $(TTF_NORMAL) default normal 18
	tks font_convert $(TTF_NORMAL) default normal 11
	tks font_convert $(TTF_NORMAL) default normal 22
	tks font_convert $(TTF_NORMAL) default normal 13
	tks font_convert $(TTF_NORMAL) default normal 26
	tks font_convert $(TTF_NORMAL) default normal 30
	tks font_convert $(TTF_BOLD)   default bold   13
	tks font_convert $(TTF_BOLD)   default bold   26
	tks font_convert $(TTF_NORMAL) default normal 17
	tks font_convert $(TTF_NORMAL) default normal 34
	tks font_convert $(TTF_NORMAL) default normal 24
	tks font_convert $(TTF_NORMAL) default normal 48
