#
# Makefile for tkoldmath plugin on macOS / Clang platform
#
# (c) 2001-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tkoldmath

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_macos.mk
