#
# Makefile for tkoldmath plugin on MingW / GCC platform
# 
# (c) 2001-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tkoldmath

EXTRAFLAGS= 

EXTRALIBS= -luuid -lopengl32 -lglu32

PLAF_OBJ= 

include make.objects

include ../plugin_mingw.mk
