#
# Makefile for tkoldmath plugin + Microsoft Visual C++ 2003 / 2005 / 2008 / .. / 2022 ToolKit
# 
# (c) 2001-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkoldmath

EXTRAFLAGS = 

EXTRALIBS= 

PLAF_OBJ = 

include make.objects

include ../plugin_msvc.mk
