#
# Makefile for tkoldmath plugin on Linux / GCC platform
# 
# (c) 2001-2025 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkoldmath

ifeq ($(CROSS_TARGET),DNX_POKY)
EXTRAFLAGS= -DDX_GLES
else
EXTRAFLAGS=
endif

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_linux.mk
