#
# Makefile for tksamplechain plugin on macOS / GCC platform
#
# (c) 2016-2025 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksamplechain

EXTRAFLAGS=
# -std=c++0x

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../plugin_macos.mk
