#
# Makefile for tksamplechain plugin on macOS / Clang platform
#
# (c) 2016-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksamplechain

EXTRAFLAGS=
# -std=c++0x

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_macos.mk
