#
# Makefile for tksamplechain plugin on Windows / Visual C++ platform
#
# (c) 2016-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tksamplechain

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
