#
# Makefile for tksampleedit plugin on Windows / Visual C++ platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

#FORCE_NO_WINDDK=y

include ../install_msvc.mk

PLUGIN=tksampleedit

EXTRAFLAGS = -DUSE_TKMINNIE

EXTRALIBS= uuid.lib opengl32.lib

PLAF_OBJ =

include make.objects

include ../build_msvc.mk
