#
# Makefile for tksampleedit plugin on macOS / Clang platform
#
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksampleedit

EXTRAFLAGS= -DUSE_TKMINNIE

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_macos.mk
