#
# Makefile for tksampleedit plugin on Linux / GCC platform
#
# (c) 2009-2025 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tksampleedit

#-I$(CROSS_ROOT)/usr/include -I/usr/local/include -I/usr/X11R6/include
EXTRAFLAGS=

#-L/usr/lib -L/usr/local/lib -L/usr/X11R6/lib -lGL -lm -lX11 -lXext
EXTRALIBS=

PLAF_OBJ=

ifeq ($(CROSS_TARGET),OMAP3)
EXTRAFLAGS += -DNO_SHADE
endif

EXTRAFLAGS += -DUSE_TKMINNIE

include make.objects

include ../plugin_linux.mk
