#
# Makefile for tksampleedit plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
#
# (c) 2009-2025 Bastian Spiegel <bs@tkscript.de>
#

#FORCE_NO_WINDDK=y

include ../install_msvc.mk

PLUGIN=tksampleedit

EXTRAFLAGS = -DUSE_TKMINNIE

EXTRALIBS= uuid.lib opengl32.lib

PLAF_OBJ =

include make.objects

include ../plugin_msvc.mk
