#
# Makefile for tksampleedit plugin on macOS / GCC platform
#
# (c) 2009-2025 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksampleedit

EXTRAFLAGS= -DUSE_TKMINNIE

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../plugin_macos.mk
