#
# Makefile for tksampleedit plugin on MingW / GCC platform
# 
# (c) 2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tksampleedit

EXTRAFLAGS= 

EXTRALIBS= -luuid -lopengl32

PLAF_OBJ= 

include make.objects

include ../plugin_mingw.mk
