#
# Makefile for tkmidi_portmidi plugin + Microsoft Visual C++ 2022 ToolKit
# 
# (c) 2007-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkmidi

PORTMIDI=portmidi-master

EXTRAFLAGS= -I$(PORTMIDI)/pm_common -I$(PORTMIDI)/porttime

EXTRALIBS= winmm.lib advapi32.lib
# uuid.lib kernel32.lib

PLAF_OBJ= \
	$(PORTMIDI)/pm_win/pmwin.o \
	$(PORTMIDI)/pm_win/pmwinmm.o \
	$(PORTMIDI)/porttime/ptwinmm.o

include make.objects
ALL_OBJ += $(PLAF_OBJ)

include ../plugin_msvc.mk
