# CLAP pluginlist filter categories (filter string presets)
#  (note) all strings are treated case-insensitive

Amp
Channel
Compress
Tape
Delay
Chorus
Reverb
EQ
Filter
Master
Mono Synth
Poly Synth
Drums
fav
menu

[Amp]
Airwindows Consolidated
Saturn 2
Surge XT Effects
WaveBox

[Channel]
Airwindows Consolidated
Pro-G
Saturn 2
Surge XT Effects

[Compress]
Airwindows Consolidated
Pro-C 2
Pro-C 3
Saturn 2
Surge XT Effects

[Tape]
Airwindows Consolidated
CHOWTapeModel
Reels
Satin

[Delay]
Airwindows Consolidated
AlborosieDubStation
ColourCopy
Dark Memory
Outer Space
Reels
Space Station UM282
Surge XT Effects
Timeless
ValhallaFutureVerb

[Chorus]
ColourCopy
Chief Chorus
Full Bucket Frequency Shifter
TAL-Chorus-LX
Timeless

[EQ]
Airwindows Consolidated
Pro-Q
Surge XT Effects

[Filter]
Airwindows Consolidated
Dub Filter
Filterjam
TAL-Filter-2

[Reverb]
Airwindows Consolidated
Alborosie Dub Station
Fog Convolver 2
Polaris
Pro-R 2
Springs
Surge XT Effects
TAL-G-Verb
TAL Reverb 4
ValhallaFutureVerb
VertiVerb VRS23
ZRev

[Master]
Airwindows Consolidated
CHOWTapeModel
Pro-L 2
Satin

[Mono Synth]
Repro-1
TAL Bassline 101

[Poly Synth]
Bazille
Diva
Pianoteq
Repro-5
TAL-J-8
TAL-J8X
TAL Mod
TAL-NoiseMaker
TAL-Pha
TAL Sampler
TAL U-No-LX-V2
Twin 3
Surge XT

[Drums]


[fav]
Airwindows Consolidated
CHOWTapeModel
ColourCopy
Dark Memory
Full Bucket Frequency Shifter
Outer Space
Pro-C 3
Pro-G
Pro-Q 4
Pro-R 2
Reels
Satin
Saturn 2
Surge XT Effects
WaveBox
Zebra3

[menu]
Airwindows Consolidated
CHOWTapeModel
ColourCopy
Dark Memory
Full Bucket Frequency Shifter
Outer Space
Pro-C 3
Pro-G
Pro-Q 4
Pro-R 2
Reels
Saturn 2
Surge XT Effects
TAL-Filter-2
WaveBox
Zebra3

#default=fav
default=
