#
# Makefile for tkanalogrytm plugin + Microsoft Visual C++ 2003 / 2005 / 2008 / 2013 ToolKit
#
# (c) 2016 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkanalogrytm

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../plugin_msvc.mk
