#
# Makefile for tkanalogrytm plugin on macOS / GCC platform
#
# (c) 2016-2023 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tkanalogrytm

EXTRAFLAGS += -Wno-unused-value
EXTRAFLAGS_CPP= -std=c++0x

EXTRALIBS= -lm

PLAF_OBJ=

include make.objects

include ../plugin_macos.mk
