#
# Makefile for tkanalogrytm plugin on Linux / GCC platform
#
# (c) 2016-2023 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkanalogrytm

EXTRAFLAGS_CPP= -std=c++0x

EXTRALIBS= -lm

PLAF_OBJ=

include make.objects

include ../plugin_linux.mk
