
eureka.tkx: eureka.tkp *.tks
	$(TKS) -c eureka

.PHONY: bin
bin: eureka.tkx

.PHONY: install
install: eureka.tkx
# (note) eureka writes / loads *.dat cache files to / from current dir
#         i.e. it's not a good idea to launch the app from an arbitrary dir
#	cp eureka.tkx "$(TKS_SITE_PREFIX)/applications/"

.PHONY: clean
clean:
	rm -f eureka.tkx
