#
# Makefile for tkradiastools plugin on macOS / GCC platform
# 
# (c) 2007-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tkradiastools

EXTRAFLAGS= -Wno-unused-but-set-variable -Wno-unused-function

EXTRALIBS= -lm

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
