#
# Makefile for tkradiastools plugin on Linux / GCC platform
# 
# (c) 2007-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkradiastools

EXTRAFLAGS=

EXTRALIBS= -lm

PLAF_OBJ= 

include make.objects

include ../plugin_linux.mk
