#
# Makefile for tkradiastools plugin on MingW / GCC platform
# 
# (c) 2007-2010 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_mingw.mk

PLUGIN=tkradiastools

EXTRAFLAGS= 

EXTRALIBS=

PLAF_OBJ= 

include make.objects

include ../plugin_mingw.mk
