#
# Makefile for tkradiastools plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2007-2010 Bastian Spiegel <bs@tkscript.de> 
#

#FORCE_NO_WINDDK=y

include ../install_msvc.mk

PLUGIN=tkradiastools

EXTRAFLAGS = 

EXTRALIBS= 

PLAF_OBJ = 

include make.objects

include ../plugin_msvc.mk
