#
# Makefile for tkradiastools plugin on Linux / GCC / Clang platform
#
# (c) 2007-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkradiastools

EXTRAFLAGS=

EXTRALIBS= -lm

PLAF_OBJ=

include make.objects

include ../build_linux.mk
