#
# Makefile for tkvst2 plugin on macOS / Clang platform
#
# (c) 2023-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tkvst2

#
# Set this to the VST2.x SDK installation directory
#
#VSTSDK2=f:/dev/vstsdk2.4
VSTSDK2=$(HOME)/sources/vstsdk2.4

EXTRAFLAGS= -I"$(VSTSDK2)" -Wno-dangling-else

EXTRALIBS= -framework ApplicationServices

PLAF_OBJ=

include make.objects

include ../build_macos.mk
