#
# Makefile for tkvst2 plugin on macOS
# 
# (c) 2010-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tkvst2

#
# Set this to the VST2.x SDK installation directory
#
#VSTSDK2=f:/dev/vstsdk2.4
VSTSDK2=../../sources/vstsdk2.4

EXTRAFLAGS= -I"$(VSTSDK2)" -Wno-dangling-else

EXTRALIBS= -framework Carbon -framework ApplicationServices

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
