#
# Makefile for tkvst2 plugin + Microsoft Visual C++ 2003 / 2005 / 2008 / 2010 / 2013 / 2015 / 2017 ToolKit
# 
# (c) 2010-2019 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkvst2

#
# Set this to the VST2.x SDK installation directory
#
#VSTSDK2=h:/dev/vstsdk2.4
VSTSDK2=f:/dev/vstsdk2.4

EXTRAFLAGS= -I"$(VSTSDK2)"

EXTRALIBS= user32.lib gdi32.lib

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
