#
# Makefile for tkvst2 plugin on Windows / Visual C++ platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkvst2

#
# Set this to the VST2.x SDK installation directory
#
#VSTSDK2=h:/dev/vstsdk2.4
VSTSDK2=f:/dev/vstsdk2.4

EXTRAFLAGS= -I"$(VSTSDK2)"

EXTRALIBS= user32.lib gdi32.lib

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
