#
# Makefile for tksdl2 plugin on Windows / Visual C++ platform
#
# (c) 2001-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

SDL=SDL2-2.32.4

PLUGIN=tksdl

PLAF_OBJ = Clipboard_win32.o

EXTRAFLAGS = -DTKSDL_BUILD -DHAVE_SDL

EXTRAFLAGS += -DUSE_JOYSTICKS

#EXTRAFLAGS += -DDX_GLES

EXTRAFLAGS += -I"$(SDL)/include" -I"$(DXSDK_INC)"

ifeq ($(BUILD_64),y)
SDL_LIB="$(SDL)/lib/x64/release/SDL2.lib"
else
SDL_LIB="$(SDL)/lib/x86/release/SDL2.lib"
endif

EXTRALIBS= user32.lib shell32.lib opengl32.lib -LIBPATH:"$(DXSDK_LIB)" ddraw.lib comctl32.lib $(SDL_LIB)

include make.objects

include ../build_msvc.mk
