#
# Makefile for tksdl [sdl2] plugin on Linux / GCC platform
#
# (c) 2001-2025 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tksdl

PLAF_OBJ= Clipboard_SDL2.o

EXTRAFLAGS = -DTKSDL_BUILD

include make.objects

EXTRAFLAGS += -I/usr/include -I/usr/local/include -I/usr/X11R6/include
EXTRAFLAGS += -DHAVE_X11 -DDX_GLSWAPINTERVALEXT -DHAVE_TIMERFD

EXTRALIBS= -lSDL2 -lGL -lX11 -lXext

include ../plugin_linux.mk
