#
# Makefile for tksqlite plugin on Windows / Visual C++ platform
#
# (c) 2006-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tksqlite

EXTRAFLAGS=  -I./

EXTRALIBS=

PLAF_OBJ=

SQLITE_PATH=sqlite-amalgamation-3400100

include make.objects

include ../build_msvc.mk
