#
# Makefile for tksqlite plugin on macOS / Clang
#
# (c) 2006-2024 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tksqlite

EXTRAFLAGS=  -I./
EXTRAFLAGS+= -Wno-unused-but-set-variable
EXTRAFLAGS+= -Wno-unused-function

EXTRALIBS=

PLAF_OBJ=

SQLITE_PATH=sqlite-amalgamation-3400100

include make.objects

include ../plugin_macos.mk
