#
# Makefile for tksqlite plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2006-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tksqlite

EXTRAFLAGS=  -I./

EXTRALIBS= 

PLAF_OBJ= 

SQLITE_PATH=sqlite-amalgamation-3400100

include make.objects

include ../plugin_msvc.mk
