
ALL_SRC= \
	KorgRadias.tks

syntheditor_korg_radias.tsl: $(ALL_SRC)
	tks -cl syntheditor_korg_radias && mv syntheditor_korg_radias.tsl ../libraries/

.PHONY: clean
clean:
	rm -f syntheditor_korg_radias.tsl
