
include ../../plugin_pre_macos.mk

include makefile.common

include ../../plugin_post_macos.mk

# (note) -Oz causes (slight) issues with dly_* plugins (Apple clang version 21.0.0 (clang-2100.0.123.102))
#          => use -Os
dly_1.o: dly_1.cpp
	$(CPP) $(CPPFLAGS) -Os $(DBGFLAGS) -c $< -o $@

dly_2.o: dly_2.cpp
	$(CPP) $(CPPFLAGS) -Os $(DBGFLAGS) -c $< -o $@

dly_flt_2.o: dly_flt_2.cpp
	$(CPP) $(CPPFLAGS) -Os $(DBGFLAGS) -c $< -o $@

dly_1_fade.o: dly_1_fade.cpp
	$(CPP) $(CPPFLAGS) -Os $(DBGFLAGS) -c $< -o $@

dly_2_fade.o: dly_2_fade.cpp
	$(CPP) $(CPPFLAGS) -Os $(DBGFLAGS) -c $< -o $@

dly_flt_2_fade.o: dly_flt_2_fade.cpp
	$(CPP) $(CPPFLAGS) -Os $(DBGFLAGS) -c $< -o $@

dly_flt_2_mod.o: dly_flt_2_mod.cpp
	$(CPP) $(CPPFLAGS) -Os $(DBGFLAGS) -c $< -o $@
