#
# % cd tks-source
# % m lib
# % cd test_lib
# % m bin
# % DYLD_FALLBACK_LIBRARY_PATH=../ ./test_lib
#   test.tks: hello, main
#   test.tks: tks_lib_init()
#   test.tks: hello, MyFunction
#   test.tks: tks_lib_exit()
#
# OR
#
# % cd tks-source
# % m lib
# % m install_lib
# % cd test_lib
# % m bin
# % ./test_lib
#   test.tks: hello, main
#   test.tks: tks_lib_init()
#   test.tks: hello, MyFunction
#   test.tks: tks_lib_exit()
#

.PHONY: bin
bin: test_lib.c
	$(CC) test_lib.c -o test_lib -L../ -ltks

.PHONY: clean
clean:
	rm -f test_lib.o test_lib
