#
# $ cd tks-source
# $ m lib
# $ cd test_lib
# $ m bin
# $ ./test_lib
#   test.tks: hello, main
#   test.tks: tks_lib_init()
#   test.tks: hello, MyFunction
#   test.tks: tks_lib_exit()
#

TKS_LIB=y
include ../../install_msvc.mk

CPPFLAGS+= -nologo -W3 -Zp8 -GR- -EHs-c-
EXTRALIBS= urlmon.lib advapi32.lib uuid.lib kernel32.lib
LDFLAGS+=
# /verbose:lib /LTCG:incremental

.c.o:
	$(CC) -c $< $(CPPFLAGS) -Fo"$@"

.PHONY: bin
bin: test_lib.o
	$(LD) $(LDFLAGS) -OUT:test_lib.exe test_lib.o ../tks.lib $(EXTRALIBS)
	@ls -ld test_lib.exe

.PHONY: clean
clean:
	rm -f test_lib.o test_lib.exe
