// ----
// ---- file   : test_xdly_7.cpp
// ---- author : 
// ---- legal  : Distributed under terms of the MIT license (https://opensource.org/licenses/MIT)
// ----
// ----          Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
// ----          associated documentation files (the "Software"), to deal in the Software without restriction, including
// ----          without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// ----          copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to
// ----          the following conditions:
// ----
// ----          The above copyright notice and this permission notice shall be included in all copies or substantial
// ----          portions of the Software.
// ----
// ----          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// ----          NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// ----          IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// ----          WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// ----          SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ----
// ---- info   : auto-generated by "Cycle"
// ----           $ g++ -Wall -Wno-unused-function -Wno-unused-variable -I../../tksampler -c test_xdly_7.cpp -o test_xdly_7.o
// ---- created: 22Dec2024 15:14:36
// ----
// ----
// ----

// (note) pre-define CYCLE_SKIP_UI to skip all code used only for UI/editing purposes (e.g. when compiling for standalone replay)
// #define CYCLE_SKIP_UI  defined

#define ST_DELAY_SIZE 32768
#define ST_DELAY_MASK 32767
#define ST_DELAY_SIZE 32768
#define ST_DELAY_MASK 32767
#define ST_DELAY_SIZE 32768
#define ST_DELAY_MASK 32767
#define ST_DELAY_SIZE 32768
#define ST_DELAY_MASK 32767
#include <plugin.h>

#include <stdlib.h>
#include <math.h>
#include <string.h>

#include "xdly.h"
// xdly module-static test code line
// xdly module-static test code line
// xdly module-static test code line
// xdly module-static test code line

#define PARAM_T                  0
#define PARAM_FB                 1
#define PARAM_WET                2
#define PARAM_LFO_AMT            3
#define PARAM_FB2                4
#define PARAM_WET2               5
#define PARAM_DLY_LVL            6
#define PARAM_FLT                7
#define NUM_PARAMS               8
#ifndef CYCLE_SKIP_UI
static const char *loc_param_names[NUM_PARAMS
#if defined(_MSC_VER) && 0 == NUM_PARAMS
                                   +1
#endif
                                   ] = {
#if defined(_MSC_VER) && 0 == NUM_PARAMS
                                   ""
#else
   "t",                       // 0: T
   "fb",                      // 1: FB
   "wet",                     // 2: WET
   "lfo_amt",                 // 3: LFO_AMT
   "fb2",                     // 4: FB2
   "wet2",                    // 5: WET2
   "dly_lvl",                 // 6: DLY_LVL
   "flt",                     // 7: FLT

#endif
};
#endif // CYCLE_SKIP_UI
static float loc_param_resets[NUM_PARAMS
#if defined(_MSC_VER) && 0 == NUM_PARAMS
                                   +1
#endif
                              ] = {
#if defined(_MSC_VER) && 0 == NUM_PARAMS
   0.0f
#else
   0.5f,                      // 0: T
   0.5f,                      // 1: FB
   0.5f,                      // 2: WET
   0.0f,                      // 3: LFO_AMT
   0.0f,                      // 4: FB2
   0.0f,                      // 5: WET2
   0.0f,                      // 6: DLY_LVL
   0.5f,                      // 7: FLT

#endif
};

#define MOD_T                    0
#define MOD_FB                   1
#define MOD_WET                  2
#define MOD_LFO_AMT              3
#define MOD_LFOPHASE             4
#define MOD_FB2                  5
#define MOD_WET2                 6
#define MOD_FLT                  7
#define NUM_MODS                 8
#ifndef CYCLE_SKIP_UI
static const char *loc_mod_names[NUM_MODS
#if defined(_MSC_VER) && 0 == NUM_MODS
   +1
#endif
                                 ] = {
#if defined(_MSC_VER) && 0 == NUM_MODS
   ""
#else
   "t",                    // 0: T
   "fb",                   // 1: FB
   "wet",                  // 2: WET
   "lfo_amt",              // 3: LFO_AMT
   "lfophase",             // 4: LFOPHASE
   "fb2",                  // 5: FB2
   "wet2",                 // 6: WET2
   "flt",                  // 7: FLT

#endif
};
#endif // CYCLE_SKIP_UI

typedef struct test_xdly_7_info_s {
   st_plugin_info_t base;
} test_xdly_7_info_t;

typedef struct test_xdly_7_shared_s {
   st_plugin_shared_t base;
   float params[NUM_PARAMS
#if defined(_MSC_VER) && 0 == NUM_PARAMS
                +1
#endif
                ];
   float array_p_dly_lvl[4/*var*/][4/*size*/];
   int forced_varidx_p_dly_lvl;
   float array_p_flt[4/*var*/][4/*size*/];
   int forced_varidx_p_flt;

} test_xdly_7_shared_t;

typedef struct test_xdly_7_voice_s {
   st_plugin_voice_t base;
   float             sample_rate;
   float             bpm;
   float             velocity;
   float             note_speed_fixed;
   float             note_speed_cur;
   float             note_speed_inc;
   float             note_cur;
   float             note_inc;
   float             mods[NUM_MODS
#if defined(_MSC_VER) && 0 == NUM_MODS
                          +1
#endif
                          ];
   float mod_t_cur;
   float mod_t_inc;
   float mod_fb_cur;
   float mod_fb_inc;
   float mod_wet_cur;
   float mod_wet_inc;
   float mod_lfo_amt_cur;
   float mod_lfo_amt_inc;
   float mod_lfophase_cur;
   float mod_fb2_cur;
   float mod_fb2_inc;
   float mod_wet2_cur;
   float mod_wet2_inc;
   float mod_flt_cur;
   float mod_flt_inc;

   float tmp1_sin_phase;
   float tmp2;
   float tmp3;
   short tmp4;
   short tmp5;
   float tmp6;
   short tmp7;
   unsigned short tmp8_lfsr_state;
   short tmp9_lfsr_state_signed;
   short tmp10;
   float tmp11_hbx_last;
   short tmp12;
   float tmp13_saw_phase;
   float tmp14;
   float tmp15_saw_phase;
   float tmp16_saw_phase;
   float tmp17_saw_phase;
   float tmp18_svf_lp;
   float tmp19_svf_hp;
   float tmp20_svf_bp;
   float tmp21_svf_lp;
   float tmp22_svf_hp;
   float tmp23_svf_bp;
   float tmp24_tri_phase;
   float tmp25;
   float tmp26_svf_lp;
   float tmp27_svf_hp;
   float tmp28_svf_bp;
   float tmp29_svf_lp;
   float tmp30_svf_hp;
   float tmp31_svf_bp;
   float tmp32_tri_phase;
   float tmp33_svf_lp;
   float tmp34_svf_hp;
   float tmp35_svf_bp;
   float tmp36_svf_lp;
   float tmp37_svf_hp;
   float tmp38_svf_bp;
   float tmp39_tri_phase;
   float tmp40_svf_lp;
   float tmp41_svf_hp;
   float tmp42_svf_bp;
   float tmp43_svf_lp;
   float tmp44_svf_hp;
   float tmp45_svf_bp;
   float tmp46_tri_phase;
   float var_x;
   float var_v_toneenv;
   float var_v_noiseenv;
   float var_v_last;
   float var_v_t;
   float var_out__mapkey;
   float var_out__outdry;
   float var_out__out;
   float var_out__lfo1raw;
   float var_out__lfo1;
   float var_out__lfo2raw;
   float var_out__lfo2;
   float var_out__lfo3raw;
   float var_out__lfo3;
   float var_out__lfo4raw;
   float var_out__lfo4;

   float mapvar_mymap_tonevol;
   float mapvar_mymap_tonefreq;
   float mapvar_mymap_noisevol;
   float mapvar_mymap_noisehp;
   float eff_array_p_dly_lvl[4/*size*/];
   float last_varidx_p_dly_lvl;
   float eff_array_p_flt[4/*size*/];
   float last_varidx_p_flt;
   float sr_factor;
   float mul_sr_0;  // 0.9993f
   float mul_sr_1;  // 0.9995f
   XDly xdly_0;
   XDly xdly_1;
   XDly xdly_2;
   XDly xdly_3;

} test_xdly_7_voice_t;

static const float mapvalues_mymap[(3 * 4)/*12*/] = {
   /*    0 */ 0.0f, 1.0f, 2.5f, 0.98f, 
   /*    1 */ 1.0f, 1.3f, 0.8f, 0.2f, 
   /*    2 */ 1.0f, 0.25f, 0.0f, 0.1f, 
};

static const float mapkeys_mymap[3] = {
   /*    0 */ 0.33f,
   /*    1 */ 0.66f,
   /*    2 */ 0.99f,
};

static const float mapdeltalin_mymap[2] = {
   /*    0 */ 3.0303f,
   /*    1 */ 3.0303f,
};

#define loop(X)  for(unsigned int i = 0u; i < (X); i++)
#define clamp(a,b,c) (((a)<(b))?(b):(((a)>(c))?(c):(a)))

static inline float mathLerpf(float _a, float _b, float _t) { return _a + (_b - _a) * _t; }
static inline float mathClampf(float a, float b, float c) { return (((a)<(b))?(b):(((a)>(c))?(c):(a))); }
static inline float mathMinf(float a, float b) { return (a<b)?a:b; }
static inline float mathMaxf(float a, float b) { return (a>b)?a:b; }
static inline float mathAbsMaxf(float _x, float _y) { return ( ( (_x<0.0f)?-_x:_x)>((_y<0.0f)?-_y:_y)?_x:_y ); }
static inline float mathAbsMinf(float _x, float _y) { return ( ((_x<0.0f)?-_x:_x)<((_y<0.0f)?-_y:_y)?_x:_y ); }
static inline float frac(float _x) { return _x - ((int)_x); }

static inline float winLinear(const float *_s, float _index) {
   int idx = (int)_index;
   float r = _index - (float)idx;
   return mathLerpf(_s[idx], _s[idx+1], r);
}

static float ffrac_s(float _f) { int i; if(_f >= 0.0f) { i = (int)_f; return _f - (float)i; } else { i = (int)-_f; return 1.0f - (-_f - (float)i); } }
static short curve_0[32] = {
0, 66, 132, 198, 264, 330, 396, 462, 528, 594, 660, 726, 792, 858, 924, 990, 1057, 1123, 1189, 1255, 1321, 1387, 1453, 1519, 1585, 1651, 1717, 1783, 1849, 1915, 1981, 2048, 
};
static short curve_1[32] = {
0, 66, 132, 198, 264, 330, 396, 462, 528, 594, 660, 726, 792, 858, 924, 990, 1057, 1123, 1189, 1255, 1321, 1387, 1453, 1519, 1585, 1651, 1717, 1783, 1849, 1915, 1981, 2048, 
};

#define USE_CYCLE_SINE_TBL  defined
static float cycle_sine_tbl_f[16384];

static void loc_init(st_plugin_voice_t *_voice);

void loc_init(st_plugin_voice_t *_voice) {
   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);
   ST_PLUGIN_VOICE_SHARED_CAST(test_xdly_7_shared_t);

   float out = 0.0f;
   (void)out;
   // -------- lane "init" modIdx=0 modString=set v_toneenv
   
   // -- mod="set v_toneenv" dstVar=out
   voice->var_v_toneenv = 1;
   
   // -- mod="set v_noiseenv" dstVar=out
   voice->var_v_noiseenv = 1;
   
   // -- mod="set v_last" dstVar=out
   voice->var_v_last = 0;
} /* end init */


#ifndef CYCLE_SKIP_UI
static unsigned int loc_copy_chars(char *_d, const unsigned int _dSize, const char *_s) {
   unsigned int r = 0u;
   if(NULL != _d)
   {
      // Write min(dSize,len(s)) characters to 'd'
      char *d = _d;
      if(NULL != _s)
      {
         const char *s = _s;
         for(;;)
         {
            if(r < _dSize)
            {
               char c = s[r++];
               *d++ = c;
               if(0 == c)
                  break;
            }
            else
            {
               if(r > 0u)
                  d[-1] = 0;  // force ASCIIZ
               break;
            }
         }
      }
      else
      {
         if(_dSize > 0u)
         {
            _d[0] = 0;
            r = 1u;
         }
      }
   }
   else
   {
      // Return total length of source string
      if(NULL != _s)
      {
         const char *s = _s;
         for(;;)
         {
            char c = s[r++];
            if(0 == c)
               break;
         }
      }
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int loc_copy_floats(float              *_d,
                                    const unsigned int  _dSize,
                                    const float        *_s,
                                    const unsigned int  _sNum
                                    ) {
   unsigned int r = 0u;
   if(NULL != _d)
   {
      // Write min(dSize,sNum) characters to 'd'
      if(NULL != _s)
      {
         unsigned int num = (_sNum > _dSize) ? _dSize : _sNum;
         memcpy((void*)_d, (const void*)_s, num * sizeof(float));
         r = num;
      }
   }
   else
   {
      // Query total number of presets
      r = _sNum;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_param_name(st_plugin_info_t *_info,
                                                    unsigned int      _paramIdx
                                                    ) {
   (void)_info;
   return loc_param_names[_paramIdx];
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_param_group_name(st_plugin_info_t *_info,
                                                          unsigned int      _paramGroupIdx
                                                          ) {
   (void)_info;
   const char *r = NULL;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_param_group_idx(st_plugin_info_t *_info,
                                                          unsigned int      _paramIdx
                                                          ) {
   (void)_info;
   unsigned int r = ~0u;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_param_section_name(st_plugin_info_t *_info,
                                                            unsigned int      _paramSectionIdx
                                                            ) {
   (void)_info;
   const char *r = NULL;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_param_section_idx(st_plugin_info_t *_info,
                                                            unsigned int      _paramIdx
                                                            ) {
   (void)_info;
   unsigned int r = ~0u;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static float ST_PLUGIN_API loc_get_param_reset(st_plugin_info_t *_info,
                                               unsigned int      _paramIdx
                                               ) {
   (void)_info;
   return loc_param_resets[_paramIdx];
}
#endif // CYCLE_SKIP_UI

static float ST_PLUGIN_API loc_get_param_value(st_plugin_shared_t *_shared,
                                               unsigned int        _paramIdx
                                               ) {
   ST_PLUGIN_SHARED_CAST(test_xdly_7_shared_t);
   return shared->params[_paramIdx];
}

static void ST_PLUGIN_API loc_set_param_value(st_plugin_shared_t *_shared,
                                              unsigned int        _paramIdx,
                                              float               _value
                                              ) {
   ST_PLUGIN_SHARED_CAST(test_xdly_7_shared_t);
   shared->params[_paramIdx] = _value;
}

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_query_dynamic_param_preset_values(st_plugin_shared_t *_shared,
                                                                        const unsigned int  _paramIdx,
                                                                        float              *_retValues,
                                                                        const unsigned int  _retValuesSize
                                                                        ) {
   ST_PLUGIN_SHARED_CAST(test_xdly_7_shared_t);
   unsigned int r = 0u;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_query_dynamic_param_preset_name(st_plugin_shared_t *_shared,
                                                                      const unsigned int  _paramIdx,
                                                                      const unsigned int  _presetIdx,
                                                                      char               *_retBuf,
                                                                      const unsigned int  _retBufSize
                                                                      ) {
   ST_PLUGIN_SHARED_CAST(test_xdly_7_shared_t);
   unsigned int r = 0u;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_array_param_size(st_plugin_info_t   *_info,
                                                           const unsigned int  _paramIdx
                                                           ) {
   unsigned int r = 0u;
   switch(_paramIdx)
   {
      default:
         break;

      case 6: // param "p_dly_lvl"
         return 4u;

      case 7: // param "p_flt"
         return 4u;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_array_param_num_variations(st_plugin_info_t   *_info,
                                                                     const unsigned int  _paramIdx
                                                                     ) {
   unsigned int r = 0u;
   switch(_paramIdx)
   {
      default:
         break;

      case 6:  // param "p_dly_lvl"
         return 4u;

      case 7:  // param "p_flt"
         return 4u;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static float * ST_PLUGIN_API loc_get_array_param_variation_ptr(st_plugin_shared_t *_shared,
                                                               const unsigned int  _paramIdx,
                                                               const unsigned int  _variationIdx
                                                               ) {
   ST_PLUGIN_SHARED_CAST(test_xdly_7_shared_t);
   float *r = NULL;
   switch(_paramIdx)
   {
      default:
         break;

      case 6:  // param "p_dly_lvl"
         return &shared->array_p_dly_lvl[_variationIdx][0];

      case 7:  // param "p_flt"
         return &shared->array_p_flt[_variationIdx][0];
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static void ST_PLUGIN_API loc_set_array_param_edit_variation_idx(st_plugin_shared_t *_shared,
                                                                 const unsigned int  _paramIdx,
                                                                 const int           _variationIdx
                                                                 ) {
   ST_PLUGIN_SHARED_CAST(test_xdly_7_shared_t);
   switch(_paramIdx)
   {
      default:
         break;

      case 6:  // param "p_dly_lvl"
         shared->forced_varidx_p_dly_lvl = _variationIdx;
         break;

      case 7:  // param "p_flt"
         shared->forced_varidx_p_flt = _variationIdx;
         break;
   }
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_array_param_element_name(st_plugin_info_t   *_info,
                                                                  const unsigned int  _paramIdx,
                                                                  const unsigned int  _elementIdx
                                                                  ) {
   ST_PLUGIN_INFO_CAST(test_xdly_7_info_t);
   const char *r = NULL;
   switch(_paramIdx)
   {
      default:
         break;

      case 6:  // param "p_dly_lvl"
         switch(_elementIdx)
         {
            default:
               break;

            case 0:  // element "p_dly_lvl.dly1"
               r = "dly1";
               break;

            case 1:  // element "p_dly_lvl.dly2"
               r = "dly2";
               break;

            case 2:  // element "p_dly_lvl.dly3"
               r = "dly3";
               break;

            case 3:  // element "p_dly_lvl.dly4"
               r = "dly4";
               break;
         }
         break;

      case 7:  // param "p_flt"
         switch(_elementIdx)
         {
            default:
               break;

            case 0:  // element "p_flt.dly1"
               r = "dly1";
               break;

            case 1:  // element "p_flt.dly2"
               r = "dly2";
               break;

            case 2:  // element "p_flt.dly3"
               r = "dly3";
               break;

            case 3:  // element "p_flt.dly4"
               r = "dly4";
               break;
         }
         break;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static int ST_PLUGIN_API loc_get_array_param_element_value_range(st_plugin_info_t   *_info,
                                                                 const unsigned int  _paramIdx,
                                                                 const unsigned int  _elementIdx,
                                                                 float              *_retStorageMin,
                                                                 float              *_retStorageMax,
                                                                 float              *_retDisplayMin,
                                                                 float              *_retDisplayMax,
                                                                 unsigned int       *_retDisplayPrecision
                                                                 ) {
   (void)_elementIdx;
   switch(_paramIdx)
   {
      default:
         break;

      case 6:  // param "p_dly_lvl"
         switch(_elementIdx)
         {
            default:
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = 0.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 0:  // element "p_dly_lvl.dly1"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = 0.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 1:  // element "p_dly_lvl.dly2"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = 0.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 2:  // element "p_dly_lvl.dly3"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = 0.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 3:  // element "p_dly_lvl.dly4"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = 0.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;
         }
         break;

      case 7:  // param "p_flt"
         switch(_elementIdx)
         {
            default:
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = -1.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 0:  // element "p_flt.dly1"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = -1.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 1:  // element "p_flt.dly2"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = -1.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 2:  // element "p_flt.dly3"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = -1.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;

            case 3:  // element "p_flt.dly4"
               if(NULL != _retStorageMin) *_retStorageMin = 0.0f;
               if(NULL != _retStorageMax) *_retStorageMax = 1.0f;
               if(NULL != _retDisplayMin) *_retDisplayMin = -1.0f;
               if(NULL != _retDisplayMax) *_retDisplayMax = 1.0f;
               if(NULL != _retDisplayPrecision) *_retDisplayPrecision = 5;
               return 1;
         }
         break;
   }
   return 0;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static float ST_PLUGIN_API loc_get_array_param_element_reset(st_plugin_info_t   *_info,
                                                             const unsigned int  _paramIdx,
                                                             const unsigned int  _elementIdx
                                                             ) {
   ST_PLUGIN_INFO_CAST(test_xdly_7_info_t);
   float r = -999999.0f/*INVALID_VALUE*/;
   switch(_paramIdx)
   {
      default:
         break;

      case 6:  // param "p_dly_lvl"
         switch(_elementIdx)
         {
            default:
               break;

            case 0:  // element "p_dly_lvl.dly1"
               r = 1.0f;
               break;

            case 1:  // element "p_dly_lvl.dly2"
               r = 0.0f;
               break;

            case 2:  // element "p_dly_lvl.dly3"
               r = 1.0f;
               break;

            case 3:  // element "p_dly_lvl.dly4"
               r = 0.0f;
               break;
         }
         break;

      case 7:  // param "p_flt"
         switch(_elementIdx)
         {
            default:
               break;

            case 0:  // element "p_flt.dly1"
               r = 1.0f;
               break;

            case 1:  // element "p_flt.dly2"
               r = 0.0f;
               break;

            case 2:  // element "p_flt.dly3"
               r = 1.0f;
               break;

            case 3:  // element "p_flt.dly4"
               r = 0.0f;
               break;
         }
         break;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static void ST_PLUGIN_API loc_update_lut(st_plugin_info_t   *_info,
                                         unsigned int        _idx,
                                         const float        *_src,
                                         const unsigned int  _srcNumElements
                                         ) {
   (void)_info;
   unsigned int copySz = 0u;
   (void)copySz;
   switch(_idx)
   {
      default:
         break;
      case 0: // "p_dly_lvl init"
         copySz = Dstplugin_min(_srcNumElements, 32);
         for(unsigned int i = 0u; i < copySz; i++)
            curve_0[i] = (short)(_src[i] * 2048);
         break;
      case 1: // "p_flt init"
         copySz = Dstplugin_min(_srcNumElements, 32);
         for(unsigned int i = 0u; i < copySz; i++)
            curve_1[i] = (short)(_src[i] * 2048);
         break;
   }
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_mod_name(st_plugin_info_t *_info,
                                                  unsigned int      _modIdx
                                                  ) {
   (void)_info;
   return loc_mod_names[_modIdx];
}
#endif // CYCLE_SKIP_UI

static void ST_PLUGIN_API loc_set_sample_rate(st_plugin_voice_t *_voice,
                                              float              _sampleRate
                                              ) {
   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);
   if(_sampleRate != voice->sample_rate)
   {
      voice->sr_factor = 48000.0f / _sampleRate;
      voice->mul_sr_0 = powf(0.9993f, voice->sr_factor);
      voice->mul_sr_1 = powf(0.9995f, voice->sr_factor);
   }
   voice->sample_rate = _sampleRate;
}

static void ST_PLUGIN_API loc_set_bpm(st_plugin_voice_t *_voice,
                                      float              _bpm
                                      ) {
   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);
   voice->bpm = _bpm;
}

static void ST_PLUGIN_API loc_note_on(st_plugin_voice_t  *_voice,
                                      int                 _bGlide,
                                      unsigned char       _note,
                                      float               _vel
                                      ) {
   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);
   ST_PLUGIN_VOICE_SHARED_CAST(test_xdly_7_shared_t);
   (void)_bGlide;
   (void)_note;
   (void)_vel;
   if(!_bGlide)
   {
      memset((void*)voice->mods, 0, sizeof(voice->mods));
#ifdef OVERSAMPLE_FACTOR
      voice->note_speed_fixed = (261.63f/*C-5*/ / (voice->sample_rate * OVERSAMPLE_FACTOR));
#else
      voice->note_speed_fixed = (261.63f/*C-5*/ / voice->sample_rate);
#endif // OVERSAMPLE_FACTOR
      voice->velocity = _vel;
      voice->tmp1_sin_phase = 0.0f;
      voice->tmp9_lfsr_state_signed = 0;
      voice->tmp11_hbx_last = 0.0f;
      voice->tmp13_saw_phase = 0.0f;
      voice->tmp15_saw_phase = 0.0f;
      voice->tmp16_saw_phase = 0.0f;
      voice->tmp17_saw_phase = 0.0f;
      voice->tmp18_svf_lp = 0.0f;
      voice->tmp19_svf_hp = 0.0f;
      voice->tmp20_svf_bp = 0.0f;
      voice->tmp21_svf_lp = 0.0f;
      voice->tmp22_svf_hp = 0.0f;
      voice->tmp23_svf_bp = 0.0f;
      voice->tmp24_tri_phase = 0.0f;
      voice->tmp26_svf_lp = 0.0f;
      voice->tmp27_svf_hp = 0.0f;
      voice->tmp28_svf_bp = 0.0f;
      voice->tmp29_svf_lp = 0.0f;
      voice->tmp30_svf_hp = 0.0f;
      voice->tmp31_svf_bp = 0.0f;
      voice->tmp32_tri_phase = 0.0f;
      voice->tmp33_svf_lp = 0.0f;
      voice->tmp34_svf_hp = 0.0f;
      voice->tmp35_svf_bp = 0.0f;
      voice->tmp36_svf_lp = 0.0f;
      voice->tmp37_svf_hp = 0.0f;
      voice->tmp38_svf_bp = 0.0f;
      voice->tmp39_tri_phase = 0.0f;
      voice->tmp40_svf_lp = 0.0f;
      voice->tmp41_svf_hp = 0.0f;
      voice->tmp42_svf_bp = 0.0f;
      voice->tmp43_svf_lp = 0.0f;
      voice->tmp44_svf_hp = 0.0f;
      voice->tmp45_svf_bp = 0.0f;
      voice->tmp46_tri_phase = 0.0f;
      voice->var_x = 0.0f;
      voice->var_v_toneenv = 0.0f;
      voice->var_v_noiseenv = 0.0f;
      voice->var_v_last = 0.0f;
      voice->var_v_t = 0.0f;
      voice->var_out__mapkey = 0.0f;
      voice->var_out__outdry = 0.0f;
      voice->var_out__out = 0.0f;
      voice->var_out__lfo1raw = 0.0f;
      voice->var_out__lfo1 = 0.0f;
      voice->var_out__lfo2raw = 0.0f;
      voice->var_out__lfo2 = 0.0f;
      voice->var_out__lfo3raw = 0.0f;
      voice->var_out__lfo3 = 0.0f;
      voice->var_out__lfo4raw = 0.0f;
      voice->var_out__lfo4 = 0.0f;
      voice->mapvar_mymap_tonevol = 0;
      voice->mapvar_mymap_tonefreq = 0;
      voice->mapvar_mymap_noisevol = 0;
      voice->mapvar_mymap_noisehp = 0;
      loc_init(&voice->base);
      voice->last_varidx_p_dly_lvl = 0.0f;
      memcpy((void*)voice->eff_array_p_dly_lvl, (const void*)&shared->array_p_dly_lvl[0/*varIdx*/][0], sizeof(float) * 4);
      voice->last_varidx_p_flt = 0.0f;
      memcpy((void*)voice->eff_array_p_flt, (const void*)&shared->array_p_flt[0/*varIdx*/][0], sizeof(float) * 4);
      voice->xdly_0.reset();
      voice->xdly_1.reset();
      voice->xdly_2.reset();
      voice->xdly_3.reset();
   }
}

static void ST_PLUGIN_API loc_set_mod_value(st_plugin_voice_t *_voice,
                                            unsigned int       _modIdx,
                                            float              _value,
                                            unsigned           _frameOffset
                                            ) {
   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);
   (void)_frameOffset;
   voice->mods[_modIdx] = _value;
}

static void ST_PLUGIN_API loc_prepare_block(st_plugin_voice_t *_voice,
                                            unsigned int       _numFrames,
                                            float              _freqHz,
                                            float              _note,
                                            float              _vol,
                                            float              _pan
                                            ) {
   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);
   ST_PLUGIN_VOICE_SHARED_CAST(test_xdly_7_shared_t);
   (void)_note;
   (void)_vol;
   (void)_pan;

#ifdef OVERSAMPLE_FACTOR
   float noteSpeed = _freqHz / (voice->sample_rate * OVERSAMPLE_FACTOR);
#else
   float noteSpeed = _freqHz / voice->sample_rate;
#endif // OVERSAMPLE_FACTOR

   float modt            = shared->params[PARAM_T           ]                       + voice->mods[MOD_T            ];
   float modfb           = shared->params[PARAM_FB          ]                       + voice->mods[MOD_FB           ];
   float modwet          = shared->params[PARAM_WET         ]                       + voice->mods[MOD_WET          ];
   float modlfo_amt      = shared->params[PARAM_LFO_AMT     ]                       + voice->mods[MOD_LFO_AMT      ];
   float modlfophase     = voice->mods[MOD_LFOPHASE     ];
   float modfb2          = shared->params[PARAM_FB2         ]                       + voice->mods[MOD_FB2          ];
   float modwet2         = shared->params[PARAM_WET2        ]                       + voice->mods[MOD_WET2         ];
   float modflt          = shared->params[PARAM_FLT         ]                       + voice->mods[MOD_FLT          ];

   // Update array param "p_dly_lvl" voice array
   if(shared->forced_varidx_p_dly_lvl >= 0 || shared->params[PARAM_DLY_LVL] != voice->last_varidx_p_dly_lvl)
   {
      float idxF = (shared->forced_varidx_p_dly_lvl >= 0) ? ((float)shared->forced_varidx_p_dly_lvl) : (shared->params[PARAM_DLY_LVL] * 4);
      float amtB = idxF - ((int)idxF);
      unsigned int idxA = (unsigned int)idxF;
      if(idxA >= 4u/*num_variations*/)
         idxA = 0u;
      unsigned int idxB = idxA + 1u;
      if(idxB >= 4u/*num_variations*/)
         idxB = 0u;
      const float *sA = &shared->array_p_dly_lvl[idxA][0];
      const float *sB = &shared->array_p_dly_lvl[idxB][0];
      float *d = &voice->eff_array_p_dly_lvl[0];
      for(unsigned int i = 0u; i < 4u; i++)
         d[i] = sA[i] + (sB[i] - sA[i]) * amtB;
      voice->last_varidx_p_dly_lvl = (shared->forced_varidx_p_dly_lvl >= 0) ? -1.0f : shared->params[PARAM_DLY_LVL];
   }

   // Update array param "p_flt" voice array
   if(shared->forced_varidx_p_flt >= 0 || modflt != voice->last_varidx_p_flt)
   {
      float idxF = (shared->forced_varidx_p_flt >= 0) ? ((float)shared->forced_varidx_p_flt) : (modflt * 4);
      float amtB = idxF - ((int)idxF);
      unsigned int idxA = (unsigned int)idxF;
      if(idxA >= 4u/*num_variations*/)
         idxA = 0u;
      unsigned int idxB = idxA + 1u;
      if(idxB >= 4u/*num_variations*/)
         idxB = 0u;
      const float *sA = &shared->array_p_flt[idxA][0];
      const float *sB = &shared->array_p_flt[idxB][0];
      float *d = &voice->eff_array_p_flt[0];
      for(unsigned int i = 0u; i < 4u; i++)
         d[i] = sA[i] + (sB[i] - sA[i]) * amtB;
      voice->last_varidx_p_flt = (shared->forced_varidx_p_flt >= 0) ? -1.0f : modflt;
   }

   if(_numFrames > 0u)
   {
      // lerp
#ifdef OVERSAMPLE_FACTOR
      float recBlockSize = (1.0f / (_numFrames * OVERSAMPLE_FACTOR));
#else
      float recBlockSize = (1.0f / _numFrames);
#endif // OVERSAMPLE_FACTOR
      voice->note_speed_inc = (noteSpeed - voice->note_speed_cur) * recBlockSize;
      voice->note_inc       = (_note - voice->note_cur) * recBlockSize;
      voice->mod_t_inc            = (modt               - voice->mod_t_cur             ) * recBlockSize;
      voice->mod_fb_inc           = (modfb              - voice->mod_fb_cur            ) * recBlockSize;
      voice->mod_wet_inc          = (modwet             - voice->mod_wet_cur           ) * recBlockSize;
      voice->mod_lfo_amt_inc      = (modlfo_amt         - voice->mod_lfo_amt_cur       ) * recBlockSize;
      voice->mod_lfophase_cur     = modlfophase;
      voice->mod_fb2_inc          = (modfb2             - voice->mod_fb2_cur           ) * recBlockSize;
      voice->mod_wet2_inc         = (modwet2            - voice->mod_wet2_cur          ) * recBlockSize;
      voice->mod_flt_inc          = (modflt             - voice->mod_flt_cur           ) * recBlockSize;
   }
   else
   {
      // initial params/modulation (first block, not rendered)
      voice->note_speed_cur = noteSpeed;
      voice->note_speed_inc = 0.0f;
      voice->note_cur       = _note;
      voice->note_inc       = 0.0f;
      voice->mod_t_cur            = modt;
      voice->mod_t_inc            = 0.0f;
      voice->mod_fb_cur           = modfb;
      voice->mod_fb_inc           = 0.0f;
      voice->mod_wet_cur          = modwet;
      voice->mod_wet_inc          = 0.0f;
      voice->mod_lfo_amt_cur      = modlfo_amt;
      voice->mod_lfo_amt_inc      = 0.0f;
      voice->mod_lfophase_cur     = modlfophase;
      voice->mod_fb2_cur          = modfb2;
      voice->mod_fb2_inc          = 0.0f;
      voice->mod_wet2_cur         = modwet2;
      voice->mod_wet2_inc         = 0.0f;
      voice->mod_flt_cur          = modflt;
      voice->mod_flt_inc          = 0.0f;
   }

   // printf("xxx note_cur=%f\n", voice->note_cur);
   // printf("xxx prepare_block: numFrames=%u moda=%f\n", _numFrames, moda);
   // printf("xxx voice->voicebus_idx_0=%u voice->base.voice_bus_read_offset=%u\n", voice->voicebus_idx_0, voice->base.voice_bus_read_offset);
}

static void ST_PLUGIN_API loc_process_replace(st_plugin_voice_t  *_voice,
                                              int                 _bMonoIn,
                                              const float        *_samplesIn,
                                              float              *_samplesOut,
                                              unsigned int        _numFrames
                                              ) {
   (void)_bMonoIn;
   (void)_samplesIn;

   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);
   ST_PLUGIN_VOICE_SHARED_CAST(test_xdly_7_shared_t);

   // Mono output (replicate left to right channel)
   unsigned int j = 0u;
#ifndef STEREO
   unsigned int jStep = _bMonoIn ? 1u : 2u;
#endif // STEREO
   unsigned int k = 0u;
   for(unsigned int i = 0u; i < _numFrames; i++)
   {
      const float inL = _samplesIn[j];
#ifdef STEREO
      float outL;
      float outR;
      const float inR = _samplesIn[j + 1u];
#endif // STEREO
      float out;
#ifdef OVERSAMPLE_FACTOR
#ifdef STEREO
      float outOSL = 0.0f;
      float outOSR = 0.0f;
#else
      float outOS = 0.0f;
#endif // STEREO
#endif // OVERSAMPLE_FACTOR

#ifdef OVERSAMPLE_FACTOR
      for(unsigned int osi = 0u; osi < OVERSAMPLE_FACTOR; osi++)
#endif // OVERSAMPLE_FACTOR
      {
#ifdef STEREO
         out = outL = inL;
         outR = inR;
#else
         out = inL;
#endif // STEREO
      float tmp_f; (void)tmp_f;
      float tmp2_f; (void)tmp2_f;
      
      // ========
      // ======== lane "out" modIdx=0 modString=note
      // ========
      
      // -- mod="note" dstVar=out
      out = voice->note_cur;
      
      // -- mod="0.333333" dstVar=out
      out *= 0.333333f;
      
      // -- mod="frc" dstVar=out
      out = ffrac_s(out);
      
      // -- mod="set out__mapkey" dstVar=out
      voice->var_out__mapkey = out;
      
      // -- mod="sin" dstVar=out
      
      // ---- mod="sin" input "freq" seq 1/1
      
      // -- mod="$out__mapkey" dstVar=voice->tmp3/*sin_freq*/
      voice->tmp3/*sin_freq*/ = voice->var_out__mapkey;
      
      // -- mod="map" dstVar=voice->tmp3/*sin_freq*/
      voice->tmp4/*idx*/ = 3;
      if(voice->tmp3/*sin_freq*/ > 0.33f)
      {
         if(voice->tmp3/*sin_freq*/ < 0.99f)
         {
            voice->tmp5/*field_idx*/ = 5/*tonefreq*/;
            for(voice->tmp4/*idx*/ = 1; voice->tmp4/*idx*/ >= 0; voice->tmp4/*idx*/--)
            {
               if(voice->tmp3/*sin_freq*/ > mapkeys_mymap[voice->tmp4/*idx*/])
               {
                  if( (mapkeys_mymap[voice->tmp4/*idx*/ + 1] - voice->tmp3/*sin_freq*/) > (voice->tmp3/*sin_freq*/ - mapkeys_mymap[voice->tmp4/*idx*/]) )
                  {
                     voice->tmp3/*sin_freq*/ = mapvalues_mymap[voice->tmp5/*field_idx*/];
                  }
                  else
                  {
                     voice->tmp3/*sin_freq*/ = mapvalues_mymap[voice->tmp5/*field_idx*/ + 4];
                  }
               }
               voice->tmp5/*field_idx*/ -= 4;
            }
         }
         else
         {
            voice->tmp3/*sin_freq*/ = mapvalues_mymap[8 + 1/*tonefreq*/];
         }
      }
      else
      {
         voice->tmp3/*sin_freq*/ = mapvalues_mymap[1/*tonefreq*/];
      }
      
      // -- mod="$v_toneenv" dstVar=voice->tmp3/*sin_freq*/
      voice->tmp6/*seq*/ = voice->tmp3/*sin_freq*/;
      voice->tmp6/*seq*/ = voice->var_v_toneenv;
      
      // -- mod="1.5" dstVar=voice->tmp6/*seq*/
      voice->tmp6/*seq*/ *= 1.5f;
      voice->tmp3/*sin_freq*/ += voice->tmp6/*seq*/;
      voice->tmp2/*sin_speed*/ = voice->note_speed_cur * voice->tmp3/*sin_freq*/;
      voice->tmp3/*sin_tmp*/ = (voice->tmp1_sin_phase);
      voice->tmp3/*sin_tmp*/ = ffrac_s(voice->tmp3/*sin_tmp*/);
      out = cycle_sine_tbl_f[(unsigned short)(16384 * voice->tmp3/*sin_tmp*/)&16383u];
      voice->tmp1_sin_phase = ffrac_s(voice->tmp1_sin_phase + voice->tmp2/*sin_speed*/);
      
      // -- mod="$out__mapkey" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->var_out__mapkey;
      
      // -- mod="map" dstVar=voice->tmp2/*seq*/
      voice->tmp4/*idx*/ = 3;
      if(voice->tmp2/*seq*/ > 0.33f)
      {
         if(voice->tmp2/*seq*/ < 0.99f)
         {
            voice->tmp7/*field_idx*/ = 4/*tonevol*/;
            for(voice->tmp4/*idx*/ = 1; voice->tmp4/*idx*/ >= 0; voice->tmp4/*idx*/--)
            {
               if(voice->tmp2/*seq*/ > mapkeys_mymap[voice->tmp4/*idx*/])
               {
                  if( (mapkeys_mymap[voice->tmp4/*idx*/ + 1] - voice->tmp2/*seq*/) > (voice->tmp2/*seq*/ - mapkeys_mymap[voice->tmp4/*idx*/]) )
                  {
                     voice->tmp2/*seq*/ = mapvalues_mymap[voice->tmp7/*field_idx*/];
                  }
                  else
                  {
                     voice->tmp2/*seq*/ = mapvalues_mymap[voice->tmp7/*field_idx*/ + 4];
                  }
               }
               voice->tmp7/*field_idx*/ -= 4;
            }
         }
         else
         {
            voice->tmp2/*seq*/ = mapvalues_mymap[8 + 0/*tonevol*/];
         }
      }
      else
      {
         voice->tmp2/*seq*/ = mapvalues_mymap[0/*tonevol*/];
      }
      out *= voice->tmp2/*seq*/;
      
      // -- mod="$v_toneenv" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->var_v_toneenv;
      out *= voice->tmp2/*seq*/;
      
      // -- mod="fsr" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp4/*i2f*/ = (int)(voice->tmp2/*seq*/ * 2048);  // IntFallback: F2I
      voice->tmp8_lfsr_state ^= voice->tmp8_lfsr_state >> 7;
      voice->tmp8_lfsr_state ^= voice->tmp8_lfsr_state << 9;
      voice->tmp8_lfsr_state ^= voice->tmp8_lfsr_state >> 13;
      voice->tmp9_lfsr_state_signed = (voice->tmp8_lfsr_state & 65520);
      voice->tmp4/*i2f*/ = voice->tmp9_lfsr_state_signed >> 4;
      voice->tmp2/*seq*/ = voice->tmp4/*i2f*/ / ((float)(2048));  // IntFallback: I2F
      
      // -- mod="$out__mapkey" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->var_out__mapkey;
      
      // -- mod="map" dstVar=voice->tmp3/*seq*/
      voice->tmp4/*idx*/ = 3;
      if(voice->tmp3/*seq*/ > 0.33f)
      {
         if(voice->tmp3/*seq*/ < 0.99f)
         {
            voice->tmp10/*field_idx*/ = 6/*noisevol*/;
            for(voice->tmp4/*idx*/ = 1; voice->tmp4/*idx*/ >= 0; voice->tmp4/*idx*/--)
            {
               if(voice->tmp3/*seq*/ > mapkeys_mymap[voice->tmp4/*idx*/])
               {
                  if( (mapkeys_mymap[voice->tmp4/*idx*/ + 1] - voice->tmp3/*seq*/) > (voice->tmp3/*seq*/ - mapkeys_mymap[voice->tmp4/*idx*/]) )
                  {
                     voice->tmp3/*seq*/ = mapvalues_mymap[voice->tmp10/*field_idx*/];
                  }
                  else
                  {
                     voice->tmp3/*seq*/ = mapvalues_mymap[voice->tmp10/*field_idx*/ + 4];
                  }
               }
               voice->tmp10/*field_idx*/ -= 4;
            }
         }
         else
         {
            voice->tmp3/*seq*/ = mapvalues_mymap[8 + 2/*noisevol*/];
         }
      }
      else
      {
         voice->tmp3/*seq*/ = mapvalues_mymap[2/*noisevol*/];
      }
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="$v_noiseenv" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->var_v_noiseenv;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="hbx" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="hbx" input "freq" seq 1/1
      
      // -- mod="$out__mapkey" dstVar=voice->tmp3/*freq*/
      voice->tmp3/*freq*/ = voice->var_out__mapkey;
      
      // -- mod="map" dstVar=voice->tmp3/*freq*/
      voice->tmp4/*idx*/ = 3;
      if(voice->tmp3/*freq*/ > 0.33f)
      {
         if(voice->tmp3/*freq*/ < 0.99f)
         {
            voice->tmp12/*field_idx*/ = 7/*noisehp*/;
            for(voice->tmp4/*idx*/ = 1; voice->tmp4/*idx*/ >= 0; voice->tmp4/*idx*/--)
            {
               if(voice->tmp3/*freq*/ > mapkeys_mymap[voice->tmp4/*idx*/])
               {
                  if( (mapkeys_mymap[voice->tmp4/*idx*/ + 1] - voice->tmp3/*freq*/) > (voice->tmp3/*freq*/ - mapkeys_mymap[voice->tmp4/*idx*/]) )
                  {
                     voice->tmp3/*freq*/ = mapvalues_mymap[voice->tmp12/*field_idx*/];
                  }
                  else
                  {
                     voice->tmp3/*freq*/ = mapvalues_mymap[voice->tmp12/*field_idx*/ + 4];
                  }
               }
               voice->tmp12/*field_idx*/ -= 4;
            }
         }
         else
         {
            voice->tmp3/*freq*/ = mapvalues_mymap[8 + 3/*noisehp*/];
         }
      }
      else
      {
         voice->tmp3/*freq*/ = mapvalues_mymap[3/*noisehp*/];
      }
      voice->tmp3/*freq*/ *= voice->tmp3/*freq*/;
      voice->tmp3/*freq*/ *= voice->tmp3/*freq*/;
      voice->tmp11_hbx_last = mathLerpf(voice->tmp11_hbx_last, voice->tmp2/*seq*/, voice->tmp3/*freq*/ * voice->sr_factor);
      voice->tmp2/*seq*/ = voice->tmp2/*seq*/ - voice->tmp11_hbx_last;
      out += voice->tmp2/*seq*/;
      
      // -- mod="$v_toneenv" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->var_v_toneenv;
      
      // -- mod="0.9993" dstVar=voice->tmp2/*seq*/
      voice->tmp2/*seq*/ *= voice->mul_sr_0;
      
      // -- mod="sto v_toneenv" dstVar=voice->tmp2/*seq*/
      voice->var_v_toneenv = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="$v_noiseenv" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->var_v_noiseenv;
      
      // -- mod="0.9995" dstVar=voice->tmp2/*seq*/
      voice->tmp2/*seq*/ *= voice->mul_sr_1;
      
      // -- mod="sto v_noiseenv" dstVar=voice->tmp2/*seq*/
      voice->var_v_noiseenv = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="2" dstVar=out
      out *= 2.0f;
      
      // -- mod="clp" dstVar=out
      if(out > 0.999f) out = 0.999f;
      else if(out < -0.999f) out = -0.999f;
      
      // -- mod="set out__outdry" dstVar=out
      voice->var_out__outdry = out;
      
      // -- mod="$v_last" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->var_v_last;
      
      // -- mod="$m_fb2" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->mod_fb2_cur;
      
      // -- mod="clp" dstVar=voice->tmp3/*seq*/
      if(voice->tmp3/*seq*/ > 1.0f) voice->tmp3/*seq*/ = 1.0f;
      else if(voice->tmp3/*seq*/ < 0.0f) voice->tmp3/*seq*/ = 0.0f;
      
      // -- mod="0.125" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ *= 0.125f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      out += voice->tmp2/*seq*/;
      
      // -- mod="set out__out" dstVar=out
      voice->var_out__out = out;
      
      // -- mod="saw" dstVar=out
      voice->tmp2/*seq*/ = out;
      
      // ---- mod="saw" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp6/*saw_freq*/
      voice->tmp6/*saw_freq*/ = 0.0f;
      voice->tmp3/*saw_speed*/ = voice->note_speed_fixed * voice->tmp6/*saw_freq*/;
      
      // ---- mod="saw" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ = voice->mod_lfophase_cur;
      voice->tmp6/*saw_tmp*/ = ((voice->tmp13_saw_phase + voice->tmp14/*phase*/));
      voice->tmp6/*saw_tmp*/ = ffrac_s(voice->tmp6/*saw_tmp*/);
      voice->tmp2/*seq*/ = 1.0f - (voice->tmp6/*saw_tmp*/ * 2.0f);
      
      // -- mod="set out__lfo1raw" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo1raw = voice->tmp2/*seq*/;
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 0.5f) + 0.5f;
      
      // -- mod="$m_lfo_amt" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->mod_lfo_amt_cur;
      
      // -- mod="0.025" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ *= 0.025f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="set out__lfo1" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo1 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="saw" dstVar=out
      voice->tmp2/*seq*/ = out;
      
      // ---- mod="saw" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp6/*saw_freq*/
      voice->tmp6/*saw_freq*/ = 0.0f;
      voice->tmp3/*saw_speed*/ = voice->note_speed_fixed * voice->tmp6/*saw_freq*/;
      
      // ---- mod="saw" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ = voice->mod_lfophase_cur;
      
      // -- mod="0.25" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ += 0.25f;
      voice->tmp6/*saw_tmp*/ = ((voice->tmp15_saw_phase + voice->tmp14/*phase*/));
      voice->tmp6/*saw_tmp*/ = ffrac_s(voice->tmp6/*saw_tmp*/);
      voice->tmp2/*seq*/ = 1.0f - (voice->tmp6/*saw_tmp*/ * 2.0f);
      
      // -- mod="set out__lfo2raw" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo2raw = voice->tmp2/*seq*/;
      
      // -- mod="$m_lfo_amt" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->mod_lfo_amt_cur;
      
      // -- mod="0.025" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ *= 0.025f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="set out__lfo2" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo2 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="saw" dstVar=out
      voice->tmp2/*seq*/ = out;
      
      // ---- mod="saw" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp6/*saw_freq*/
      voice->tmp6/*saw_freq*/ = 0.0f;
      voice->tmp3/*saw_speed*/ = voice->note_speed_fixed * voice->tmp6/*saw_freq*/;
      
      // ---- mod="saw" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ = voice->mod_lfophase_cur;
      
      // -- mod="0.5" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ += 0.5f;
      
      // -- mod="frc" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ = ffrac_s(voice->tmp14/*phase*/);
      voice->tmp6/*saw_tmp*/ = ((voice->tmp16_saw_phase + voice->tmp14/*phase*/));
      voice->tmp6/*saw_tmp*/ = ffrac_s(voice->tmp6/*saw_tmp*/);
      voice->tmp2/*seq*/ = 1.0f - (voice->tmp6/*saw_tmp*/ * 2.0f);
      
      // -- mod="set out__lfo3raw" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo3raw = voice->tmp2/*seq*/;
      
      // -- mod="$m_lfo_amt" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->mod_lfo_amt_cur;
      
      // -- mod="0.025" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ *= 0.025f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="set out__lfo3" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo3 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="saw" dstVar=out
      voice->tmp2/*seq*/ = out;
      
      // ---- mod="saw" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp6/*saw_freq*/
      voice->tmp6/*saw_freq*/ = 0.0f;
      voice->tmp3/*saw_speed*/ = voice->note_speed_fixed * voice->tmp6/*saw_freq*/;
      
      // ---- mod="saw" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ = voice->mod_lfophase_cur;
      
      // -- mod="0.75" dstVar=voice->tmp14/*phase*/
      voice->tmp14/*phase*/ += 0.75f;
      voice->tmp6/*saw_tmp*/ = ((voice->tmp17_saw_phase + voice->tmp14/*phase*/));
      voice->tmp6/*saw_tmp*/ = ffrac_s(voice->tmp6/*saw_tmp*/);
      voice->tmp2/*seq*/ = 1.0f - (voice->tmp6/*saw_tmp*/ * 2.0f);
      
      // -- mod="set out__lfo4raw" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo4raw = voice->tmp2/*seq*/;
      
      // -- mod="$m_lfo_amt" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->mod_lfo_amt_cur;
      
      // -- mod="0.025" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ *= 0.025f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="set out__lfo4" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo4 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="$m_t" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->mod_t_cur;
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="fma" input "add" seq 1/1
      
      // -- mod="$out__lfo1" dstVar=voice->tmp3/*add*/
      voice->tmp3/*add*/ = voice->var_out__lfo1;
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 0.025f) + voice->tmp3/*add*/;
      
      // -- mod="sto out__lfo1" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo1 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="$m_t" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->mod_t_cur;
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="fma" input "add" seq 1/1
      
      // -- mod="$out__lfo2" dstVar=voice->tmp3/*add*/
      voice->tmp3/*add*/ = voice->var_out__lfo2;
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 0.025f) + voice->tmp3/*add*/;
      
      // -- mod="sto out__lfo2" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo2 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="$m_t" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->mod_t_cur;
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="fma" input "add" seq 1/1
      
      // -- mod="$out__lfo3" dstVar=voice->tmp3/*add*/
      voice->tmp3/*add*/ = voice->var_out__lfo3;
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 0.025f) + voice->tmp3/*add*/;
      
      // -- mod="sto out__lfo3" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo3 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="$m_t" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->mod_t_cur;
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="fma" input "add" seq 1/1
      
      // -- mod="$out__lfo4" dstVar=voice->tmp3/*add*/
      voice->tmp3/*add*/ = voice->var_out__lfo4;
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 0.025f) + voice->tmp3/*add*/;
      
      // -- mod="sto out__lfo4" dstVar=voice->tmp2/*seq*/
      voice->var_out__lfo4 = voice->tmp2/*seq*/;
      // (ignore last output via '.')
      
      // -- mod="0" dstVar=out
      out = 0.0f;
      
      // -- mod="pluginarrayparamfield" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->eff_array_p_flt[0/*dly1*/];
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 2.0f) + -1.0f;
      
      // -- mod="sto v_t" dstVar=voice->tmp2/*seq*/
      voice->var_v_t = voice->tmp2/*seq*/;
      
      // -- mod="cmp" dstVar=voice->tmp2/*seq*/
      if(voice->tmp2/*seq*/ < 0.0f)
      {
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         
         // -- mod="1" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ += 1.0f;
         
         // -- mod="clp" dstVar=voice->tmp3/*addsr_freq*/
         if(voice->tmp3/*addsr_freq*/ > 1.0f) voice->tmp3/*addsr_freq*/ = 1.0f;
         else if(voice->tmp3/*addsr_freq*/ < 0.001f) voice->tmp3/*addsr_freq*/ = 0.001f;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp18_svf_lp = voice->tmp18_svf_lp + (voice->tmp20_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp19_svf_hp = voice->tmp2/*seq*/ - voice->tmp18_svf_lp - (voice->tmp20_svf_bp * 1.0f);
         voice->tmp20_svf_bp = voice->tmp20_svf_bp + (voice->tmp19_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp18_svf_lp;
      }
      else
      {
         
         // ---- mod="cmp" input "else" seq 1/1
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp21_svf_lp = voice->tmp21_svf_lp + (voice->tmp23_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp22_svf_hp = voice->tmp2/*seq*/ - voice->tmp21_svf_lp - (voice->tmp23_svf_bp * 1.0f);
         voice->tmp23_svf_bp = voice->tmp23_svf_bp + (voice->tmp22_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp22_svf_hp;
      }
      
      // -- mod="xdly" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="xdly" input "t" seq 1/1
      
      // -- mod="$out__lfo1" dstVar=voice->tmp3/*xdly_0_in_t*/
      voice->tmp3/*xdly_0_in_t*/ = voice->var_out__lfo1;
      
      // ---- mod="xdly" input "fb" seq 1/1
      
      // -- mod="$m_fb" dstVar=voice->tmp6/*xdly_0_in_fb*/
      voice->tmp6/*xdly_0_in_fb*/ = voice->mod_fb_cur;
      
      // ---- mod="xdly" input "wet" seq 1/1
      
      // -- mod="$m_wet" dstVar=voice->tmp14/*xdly_0_in_wet*/
      voice->tmp14/*xdly_0_in_wet*/ = voice->mod_wet_cur;
      voice->tmp2/*seq*/ = voice->xdly_0.process(voice->tmp2/*seq*/, voice->tmp3/*xdly_0_in_t*/, voice->tmp6/*xdly_0_in_fb*/, voice->tmp14/*xdly_0_in_wet*/);
      
      // -- mod="tri" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      
      // ---- mod="tri" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp14/*tri_freq*/
      voice->tmp14/*tri_freq*/ = 0.0f;
      voice->tmp6/*tri_speed*/ = voice->note_speed_cur * voice->tmp14/*tri_freq*/;
      
      // ---- mod="tri" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ = voice->mod_lfophase_cur;
      voice->tmp14/*tri_tmp*/ = ((voice->tmp24_tri_phase + voice->tmp25/*phase*/));
      voice->tmp14/*tri_tmp*/ = ffrac_s(voice->tmp14/*tri_tmp*/);
      voice->tmp3/*seq*/ = (voice->tmp14/*tri_tmp*/ < 0.5f) ? (-1.0f + voice->tmp14/*tri_tmp*/ * 4.0f) : (1.0f - (voice->tmp14/*tri_tmp*/ - 0.5f)*4);
      
      // -- mod="fma" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ = (voice->tmp3/*seq*/ * 0.5f) + 0.5f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="pluginarrayparamfield" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->eff_array_p_dly_lvl[0/*dly1*/];
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      out += voice->tmp2/*seq*/;
      
      // -- mod="pluginarrayparamfield" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->eff_array_p_flt[1/*dly2*/];
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 2.0f) + -1.0f;
      
      // -- mod="sto v_t" dstVar=voice->tmp2/*seq*/
      voice->var_v_t = voice->tmp2/*seq*/;
      
      // -- mod="cmp" dstVar=voice->tmp2/*seq*/
      if(voice->tmp2/*seq*/ < 0.0f)
      {
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         
         // -- mod="1" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ += 1.0f;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp26_svf_lp = voice->tmp26_svf_lp + (voice->tmp28_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp27_svf_hp = voice->tmp2/*seq*/ - voice->tmp26_svf_lp - (voice->tmp28_svf_bp * 1.0f);
         voice->tmp28_svf_bp = voice->tmp28_svf_bp + (voice->tmp27_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp26_svf_lp;
      }
      else
      {
         
         // ---- mod="cmp" input "else" seq 1/1
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp29_svf_lp = voice->tmp29_svf_lp + (voice->tmp31_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp30_svf_hp = voice->tmp2/*seq*/ - voice->tmp29_svf_lp - (voice->tmp31_svf_bp * 1.0f);
         voice->tmp31_svf_bp = voice->tmp31_svf_bp + (voice->tmp30_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp30_svf_hp;
      }
      
      // -- mod="xdly" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="xdly" input "t" seq 1/1
      
      // -- mod="$out__lfo2" dstVar=voice->tmp3/*xdly_1_in_t*/
      voice->tmp3/*xdly_1_in_t*/ = voice->var_out__lfo2;
      
      // ---- mod="xdly" input "fb" seq 1/1
      
      // -- mod="$m_fb" dstVar=voice->tmp6/*xdly_1_in_fb*/
      voice->tmp6/*xdly_1_in_fb*/ = voice->mod_fb_cur;
      
      // ---- mod="xdly" input "wet" seq 1/1
      
      // -- mod="$m_wet" dstVar=voice->tmp14/*xdly_1_in_wet*/
      voice->tmp14/*xdly_1_in_wet*/ = voice->mod_wet_cur;
      voice->tmp2/*seq*/ = voice->xdly_1.process(voice->tmp2/*seq*/, voice->tmp3/*xdly_1_in_t*/, voice->tmp6/*xdly_1_in_fb*/, voice->tmp14/*xdly_1_in_wet*/);
      
      // -- mod="tri" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      
      // ---- mod="tri" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp14/*tri_freq*/
      voice->tmp14/*tri_freq*/ = 0.0f;
      voice->tmp6/*tri_speed*/ = voice->note_speed_cur * voice->tmp14/*tri_freq*/;
      
      // ---- mod="tri" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ = voice->mod_lfophase_cur;
      
      // -- mod="0.25" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ += 0.25f;
      
      // -- mod="frc" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ = ffrac_s(voice->tmp25/*phase*/);
      voice->tmp14/*tri_tmp*/ = ((voice->tmp32_tri_phase + voice->tmp25/*phase*/));
      voice->tmp14/*tri_tmp*/ = ffrac_s(voice->tmp14/*tri_tmp*/);
      voice->tmp3/*seq*/ = (voice->tmp14/*tri_tmp*/ < 0.5f) ? (-1.0f + voice->tmp14/*tri_tmp*/ * 4.0f) : (1.0f - (voice->tmp14/*tri_tmp*/ - 0.5f)*4);
      
      // -- mod="fma" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ = (voice->tmp3/*seq*/ * 0.5f) + 0.5f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="pluginarrayparamfield" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->eff_array_p_dly_lvl[1/*dly2*/];
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      out += voice->tmp2/*seq*/;
      
      // -- mod="pluginarrayparamfield" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->eff_array_p_flt[2/*dly3*/];
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 2.0f) + -1.0f;
      
      // -- mod="sto v_t" dstVar=voice->tmp2/*seq*/
      voice->var_v_t = voice->tmp2/*seq*/;
      
      // -- mod="cmp" dstVar=voice->tmp2/*seq*/
      if(voice->tmp2/*seq*/ < 0.0f)
      {
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         
         // -- mod="1" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ += 1.0f;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp33_svf_lp = voice->tmp33_svf_lp + (voice->tmp35_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp34_svf_hp = voice->tmp2/*seq*/ - voice->tmp33_svf_lp - (voice->tmp35_svf_bp * 1.0f);
         voice->tmp35_svf_bp = voice->tmp35_svf_bp + (voice->tmp34_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp33_svf_lp;
      }
      else
      {
         
         // ---- mod="cmp" input "else" seq 1/1
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp36_svf_lp = voice->tmp36_svf_lp + (voice->tmp38_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp37_svf_hp = voice->tmp2/*seq*/ - voice->tmp36_svf_lp - (voice->tmp38_svf_bp * 1.0f);
         voice->tmp38_svf_bp = voice->tmp38_svf_bp + (voice->tmp37_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp37_svf_hp;
      }
      
      // -- mod="xdly" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="xdly" input "t" seq 1/1
      
      // -- mod="$out__lfo3" dstVar=voice->tmp3/*xdly_2_in_t*/
      voice->tmp3/*xdly_2_in_t*/ = voice->var_out__lfo3;
      
      // ---- mod="xdly" input "fb" seq 1/1
      
      // -- mod="$m_fb" dstVar=voice->tmp6/*xdly_2_in_fb*/
      voice->tmp6/*xdly_2_in_fb*/ = voice->mod_fb_cur;
      
      // ---- mod="xdly" input "wet" seq 1/1
      
      // -- mod="$m_wet" dstVar=voice->tmp14/*xdly_2_in_wet*/
      voice->tmp14/*xdly_2_in_wet*/ = voice->mod_wet_cur;
      voice->tmp2/*seq*/ = voice->xdly_2.process(voice->tmp2/*seq*/, voice->tmp3/*xdly_2_in_t*/, voice->tmp6/*xdly_2_in_fb*/, voice->tmp14/*xdly_2_in_wet*/);
      
      // -- mod="tri" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      
      // ---- mod="tri" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp14/*tri_freq*/
      voice->tmp14/*tri_freq*/ = 0.0f;
      voice->tmp6/*tri_speed*/ = voice->note_speed_cur * voice->tmp14/*tri_freq*/;
      
      // ---- mod="tri" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ = voice->mod_lfophase_cur;
      
      // -- mod="0.5" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ += 0.5f;
      
      // -- mod="frc" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ = ffrac_s(voice->tmp25/*phase*/);
      voice->tmp14/*tri_tmp*/ = ((voice->tmp39_tri_phase + voice->tmp25/*phase*/));
      voice->tmp14/*tri_tmp*/ = ffrac_s(voice->tmp14/*tri_tmp*/);
      voice->tmp3/*seq*/ = (voice->tmp14/*tri_tmp*/ < 0.5f) ? (-1.0f + voice->tmp14/*tri_tmp*/ * 4.0f) : (1.0f - (voice->tmp14/*tri_tmp*/ - 0.5f)*4);
      
      // -- mod="fma" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ = (voice->tmp3/*seq*/ * 0.5f) + 0.5f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="pluginarrayparamfield" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->eff_array_p_dly_lvl[2/*dly3*/];
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      out += voice->tmp2/*seq*/;
      
      // -- mod="pluginarrayparamfield" dstVar=out
      voice->tmp2/*seq*/ = out;
      voice->tmp2/*seq*/ = voice->eff_array_p_flt[3/*dly4*/];
      
      // -- mod="fma" dstVar=voice->tmp2/*seq*/
      voice->tmp2/*seq*/ = (voice->tmp2/*seq*/ * 2.0f) + -1.0f;
      
      // -- mod="sto v_t" dstVar=voice->tmp2/*seq*/
      voice->var_v_t = voice->tmp2/*seq*/;
      
      // -- mod="cmp" dstVar=voice->tmp2/*seq*/
      if(voice->tmp2/*seq*/ < 0.0f)
      {
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         
         // -- mod="1" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ += 1.0f;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp40_svf_lp = voice->tmp40_svf_lp + (voice->tmp42_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp41_svf_hp = voice->tmp2/*seq*/ - voice->tmp40_svf_lp - (voice->tmp42_svf_bp * 1.0f);
         voice->tmp42_svf_bp = voice->tmp42_svf_bp + (voice->tmp41_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp40_svf_lp;
      }
      else
      {
         
         // ---- mod="cmp" input "else" seq 1/1
         
         // -- mod="$out__out" dstVar=voice->tmp2/*seq*/
         voice->tmp2/*seq*/ = voice->var_out__out;
         
         // -- mod="svf" dstVar=voice->tmp2/*seq*/
         
         // ---- mod="svf" input "freq" seq 1/1
         
         // -- mod="$v_t" dstVar=voice->tmp3/*addsr_freq*/
         voice->tmp3/*addsr_freq*/ = voice->var_v_t;
         voice->tmp3/*addsr_freq*/ *= voice->sr_factor;
         voice->tmp43_svf_lp = voice->tmp43_svf_lp + (voice->tmp45_svf_bp * voice->tmp3/*addsr_freq*/);
         voice->tmp44_svf_hp = voice->tmp2/*seq*/ - voice->tmp43_svf_lp - (voice->tmp45_svf_bp * 1.0f);
         voice->tmp45_svf_bp = voice->tmp45_svf_bp + (voice->tmp44_svf_hp * voice->tmp3/*addsr_freq*/);
         voice->tmp2/*seq*/ = voice->tmp44_svf_hp;
      }
      
      // -- mod="xdly" dstVar=voice->tmp2/*seq*/
      
      // ---- mod="xdly" input "t" seq 1/1
      
      // -- mod="$out__lfo4" dstVar=voice->tmp3/*xdly_3_in_t*/
      voice->tmp3/*xdly_3_in_t*/ = voice->var_out__lfo4;
      
      // ---- mod="xdly" input "fb" seq 1/1
      
      // -- mod="$m_fb" dstVar=voice->tmp6/*xdly_3_in_fb*/
      voice->tmp6/*xdly_3_in_fb*/ = voice->mod_fb_cur;
      
      // ---- mod="xdly" input "wet" seq 1/1
      
      // -- mod="$m_wet" dstVar=voice->tmp14/*xdly_3_in_wet*/
      voice->tmp14/*xdly_3_in_wet*/ = voice->mod_wet_cur;
      voice->tmp2/*seq*/ = voice->xdly_3.process(voice->tmp2/*seq*/, voice->tmp3/*xdly_3_in_t*/, voice->tmp6/*xdly_3_in_fb*/, voice->tmp14/*xdly_3_in_wet*/);
      
      // -- mod="tri" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      
      // ---- mod="tri" input "freq" seq 1/1
      
      // -- mod="0" dstVar=voice->tmp14/*tri_freq*/
      voice->tmp14/*tri_freq*/ = 0.0f;
      voice->tmp6/*tri_speed*/ = voice->note_speed_cur * voice->tmp14/*tri_freq*/;
      
      // ---- mod="tri" input "phase" seq 1/1
      
      // -- mod="$m_lfophase" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ = voice->mod_lfophase_cur;
      
      // -- mod="0.75" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ += 0.75f;
      
      // -- mod="frc" dstVar=voice->tmp25/*phase*/
      voice->tmp25/*phase*/ = ffrac_s(voice->tmp25/*phase*/);
      voice->tmp14/*tri_tmp*/ = ((voice->tmp46_tri_phase + voice->tmp25/*phase*/));
      voice->tmp14/*tri_tmp*/ = ffrac_s(voice->tmp14/*tri_tmp*/);
      voice->tmp3/*seq*/ = (voice->tmp14/*tri_tmp*/ < 0.5f) ? (-1.0f + voice->tmp14/*tri_tmp*/ * 4.0f) : (1.0f - (voice->tmp14/*tri_tmp*/ - 0.5f)*4);
      
      // -- mod="fma" dstVar=voice->tmp3/*seq*/
      voice->tmp3/*seq*/ = (voice->tmp3/*seq*/ * 0.5f) + 0.5f;
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      
      // -- mod="pluginarrayparamfield" dstVar=voice->tmp2/*seq*/
      voice->tmp3/*seq*/ = voice->tmp2/*seq*/;
      voice->tmp3/*seq*/ = voice->eff_array_p_dly_lvl[3/*dly4*/];
      voice->tmp2/*seq*/ *= voice->tmp3/*seq*/;
      out += voice->tmp2/*seq*/;
      
      // -- mod="sto v_last" dstVar=out
      voice->var_v_last = out;
      
      // -- mod="ipl" dstVar=out
      voice->tmp2/*a*/ = out;
      
      // ---- mod="ipl" input "a" seq 1/1
      
      // -- mod="$out__outdry" dstVar=voice->tmp2/*a*/
      voice->tmp2/*a*/ = voice->var_out__outdry;
      voice->tmp3/*t*/ = out;
      
      // ---- mod="ipl" input "t" seq 1/1
      
      // -- mod="$m_wet2" dstVar=voice->tmp3/*t*/
      voice->tmp3/*t*/ = voice->mod_wet2_cur;
      out = voice->tmp2/*a*/ + (out - voice->tmp2/*a*/) * voice->tmp3/*t*/;

      /* end calc */

#ifdef OVERSAMPLE_FACTOR
#ifdef STEREO
         outOSL += outL;
         outOSR += outR;
#else
         outOS += out;
#endif // STEREO
#endif // OVERSAMPLE_FACTOR
         voice->note_speed_cur += voice->note_speed_inc;
         voice->note_cur       += voice->note_inc;
         voice->mod_t_cur          += voice->mod_t_inc;
         voice->mod_fb_cur         += voice->mod_fb_inc;
         voice->mod_wet_cur        += voice->mod_wet_inc;
         voice->mod_lfo_amt_cur    += voice->mod_lfo_amt_inc;
         voice->mod_fb2_cur        += voice->mod_fb2_inc;
         voice->mod_wet2_cur       += voice->mod_wet2_inc;
         voice->mod_flt_cur        += voice->mod_flt_inc;
      }
#ifdef OVERSAMPLE_FACTOR
      // Apply lowpass filter before downsampling
      //   (note) normalized Fc = F/Fs = 0.442947 / sqrt(oversample_factor^2 - 1)
#ifdef STEREO
      outL = outOSL * (1.0f / OVERSAMPLE_FACTOR);
      outR = outOSR * (1.0f / OVERSAMPLE_FACTOR);
#else
      out = outOS * (1.0f / OVERSAMPLE_FACTOR);
#endif // STEREO
#endif // OVERSAMPLE_FACTOR
#ifdef STEREO
      outL = Dstplugin_fix_denorm_32(outL);
      outR = Dstplugin_fix_denorm_32(outR);
#else
      out = Dstplugin_fix_denorm_32(out);
#endif // STEREO
#ifdef STEREO
      _samplesOut[k]      = outL;
      _samplesOut[k + 1u] = outR;
#else
      _samplesOut[k]      = out;
      _samplesOut[k + 1u] = out;
#endif // STEREO

      // Next frame
      k += 2u;
#ifdef STEREO
      j += 2u;
#else
      j += jStep;
#endif // STEREO
   } /* loop numFrames */
}

static st_plugin_shared_t *ST_PLUGIN_API loc_shared_new(st_plugin_info_t *_info) {
   test_xdly_7_shared_t *ret = (test_xdly_7_shared_t *)malloc(sizeof(test_xdly_7_shared_t));
   if(NULL != ret)
   {
      memset((void*)ret, 0, sizeof(*ret));
      ret->base.info  = _info;
      memcpy((void*)ret->params, (void*)loc_param_resets, NUM_PARAMS * sizeof(float));
         ret->forced_varidx_p_dly_lvl = -1;
         ret->forced_varidx_p_flt = -1;
   }
   return &ret->base;
}

static void ST_PLUGIN_API loc_shared_delete(st_plugin_shared_t *_shared) {
   free((void*)_shared);
}

static st_plugin_voice_t *ST_PLUGIN_API loc_voice_new(st_plugin_info_t *_info, unsigned int _voiceIdx) {
   test_xdly_7_voice_t *voice = (test_xdly_7_voice_t *)malloc(sizeof(test_xdly_7_voice_t));
   if(NULL != voice)
   {
      memset((void*)voice, 0, sizeof(*voice));
      voice->base.info = _info;
   // xdly_0 voice_new() test code line
   // xdly_1 voice_new() test code line
   // xdly_2 voice_new() test code line
   // xdly_3 voice_new() test code line
      voice->tmp8_lfsr_state = 25985 * (_voiceIdx + 1u);
   }
   return &voice->base;
}

static void ST_PLUGIN_API loc_voice_delete(st_plugin_voice_t *_voice) {
   ST_PLUGIN_VOICE_CAST(test_xdly_7_voice_t);

   free((void*)_voice);
   // xdly_0 voice_delete() test code line
   // xdly_1 voice_delete() test code line
   // xdly_2 voice_delete() test code line
   // xdly_3 voice_delete() test code line
   }

static void ST_PLUGIN_API loc_plugin_exit(st_plugin_info_t *_info) {
   free((void*)_info);
}

#ifdef USE_CYCLE_SINE_TBL
static void loc_calc_sine_tbl(void) {
#define QCOS_BITS 16
#define QCOS_ONE  (1 << QCOS_BITS)
#define QCOS_MASK (QCOS_ONE - 1)
   // (note) same as in TSR "C" implementation
   float *qcos = cycle_sine_tbl_f + 4096; // quarter cos tbl

   // calc quarter cos tbl
   int k = 0;
   for(int a = 0; a < (QCOS_ONE/4); a += (QCOS_ONE/16384)/*4*/)  // 4096 elements
   {
      int x = a - ((int)(QCOS_ONE * 0.25 + 0.5)) + ((a + ((int)(QCOS_ONE * 0.25 + 0.5)))&~QCOS_MASK);
      x = ((x * ((x<0?-x:x) - ((int)(QCOS_ONE * 0.5 + 0.5)))) >> QCOS_BITS) << 4;
      x += (((((int)(QCOS_ONE * 0.225 + 0.5)) * x) >> QCOS_BITS) * ((x<0?-x:x) - QCOS_ONE)) >> QCOS_BITS;
      qcos[k++] = x / float(QCOS_ONE);
   }

   // 0..90deg (rev qtbl)
   int j = 4096;
   k = 0;
   loop(4096)
      cycle_sine_tbl_f[k++] = qcos[--j];

   // 90..180deg = cos tbl
   k += 4096;

   // 180..360deg (y-flip first half of tbl)
   j = 0;
   loop(8192)
      cycle_sine_tbl_f[k++] = -cycle_sine_tbl_f[j++];

#ifdef USE_CYCLE_SINE_TBL_I
   loop(16384)
      cycle_sine_tbl_i[i] = (short)(cycle_sine_tbl_f[i] * 2048.0f/*FX_ONE*/);
#endif // USE_CYCLE_SINE_TBL_I
}
#endif // USE_CYCLE_SINE_TBL

#ifdef USE_CYCLE_HSE_TBL
#endif // USE_CYCLE_HSE_TBL

extern "C" {
st_plugin_info_t *test_xdly_7_init(void) {
   test_xdly_7_info_t *ret = (test_xdly_7_info_t *)malloc(sizeof(test_xdly_7_info_t));

   if(NULL != ret)
   {
      memset(ret, 0, sizeof(*ret));

      ret->base.api_version = ST_PLUGIN_API_VERSION;
      ret->base.id          = "test_xdly_7_0x62b82d42";  // unique id. don't change this in future builds.
      ret->base.author      = "";
      ret->base.name        = "test_xdly_7";
      ret->base.short_name  = "test_xdly_7";
      ret->base.flags       = ST_PLUGIN_FLAG_OSC;
      ret->base.category    = ST_PLUGIN_CAT_UNKNOWN;
      ret->base.num_params  = NUM_PARAMS;
      ret->base.num_mods    = NUM_MODS;

      ret->base.shared_new                          = &loc_shared_new;
      ret->base.shared_delete                       = &loc_shared_delete;
      ret->base.voice_new                           = &loc_voice_new;
      ret->base.voice_delete                        = &loc_voice_delete;
#ifndef CYCLE_SKIP_UI
      ret->base.get_param_name                      = &loc_get_param_name;
      ret->base.get_param_group_name                = &loc_get_param_group_name;
      ret->base.get_param_group_idx                 = &loc_get_param_group_idx;
      ret->base.get_param_section_name              = &loc_get_param_section_name;
      ret->base.get_param_section_idx               = &loc_get_param_section_idx;
      ret->base.get_param_reset                     = &loc_get_param_reset;
      ret->base.query_dynamic_param_preset_values   = &loc_query_dynamic_param_preset_values;
      ret->base.query_dynamic_param_preset_name     = &loc_query_dynamic_param_preset_name;
      ret->base.get_array_param_size                = &loc_get_array_param_size;
      ret->base.get_array_param_num_variations      = &loc_get_array_param_num_variations;
      ret->base.get_array_param_variation_ptr       = &loc_get_array_param_variation_ptr;
      ret->base.set_array_param_edit_variation_idx  = &loc_set_array_param_edit_variation_idx;
      ret->base.get_array_param_element_name        = &loc_get_array_param_element_name;
      ret->base.get_array_param_element_value_range = &loc_get_array_param_element_value_range;
      ret->base.get_array_param_element_reset       = &loc_get_array_param_element_reset;
      ret->base.update_lut                          = &loc_update_lut;
#endif // CYCLE_SKIP_UI
      ret->base.get_param_value                     = &loc_get_param_value;
      ret->base.set_param_value                     = &loc_set_param_value;
#ifndef CYCLE_SKIP_UI
      ret->base.get_mod_name                        = &loc_get_mod_name;
#endif // CYCLE_SKIP_UI
      ret->base.set_sample_rate                     = &loc_set_sample_rate;
      ret->base.set_bpm                             = &loc_set_bpm;
      ret->base.note_on                             = &loc_note_on;
      ret->base.set_mod_value                       = &loc_set_mod_value;
      ret->base.prepare_block                       = &loc_prepare_block;
      ret->base.process_replace                     = &loc_process_replace;
      ret->base.plugin_exit                         = &loc_plugin_exit;

#ifdef USE_CYCLE_SINE_TBL
      loc_calc_sine_tbl();
#endif // USE_CYCLE_SINE_TBL
   }

   return &ret->base;
}

#ifndef STFX_SKIP_MAIN_INIT
ST_PLUGIN_APICALL st_plugin_info_t *ST_PLUGIN_API st_plugin_init(unsigned int _pluginIdx) {
   switch(_pluginIdx)
   {
      case 0u:
         return test_xdly_7_init();
   }
   return NULL;
}
#endif // STFX_SKIP_MAIN_INIT

} // extern "C"
