include ${TKS_ROOT}/install_macos.mk
include makefile.common

.PHONY: install_rls
install_rls:
	$(TKS) -c synergy && mv synergy.tkx ../synergy/macos_installer_arm64/Synergy_arm64.app/Contents/MacOS/data.tkx
	$(TKS) -c synergy && mv synergy.tkx ../synergy/macos_installer_x86_64/Synergy_x86_64.app/Contents/MacOS/data.tkx
