#
# Makefile for tkspeexdsp plugin on macOS
# 
# (c) 2020-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

LIBSPEEXDSP=speexdsp-SpeexDSP-1.2rc3

PLUGIN=tkspeexdsp

EXTRAFLAGS= -DHAVE_CONFIG_H -I$(LIBSPEEXDSP) -I$(LIBSPEEXDSP)/include

ifeq ($(BUILD_ARM),y)
# EXTRAFLAGS+= -D_USE_NEON
else
EXTRAFLAGS+= -D_USE_SSE -D_USE_SSE2
endif

include make.objects

include ../plugin_macos.mk
