#
# Makefile for tkspeexdsp plugin on Linux / GCC platform
# 
# (c) 2020-2025 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

LIBSPEEXDSP=speexdsp-SpeexDSP-1.2rc3

PLUGIN=tkspeexdsp

EXTRAFLAGS= -DHAVE_CONFIG_H -I$(LIBSPEEXDSP) -I$(LIBSPEEXDSP)/include

ifeq ($(BUILD_ARM),y)
ifneq ($(BUILD_64),y)
EXTRAFLAGS+= -D_USE_NEON
endif
else
EXTRAFLAGS+= -D_USE_SSE -D_USE_SSE2
endif

include make.objects

include ../plugin_linux.mk
