#
# Makefile for tkspeexdsp plugin + Microsoft Visual C++ 2019 ToolKit
# 
# (c) 2020-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

LIBSPEEXDSP=speexdsp-SpeexDSP-1.2rc3

PLUGIN=tkspeexdsp

EXTRAFLAGS= -DWINVER=0x0501 -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DHAVE_CONFIG_H -I$(LIBSPEEXDSP)/win32 -I$(LIBSPEEXDSP)/include
EXTRAFLAGS+= -D_USE_SSE -D_USE_SSE2

include make.objects

include ../plugin_msvc.mk
