
HAVE_VGTESSELATE=y
EXTRAFLAGS+= -DUSE_MINNIE_MIB_SETUP
EXTRAFLAGS+= -DMINNIE_PRINTF=1
EXTRAFLAGS+= -DMINNIE_ALLOC_DEBUG=1
EXTRAFLAGS+= -DMINNIE_SW_RENDER=0
EXTRAFLAGS+= -DMINNIE_EXPORT_VERTEX_16BIT=1
EXTRAFLAGS+= -DTKMINNIE_BUILD
EXTRAFLAGS+= -DSHADERVG_SCRIPT_API
#EXTRAFLAGS+= -DMINNIE_LIB
EXTRAFLAGS+= -DSHADERVG_STENCIL_POLYGONS
#EXTRAFLAGS+= -DSHADERVG_USE_DEFAULT_POINT_14_2
#EXTRAFLAGS+= -DSHADERVG_USE_DEFAULT_LINE_14_2
#EXTRAFLAGS+= -DSHADERVG_USE_DEFAULT_POLYGON_14_2
EXTRAFLAGS+= -DSHADERVG_TEXT
EXTRAFLAGS+= -DSHADERVG_TEXT_BATCH_SIZE=128
EXTRAFLAGS+= -DSHADERVG_UNDERLINE_TEXT_BATCH_SIZE=16
EXTRAFLAGS+= -DSHADERVG_MATRIX_STACK
EXTRAFLAGS+= -DSHADERVG_MATRIX_STACK_SIZE=16

# fixes t-junctions in bevel and miter line strips but increases triangle-count by ~67% (5/3)
EXTRAFLAGS+= -DSHADERVG_HIRES_GEO

# must be defined for OpenGL ES 3.x targets
#EXTRAFLAGS+= -DSHADERVG_GLES

# required on NVidia / not on macOS
EXTRAFLAGS+= -DSHADERVG_UNMAP_SCRATCHVBO_DURING_DRAW

# (note) slower than mapping the scratch buffer
##EXTRAFLAGS+= -DSHADERVG_USE_SCRATCHBUFFERSUBDATA

# redirect VG_tesselator malloc/free to vgtess_malloc/free functions and track memory usage
EXTRAFLAGS += -DVGTESSELATE_MALLOC_DEBUG

ifeq ("$(HAVE_VGTESSELATE)","y")
EXTRAFLAGS += -DHAVE_VGTESSELATE
endif
