#
# Makefile for tkminnie plugin on macOS / Clang platform
#
# (c) 2014-2025 Bastian Spiegel <bs@tkscript.de>
#

PLUGIN=tkminnie

YAC_ROOTPATH=../../
include ../../install_macos.mk

include config_common.mk

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../../plugin_macos.mk

.PHONY: ee
ee::
	$(TKS) app:dog++ -pn $(PLUGIN) -mn $(PLUGIN) ../*.h  >"$(YAC_ROOTPATH)/apidocs/ee/tkminnie.ee"
	$(TKS) app:dog++ -pn ShaderVG -mn ShaderVG ../shadervg/shadervg.h >"$(YAC_ROOTPATH)/apidocs/ee/shadervg.ee"
	$(TKS) app:dog++ -pn ShaderVG_Text -mn ShaderVG_Text ../shadervg/text.h >"$(YAC_ROOTPATH)/apidocs/ee/shadervg_text.ee"
