#
# Makefile for tkminnie plugin on Linux / GCC platform
#
# (c) 2014-2026 Bastian Spiegel <bs@tkscript.de>
#

PLUGIN=tkminnie

include ${TKS_ROOT}/install_linux.mk

include config_common.mk

EXTRAFLAGS+= -DMINNIE_SKIP_DRAWABLE_C_API

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ${TKS_ROOT}/plugin_linux.mk

.PHONY: ee
ee::
	$(TKS) app:dog++ -pn $(PLUGIN) -mn $(PLUGIN) ../*.h  >"${TKS_ROOT}/apidocs/ee/tkminnie.ee"
	$(TKS) app:dog++ -pn ShaderVG -mn ShaderVG ../shadervg/shadervg.h >"${TKS_ROOT}/apidocs/ee/shadervg.ee"
	$(TKS) app:dog++ -pn ShaderVG_Text -mn ShaderVG_Text ../shadervg/text.h >"${TKS_ROOT}/apidocs/ee/shadervg_text.ee"
