EXTRAFLAGS= -DLIBSYNERGY_BUILD
EXTRAFLAGS+= -DYAC_NO_HOST
EXTRAFLAGS+= -DTKSAMPLER_SKIP_ADDITIVE
EXTRAFLAGS+= -DTKSAMPLER_SKIP_LIVEREC
EXTRAFLAGS+= -DSR_STDIO -DHAVE_VSNPRINTF
EXTRAFLAGS+= -DSR_MIX_RATE=48000.0f -DSR_VOLUME=0.94f
EXTRAFLAGS+= -DSR_INFO
#EXTRAFLAGS+= -DSR_INFOV
#EXTRAFLAGS+= -DSR_TRACE
#EXTRAFLAGS+= -DSR_SAVE_WF_DAT
#EXTRAFLAGS+= -DSR_SONGTRACE
#EXTRAFLAGS+= -DSR_REPLAYTRACE
#EXTRAFLAGS+= -DSR_SAVE_SONG_WF_DAT
EXTRAFLAGS+= -DSR_PORTAUDIO
# (note) when SR_PORTAUDIO_DEVIDX is undefined, Pa_GetDefaultOutputDevice() is used instead
#EXTRAFLAGS+= -DSR_PORTAUDIO_DEVIDX=5
EXTRAFLAGS+= -DSR_TRACK_FX
EXTRAFLAGS+= -DSR_VOICE_FX
EXTRAFLAGS+= -DSR_PROFILE
