
# define in parent makefile and include auto-generated <project.mk>
# SR_CUSTOM_MK := y

#
# MIN_FEATURES: 'y'=remove xfade,ext.interpolation modes,anti-aliasing/imaging filters,global LFOs
# FILTERS     : enable basic lpf / bpf / brf / hpf / peq / lsh / hsh
# WAVETABLES  : enable 1d / 2d wavetables
# LFO         : enable LFOs
# MODSEQ      : enable modulation sequencers 1..4
# PLUGINS     : enable voice + track fx
# AUDIO       : enable portaudio output
#
MIN_FEATURES:=y
WAVETABLES  :=y
LFO         :=y
MODSEQ      :=n
FILTERS     :=y
PLUGINS     :=y
PROCEDURAL  :=y
AUDIO       :=y

# -------------------------------------------------------------------------------------------
EXTRAFLAGS+= -DYAC_NO_HOST
EXTRAFLAGS+= -DYAC_CUST_EVENT
EXTRAFLAGS+= -DYAC_CUST_NUMBEROBJECTS
EXTRAFLAGS+= -DYAC_CUST_LISTNODE
EXTRAFLAGS+= -DYAC_CUST_TREENODE
EXTRAFLAGS+= -DYAC_CUST_POINTERARRAY
EXTRAFLAGS+= -DYAC_SKIP_OBJECT_METHODS

EXTRAFLAGS+= -DLIBSYNERGY_BUILD

ifneq ($(SR_CUSTOM_MK),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_TUNING_TABLES

ifneq ($(WAVETABLES),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_WAVETABLE
endif

EXTRAFLAGS+= -DTKSAMPLER_SKIP_FRAGMENT_IPOL
EXTRAFLAGS+= -DTKSAMPLER_SKIP_ADDITIVE
EXTRAFLAGS+= -DTKSAMPLER_SKIP_LIVEREC

ifeq ($(MIN_FEATURES),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_PLAY_XFADE
EXTRAFLAGS+= -DTKSAMPLER_SKIP_IPOL_VSR
EXTRAFLAGS+= -DTKSAMPLER_SKIP_IPOL_LANCZOS
EXTRAFLAGS+= -DTKSAMPLER_SKIP_AA_AI
endif

ifneq ($(FILTERS),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_FILTER
endif

ifeq ($(MIN_FEATURES),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_EXP_MM_OPS
EXTRAFLAGS+= -DTKSAMPLER_SKIP_GLOBAL_REGS
endif

ifneq ($(LFO),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_LFO
EXTRAFLAGS+= -DTKSAMPLER_SKIP_GLOBAL_LFOS
else
  ifeq ($(MIN_FEATURES),y)
  EXTRAFLAGS+= -DTKSAMPLER_SKIP_GLOBAL_LFOS
  endif
endif

ifneq ($(MODSEQ),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_MODSEQ
endif

ifneq ($(PLUGINS),y)
EXTRAFLAGS+= -DTKSAMPLER_SKIP_PLUGINS
else
EXTRAFLAGS+= -DSR_TRACK_SENDS
EXTRAFLAGS+= -DSR_TRACK_FX
EXTRAFLAGS+= -DSR_VOICE_FX
endif

ifeq ($(PROCEDURAL),y)
EXTRAFLAGS+= -DSR_PROCEDURAL
EXTRAFLAGS+= -DSR_PROCEDURAL_TRACKS
endif

endif  # SR_CUSTOM_MK


EXTRAFLAGS+= -DSR_STDIO -DHAVE_VSNPRINTF
EXTRAFLAGS+= -DSR_MIX_RATE=48000.0f -DSR_VOLUME=0.94f
EXTRAFLAGS+= -DSR_INFO
#EXTRAFLAGS+= -DSR_INFOV
#EXTRAFLAGS+= -DSR_TRACE
#EXTRAFLAGS+= -DSR_SAVE_WF_DAT
#EXTRAFLAGS+= -DSR_SONGTRACE
#EXTRAFLAGS+= -DSR_REPLAYTRACE
#EXTRAFLAGS+= -DSR_SAVE_SONG_WF_DAT

ifeq ($(AUDIO),y)
EXTRAFLAGS+= -DSR_PORTAUDIO
# (note) when SR_PORTAUDIO_DEVIDX is undefined, Pa_GetDefaultOutputDevice() is used instead
#EXTRAFLAGS+= -DSR_PORTAUDIO_DEVIDX=5
endif

EXTRAFLAGS+= -DSR_PROFILE
