#
# Makefile for synergy_replay on Windows / VisualC platform
#
# (c) 2023-2026 Bastian Spiegel <bs@tkscript.de>
#

CUSTOM_BIN_TARGET:=y
OPT_SIZE?=y
OPT_LTO=y
DEMO_3  ?=n
DEMO_SMP?=n
AUDIO=n

include ../install_msvc.mk

TARGET=sr_replay

include common_pre.mk
include config_common.mk

#EXTRALIBS+= -lportaudio

PLAF_OBJ=

include make.objects

CLEAN_RULES += clean_sr_replay

include ../build_msvc.mk

.PHONY: bin
bin: $(BIN_RULES) $(ALL_OBJ)
	$(LD) $(LDFLAGS) -OUT:$(TARGET) $(ALL_OBJ) $(EXTRALIBS)
	@echo "Build finished at `date +%H:%M`."
	ls -ld $(TARGET)

.PHONY: listobj
listobj:
	ls -ld $(STFX_OBJ) $(ALL_OBJ)

.PHONY: sz
sz:
	$(RM) sr_replay.gz
	$(m) clean; $(m) RELEASE=y OPT_SIZE=y OPT_LTO=$(OPT_LTO) bin && $(m) listobj && strip sr_replay && ls -ld sr_replay
	gzip -9 sr_replay && ls -ld sr_replay.gz && gunzip sr_replay.gz

.PHONY: clean_sr_replay
clean_sr_replay:
	@echo "cleaning sr_replay"


include makefile.common
