#
# Makefile for synergy_replay on macOS / Clang platform
# 
# (c) 2023-2026 Bastian Spiegel <bs@tkscript.de> 
#

CUSTOM_BIN_TARGET:=y

include ../install_macos.mk

TARGET=sr_replay

include config_common.mk

EXTRALIBS= 

EXTRALIBS+= -lportaudio -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework CoreServices

PLAF_OBJ= 

include make.objects

# void cycle_calc_waveform_demo_2_r_sr(float *_wfAddr)
EXTRAFLAGS+= -Wno-unused-variable
EXTRAFLAGS+= -Wno-unused-function
ALL_OBJ += music/autogen_calc_demo_2-r-sr_float.o

CLEAN_RULES += clean_sr_replay

LDFLAGS += -Wl,-map,sr.map
# -5k:
LDFLAGS+= -Wl,-no_compact_unwind

include ../plugin_macos.mk

.PHONY: bin
bin: $(BIN_RULES) $(ALL_OBJ) 
	$(CPP) -o $(TARGET) $(ALL_OBJ) $(LDFLAGS) $(EXTRALIBS)
ifneq ($(DEBUG),y)
	$(STRIP) "$(TARGET)"
endif
	@echo "Build finished at `date +%H:%M`."
	ls -ld $(TARGET)
ifeq ($(COMP),y)
	upx -9 $(TARGET)
	ls -ld $(TARGET)
endif

.PHONY: listobj
listobj:
	ls -ld $(STFX_OBJ) $(ALL_OBJ)

m = make -f makefile.macos
.PHONY: sz
sz:
	$(RM) sr_replay.gz
	$(m) clean; $(m) RELEASE=y OPT_SIZE=y bin && $(m) listobj && strip sr_replay && ls -ld sr_replay
	size -m sr.o
# /Library/Developer/CommandLineTools/usr/bin/nm: warning: sizes with --print-size for Mach-O files are always zero.
#nm -a --demangle --print-size --size-sort -t d sr.o
	gzip -9 sr_replay && ls -ld sr_replay.gz && gunzip sr_replay.gz

.PHONY: info
info:
	@cp sr_replay debug.exe
	@$(STRIP) debug.exe
	@ls -ld debug.exe
	@rm -f debug.exe.gz
	@gzip -9 debug.exe
	@ls -ld debug.exe.gz

	@cp music/demo_2-r-sr.mid debug.mid
	@ls -ld debug.mid
	@rm -f debug.mid.gz
	@gzip -9 debug.mid
	@ls -ld debug.mid.gz

	@cp music/autogen_demo_2-r-sr.syn debug.syn
	@ls -ld debug.syn
	@rm -f debug.syn.gz
	@gzip -9 debug.syn
	@ls -ld debug.syn.gz

.PHONY: zip
zip:
	zip -r -9 demo_2-r-sr.zip music/*.mid music/*.syn
	@ls -ld demo_2-r-sr.zip

.PHONY: clean_sr_replay
clean_sr_replay:
	@echo "cleaning sr_replay"
