
.PHONY: info
info:
	@cp sr_replay debug.exe
	@$(STRIP) debug.exe
	@ls -ld debug.exe
	@rm -f debug.exe.gz
	@gzip -9 debug.exe
	@ls -ld debug.exe.gz

	@cp music/demo_2-r-sr.mid debug.mid
	@ls -ld debug.mid
	@rm -f debug.mid.gz
	@gzip -9 debug.mid
	@ls -ld debug.mid.gz

	@cp music/autogen_demo_2-r-sr.syn debug.syn
	@ls -ld debug.syn
	@rm -f debug.syn.gz
	@gzip -9 debug.syn
	@ls -ld debug.syn.gz


.PHONY: zip
zip:
	zip -r -9 demo_2-r-sr.zip music/*demo_2*.mid music/*demo_2*.syn
	@ls -ld demo_2-r-sr.zip

	zip -r -9 demo_3_fm-a.zip music/*demo-3*.mid music/*demo_3*.syn
	@ls -ld demo_3_fm-a.zip


.PHONY: cp_demo2
cp_demo2:
	cp ../tks-projects/apps/eureka/autogen_cycle/autogen_demo_2-r-sr.* music/
	cp ../tks-projects/apps/synergy/export.mid music/demo_2-r-sr.mid
	cp ../tks-projects/apps/eureka/autogen_cycle/autogen_calc_demo_2-r-sr_float.c music/


.PHONY: cp_demo3
cp_demo3:
	cp ../tks-projects/apps/eureka/autogen_cycle/autogen_demo_3_fm-a.* music/
	cp ../tks-projects/apps/synergy/export.mid music/demo_3_fm-a.mid
	cp ../tks-projects/apps/eureka/autogen_cycle/autogen_calc_demo_3_fm-a_float.c music/
