#
# Makefile for synergy_replay on Linux / GCC / Clang platform
#
# (c) 2023-2026 Bastian Spiegel <bs@tkscript.de>
#

CUSTOM_BIN_TARGET:=y
OPT_SIZE?=y
OPT_LTO ?=y
DEMO_3  ?=n
DEMO_SMP?=n

include ../install_linux.mk

TARGET=sr_replay

include common_pre.mk
include config_common.mk

EXTRALIBS+= -lportaudio

PLAF_OBJ=

include make.objects

# void cycle_calc_waveform_demo_2_r_sr(float *_wfAddr)
EXTRAFLAGS+= -Wno-unused-variable
EXTRAFLAGS+= -Wno-unused-function

CLEAN_RULES += clean_sr_replay

LDFLAGS+= -Wl,-Map=sr.map

include ../build_linux.mk

.PHONY: bin
bin: $(BIN_RULES) $(ALL_OBJ)
	$(CPP) -o $(TARGET) $(LDFLAGS) $(ALL_OBJ) $(EXTRALIBS)
ifneq ($(DEBUG),y)
	$(STRIP) "$(TARGET)"
endif
	@echo "Build finished at `date +%H:%M`."
	ls -ld $(TARGET)
ifeq ($(COMP),y)
	upx -9 $(TARGET)
	ls -ld $(TARGET)
endif

.PHONY: listobj
listobj:
	ls -ld $(STFX_OBJ) $(ALL_OBJ)

.PHONY: sz
sz:
	$(RM) sr_replay.gz
	$(m) clean; $(m) RELEASE=y OPT_SIZE=y OPT_LTO=$(OPT_LTO) bin && $(m) listobj && strip sr_replay && ls -ld sr_replay
ifneq ($(OPT_LTO),y)
	size --format=SysV sr.o
endif
	gzip -9 sr_replay && ls -ld sr_replay.gz && gunzip sr_replay.gz

.PHONY: clean_sr_replay
clean_sr_replay:
	@echo "cleaning sr_replay"


include makefile.common
