#
# Makefile for synergy_replay on macOS / Clang platform
# 
# (c) 2023-2026 Bastian Spiegel <bs@tkscript.de> 
#

CUSTOM_BIN_TARGET:=y

include ../install_macos.mk

TARGET=sr_test

EXTRAFLAGS= -DLIBSYNERGY_BUILD -DYAC_NO_HOST
EXTRAFLAGS+= -DSR_STDIO -DHAVE_VSNPRINTF
# EXTRAFLAGS+= -DSR_TRACE
#EXTRAFLAGS+= -DSR_SAVE_WF_DAT
# EXTRAFLAGS+= -DSR_SONGTRACE
# EXTRAFLAGS+= -DSR_REPLAYTRACE
#EXTRAFLAGS+= -DSR_SAVE_SONG_WF_DAT
EXTRAFLAGS+= -DSR_PORTAUDIO
# (note) when SR_PORTAUDIO_DEVIDX is undefined, Pa_GetDefaultOutputDevice() is used instead
#EXTRAFLAGS+= -DSR_PORTAUDIO_DEVIDX=5
EXTRAFLAGS+= -DSR_TRACK_FX
EXTRAFLAGS+= -DSR_VOICE_FX
EXTRAFLAGS+= -DSR_PROFILE

EXTRALIBS= 

EXTRALIBS+= -lportaudio -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework CoreServices

PLAF_OBJ= 

EXTRALIBS+= \
	../tksampler/plugins/fx/schroederverb/schroederverb.o \
	../tksampler/plugins/fx/fx_core/amp.o \
	../tksampler/plugins/fx/fx_core/dly_2.o \
	../tksampler/plugins/fx/fx_core/dly_flt_2_mod.o \
	../tksampler/plugins/fx/fx_core/biquad_lpf_1.o \
	../tksampler/plugins/fx/fx_core/biquad_lpf_2.o \
	../tksampler/plugins/fx/fx_core/biquad_hpf_1.o \
	../tksampler/plugins/fx/fx_core/biquad_hpf_2.o \
	../tksampler/plugins/fx/fx_core/biquad_lsh_1.o \
	../tksampler/plugins/fx/fx_core/biquad_lsh_2.o \
	../tksampler/plugins/fx/fx_core/biquad_hsh_1.o \
	../tksampler/plugins/fx/fx_core/biquad_hsh_2.o \
	../tksampler/plugins/fx/fx_core/biquad.o \
	../tksampler/plugins/fx/fx_core/eq3.o \
	../tksampler/plugins/fx/fx_core/gain.o \
	../tksampler/plugins/fx/fx_core/resample_linear.o \
	../tksampler/plugins/fx/fx_core/ws_tanh_asym.o \
	../tksampler/plugins/fx/fx_core/ws_fm.o \
	../tksampler/plugins/fx/valley_plateau/valley_plateau.o \
	../tksampler/plugins/fx/valley_plateau/Plateau/Dattorro.o \
	../tksampler/plugins/fx/valley_plateau/Common/DSP/OnePoleFilters.o \
        ../tksampler/plugins/cycle/cycle_cycle_rms_comp_stereo_1.o \
	../tksampler/plugins/cycle/cycle_chorus_tri_1.o \
	../tksampler/plugins/osc/gm_rng_convolve/gm_rng_convolve.o \
	../tksampler/plugins/osc/befaco_noise_plethora/np_svf.o \
	../tksampler/plugins/osc/fm_stack_v2/loresh.o \
	../tksampler/plugins/osc/fm_stack_v2/medres.o \
	../tksampler/plugins/osc/fm_stack_v2/medresh.o \
	../tksampler/plugins/osc/fm_stack_v2/hires.o \
	../tksampler/plugins/osc/fm_stack_v2/main.o \
	../tksampler/plugins/osc/fm_stack_v2/curves.o

include make.objects

CLEAN_RULES += clean_sr_test

include ../plugin_macos.mk

.PHONY: bin
bin: $(BIN_RULES) $(ALL_OBJ) 
	$(CPP) -o $(TARGET) $(ALL_OBJ) $(LDFLAGS) $(EXTRALIBS)
ifneq ($(DEBUG),y)
	$(STRIP) "$(TARGET)"
endif
	@echo "Build finished at `date +%H:%M`."
	ls -ld $(TARGET)
ifeq ($(COMP),y)
	upx -9 $(TARGET)
	ls -ld $(TARGET)
endif

.PHONY: info
info:
	@cp sr_test debug.exe
	@ls -ld debug.exe
	@rm -f debug.exe.gz
	@gzip -9 debug.exe
	@ls -ld debug.exe.gz

#	@cp ../tks-projects/flux/export.mid debug.mid
	@cp ../tks-projects/flux/mb_rng_convolve_epiano-27Apr2022b.mid debug.mid
	@ls -ld debug.mid
	@rm -f debug.mid.gz
	@gzip -9 debug.mid
	@ls -ld debug.mid.gz

#	@cp ../tks-projects/eureka/autogen_cycle/autogen_debug2.syn debug.syn
	@cp ../tks-projects/eureka/autogen_cycle/autogen_mb_rng_convolve_epiano-27Apr2022b.syn debug.syn
	@ls -ld debug.syn
	@rm -f debug.syn.gz
	@gzip -9 debug.syn
	@ls -ld debug.syn.gz

#	@echo " (note) most of the samples in the debug.syn file are unused (just for testing the compression)"

.PHONY: clean_sr_test
clean_sr_test:
	@echo "cleaning sr_test"

.PHONY: calc
calc:
	@cp ../tks-projects/eureka/autogen_cycle/autogen_cycle_float_test-16Apr2023a.syn t.syn
	@ls -ld t.syn
	@gzip -9 t.syn
	@ls -ld t.syn.gz
	@rm -f t.syn.gz

	gcc -c ../tks-projects/eureka/autogen_cycle/autogen_calc_cycle_float_test-16Apr2023a_float.c -o t.o
	@ls -ld t.o
	@gzip -9 t.o
	@ls -ld t.o.gz
	@rm -f t.o.gz

