#
# Makefile for synergy_replay on macOS / Clang platform
# 
# (c) 2023-2026 Bastian Spiegel <bs@tkscript.de> 
#

CUSTOM_BIN_TARGET:=y
OPT_SIZE?=y
OPT_LTO?=y
DEMO_3?=n

include ../install_macos.mk

# "strip -x" => "strip"
STRIP=strip

TARGET=sr_replay

ifeq ($(DEMO_3),y)
include music/autogen_demo_3_fm-a.mk
else
include music/autogen_demo_2-r-sr.mk
endif

include config_common.mk

ifeq ($(DEMO_3),y)
EXTRAFLAGS+= -DDEMO_3
endif

EXTRALIBS= 

EXTRALIBS+= -lportaudio 
#-framework AudioToolbox -framework AudioUnit -framework CoreAudio -framework CoreServices

PLAF_OBJ= 

include make.objects

EXTRAFLAGS+= -Wno-unused-variable
EXTRAFLAGS+= -Wno-unused-function
#EXTRAFLAGS+= -fno-common
#EXTRAFLAGS+= -ffunction-sections -fdata-sections

ifeq ($(DEMO_3),y)
ALL_OBJ += music/autogen_calc_demo_3_fm-a_float.o
else
ALL_OBJ += music/autogen_calc_demo_2-r-sr_float.o
endif

CLEAN_RULES += clean_sr_replay

LDFLAGS+= -Wl,-map,sr.map
# -5k:
LDFLAGS+= -Wl,-no_compact_unwind
LDFLAGS+= -dead_strip

include ../plugin_macos.mk

.PHONY: bin
bin: $(BIN_RULES) $(ALL_OBJ) 
	$(CPP) -o $(TARGET) $(ALL_OBJ) $(LDFLAGS) $(EXTRALIBS)
ifneq ($(DEBUG),y)
	$(STRIP) "$(TARGET)"
	strip $(TARGET)
endif
	@echo "Build finished at `date +%H:%M`."
	ls -ld $(TARGET)
ifeq ($(COMP),y)
	upx -9 $(TARGET)
	ls -ld $(TARGET)
endif

.PHONY: listobj
listobj:
	ls -ld $(STFX_OBJ) $(ALL_OBJ)

m = make -f makefile.macos
.PHONY: sz
sz:
	$(RM) sr_replay.gz
	$(m) clean; $(m) RELEASE=y OPT_SIZE=y OPT_LTO=$(OPT_LTO) bin && $(m) listobj && strip sr_replay && ls -ld sr_replay
ifneq ($(OPT_LTO),y)
	size -m sr.o
endif
# /Library/Developer/CommandLineTools/usr/bin/nm: warning: sizes with --print-size for Mach-O files are always zero.
#nm -a --demangle --print-size --size-sort -t d sr.o
	gzip -9 sr_replay && ls -ld sr_replay.gz && gunzip sr_replay.gz

.PHONY: info
info:
	@cp sr_replay debug.exe
	@$(STRIP) debug.exe
	@ls -ld debug.exe
	@rm -f debug.exe.gz
	@gzip -9 debug.exe
	@ls -ld debug.exe.gz

	@cp music/demo_2-r-sr.mid debug.mid
	@ls -ld debug.mid
	@rm -f debug.mid.gz
	@gzip -9 debug.mid
	@ls -ld debug.mid.gz

	@cp music/autogen_demo_2-r-sr.syn debug.syn
	@ls -ld debug.syn
	@rm -f debug.syn.gz
	@gzip -9 debug.syn
	@ls -ld debug.syn.gz

.PHONY: zip
zip:
	zip -r -9 demo_2-r-sr.zip music/*demo_2*.mid music/*demo_2*.syn
	@ls -ld demo_2-r-sr.zip

	zip -r -9 demo_3_fm-a.zip music/*demo-3*.mid music/*demo_3*.syn
	@ls -ld demo_3_fm-a.zip

.PHONY: clean_sr_replay
clean_sr_replay:
	@echo "cleaning sr_replay"

.PHONY: plugins
plugins:
	(cd ../tksampler ; make -f makefile.macos -j $(NUMJOBS) clean)
	(cd ../tksampler/plugins ; make -f makefile.macos -j $(NUMJOBS) OPT_SIZE=$(OPT_SIZE) OPT_LTO=$(OPT_LTO) STFX_SKIP_MAIN_INIT=1 bin)

.PHONY: cp_demo3
cp_demo3:
	cp ../tks-projects/apps/eureka/autogen_cycle/autogen_demo_3_fm-a.* music/
	cp ../tks-projects/apps/synergy/export.mid music/demo_3_fm-a.mid
	cp ../tks-projects/apps/eureka/autogen_cycle/autogen_calc_demo_3_fm-a_float.c music/
