#
# Makefile for polyraster plugin on macOS / Clang platform
# 
# (c) 2003-2026 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=polyraster

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../build_macos.mk
