#
# Makefile for poly_raster plugin on Linux / GCC / Clang platform
# 
# (c) 2009-2026 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=polyraster

EXTRAFLAGS= 

EXTRALIBS= 

#PLAF_OBJ= 

include make.objects

#ALL_OBJ += $(PLAF_OBJ)

#include makefile.common

include ../build_linux.mk
