#
# Makefile for polyraster plugin + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
# (c) 2003-2025 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=polyraster

EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
