#
# Makefile for tkvst2_stub plugin on macOS / Clang platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#

# (note) this is a no-op dummy plugin

include ../install_macos.mk

PLUGIN=tkvst2

EXTRAFLAGS=

EXTRALIBS=

include make.objects

include ../build_macos.mk
