#
# Makefile for tkvst_stub plugin + Microsoft Visual C++ 2003 / 2005 / .. / 2022 ToolKit
# 
# (c) 2010-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkvst2

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
