#
# Makefile for tkvst2_stub plugin on macOS
# 
# (c) 2010-2023 Bastian Spiegel <bs@tkscript.de> 
#

# (note) this is a no-op dummy plugin

include ../install_macos.mk

PLUGIN=tkvst2

EXTRAFLAGS= 

EXTRALIBS=

include make.objects

include ../plugin_macos.mk
