#
# Makefile for tkvst2_stub plugin on Linux / GCC / Clang platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#

# (note) this is a no-op dummy plugin

include ../install_linux.mk

PLUGIN=tkvst2

EXTRAFLAGS=

EXTRALIBS=
EXTRALIBS+= -Wl,--no-undefined

include make.objects

include ../build_linux.mk
