#
# Makefile for tkvst_stub plugin on Windows / Visual C++ platform
#
# (c) 2010-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkvst2

EXTRAFLAGS=

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
