#
# Makefile for tkvst2_stub plugin on Linux / GCC platform
# 
# (c) 2010-2023 Bastian Spiegel <bs@tkscript.de> 
#

# (note) this is a no-op dummy plugin

include ../install_linux.mk

PLUGIN=tkvst2

EXTRAFLAGS= 

EXTRALIBS=
EXTRALIBS+= -Wl,--no-undefined

include make.objects

include ../plugin_linux.mk
