#
# Makefile for tkvst2 plugin + Microsoft Visual C++ 2003
# 
# (c) 2010-2024 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkvst2

#
# Set this to the VST2.x SDK installation directory
#
VSTSDK2_A=f:/dev/vstsdk2.4
VSTSDK2_B=c:/bsp/sources/vstsdk2.4

EXTRAFLAGS= -I"$(VSTSDK2_A)" -I"$(VSTSDK2_B)"

EXTRALIBS= user32.lib gdi32.lib

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
