// ---- ying_vst2.h: auto generated by YInG - the YAC interface generator (Mon, 1/Jul/2024 21:19:08)
extern sUI clid_VST2ParameterProperties;
class VST2ParameterProperties;
extern sUI clid_VST2PinProperties;
class VST2PinProperties;
extern sUI clid_VST2Plugin;
class VST2Plugin;
YAC_APIC void  YAC_CALL __APIC__tkvst2_set_bpm(yacmemptr           );
YAC_APIC void  YAC_CALL __APIC__tkvst2_set_song_pos_ppq(yacmemptr  );
