// ----
// ---- file   : LineStripFlatMiterAA32PatternDecal.h
// ---- author : Bastian Spiegel <bs@tkscript.de>
// ---- legal  : Distributed under terms of the MIT license (https://opensource.org/licenses/MIT)
// ----          Copyright 2026 by bsp
// ----
// ----          Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
// ----          associated documentation files (the "Software"), to deal in the Software without restriction, including
// ----          without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// ----          copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to
// ----          the following conditions:
// ----
// ----          The above copyright notice and this permission notice shall be included in all copies or substantial
// ----          portions of the Software.
// ----
// ----          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// ----          NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// ----          IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// ----          WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// ----          SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ----
// ---- info   : ShaderVG render utilities
// ----
// ----
// ----

class LineStripFlatMiterAA32PatternDecal : public ShaderVG_Shape {

  public:
   // ------------ vertex shader --------------
#ifdef SHADERVG_HIRES_GEO
   const char *vs_src =
      "uniform mat4  u_transform; \n"
      "uniform float u_stroke_w; \n"
      "uniform int   u_last_instance; \n"
      "uniform float u_line_miter_limit; \n"
      "uniform vec2  u_paint_start; \n"
      "uniform vec2  u_paint_ob_size; \n"
      " \n"
      "ATTRIBUTE vec2  a_vertex; \n"
      "ATTRIBUTE vec2  a_vertex_n; \n"
      "ATTRIBUTE vec2  a_vertex_nn; \n"
      " \n"
      "VARYING_OUT vec2  v_vertex_mp; \n"
      "flat VARYING_OUT vec2  v_plane_n; \n"
      "flat VARYING_OUT float v_join; \n"
      "VARYING_OUT vec2  v_paint_uv; \n"
      " \n"
      "void intersect(vec2 _v1s, vec2 _v1e, vec2 _v2s, vec2 _v2e, out vec2 _r) { \n"
      "  vec2 vE = _v1e - _v1s; \n"
      "  vec2 vF = _v2e - _v2s; \n"
      "  vec2 vP = vec2(-vE.y, vE.x); \n"
      "  vec2 vG = _v1s - _v2s; \n"
      "  float h = dot(vF, vP); \n"
      "  h = dot(vG, vP) / h; \n"
      "  _r = vF * h; \n"
      "  _r += _v2s; \n"
#ifdef SHADERVG_DIV_PRECISION_NAN_WORKAROUND
      "  if(isnan(_r.x) || isnan(_r.y)) _r = _v2s; \n"
#endif // SHADERVG_DIV_PRECISION_NAN_WORKAROUND
      "} \n"
      " \n"
      "void main(void) { \n"
      "  vec2 v1 = a_vertex; \n"
      "  vec2 v2 = a_vertex_n; \n"
      "  vec2 v3 = a_vertex_nn; \n"
      " \n"
      "  vec2 v12 = v2 - v1; \n"
      "  vec2 vN = normalize(v12); \n"
      "  vec2 vD = vN * u_stroke_w; \n"
      "  vec2 v1L = vec2(v1.x + vD.y, v1.y - vD.x); \n"
      "  vec2 v2L = vec2(v2.x + vD.y, v2.y - vD.x); \n"
      "  vec2 v1R = vec2(v1.x - vD.y, v1.y + vD.x); \n"
      "  vec2 v2R = vec2(v2.x - vD.y, v2.y + vD.x); \n"
      " \n"
      "  vec2 v23 = v3 - v2; \n"
      "  vec2 vN2 = normalize(v23); \n"
      "  vec2 vD2 = vN2 * u_stroke_w; \n"
      "  vec2 v2L2 = vec2(v2.x + vD2.y, v2.y - vD2.x); \n"
      "  vec2 v3L = vec2(v3.x + vD2.y, v3.y - vD2.x); \n"
      "  vec2 v2R2 = vec2(v2.x - vD2.y, v2.y + vD2.x); \n"
      "  vec2 v3R = vec2(v3.x - vD2.y, v3.y + vD2.x); \n"
      " \n"
      "  float cz = v12.x * v23.y - v12.y * v23.x; \n"
      " \n"
      "  vec2 vMiterOrig; \n"
      "  vec2 vMiter; \n"
      "  vec2 vMiterL; \n"
      "  vec2 vMiterR; \n"
      "  vec2 vTmp; \n"
      "  float h; \n"
      "  float lenMiter; \n"
      "  float lenMiterRel; \n"
      "  if(cz > 0.0) { \n"
      "    intersect(v1L, v2L, v3L, v2L2, vMiterOrig); \n"
      "    vTmp = vMiterOrig - v2; \n"
      "    lenMiter = length(vTmp); \n"
      "    if(lenMiter > u_line_miter_limit) { \n"
      //"      vMiter = normalize(vTmp) * u_line_miter_limit + v2; \n"
      "      lenMiterRel = (u_line_miter_limit / lenMiter); \n"
      "      vMiterL = (vMiterOrig - v2L) * lenMiterRel + v2L; \n"
      "      vMiterR = (vMiterOrig - v2L2) * lenMiterRel + v2L2; \n"
      "    } else { \n"
      "      vMiterL = vMiterOrig; \n"
      "      vMiterR = vMiterOrig; \n"
      "    } \n"
      "  } else { \n"
      "    intersect(v1R, v2R, v3R, v2R2, vMiterOrig); \n"
      "    vTmp = vMiterOrig - v2; \n"
      "    lenMiter = length(vTmp); \n"
      "    if(lenMiter > u_line_miter_limit) { \n"
      "      lenMiterRel = (u_line_miter_limit / lenMiter); \n"
      "      vMiterL = (vMiterOrig - v2R) * lenMiterRel + v2R; \n"
      "      vMiterR = (vMiterOrig - v2R2) * lenMiterRel + v2R2; \n"
      "    } else { \n"
      "      vMiterL = vMiterOrig; \n"
      "      vMiterR = vMiterOrig; \n"
      "    } \n"
      "  } \n"
      "  vec2 v; \n"
      " \n"
      "  float index = float(gl_VertexID); \n"
      " \n"
      "  if(index > 19.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 18.9) { \n"
      "    v = (cz > 0.0) ? v2L2 : v2R2; \n"
      "  } \n"
      "  else if(index > 17.9) { \n"
      "    v = vMiterR; \n"
      "  } \n"
      "  else if(index > 16.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 15.9) { \n"
      "    v = vMiterR; \n"
      "  } \n"
      "  else if(index > 14.9) { \n"
      "    v = vMiterL; \n"
      "  } \n"
      "  else if(index > 13.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 12.9) { \n"
      "    v = vMiterL; \n"
      "  } \n"
      "  else if(index > 11.9) { \n"
      "    v = (cz > 0.0) ? v2L : v2R; \n"
      "  } \n"
      "  else if(index > 10.9) { \n"
      "    v = v1R; \n"
      "  } \n"
      "  else if(index > 9.9) { \n"
      "    v = v2R; \n"
      "  } \n"
      "  else if(index > 8.9) { \n"
      "    v = v1; \n"
      "  } \n"
      "  else if(index > 7.9) { \n"
      "    v = v2R; \n"
      "  } \n"
      "  else if(index > 6.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 5.9) { \n"
      "    v = v1; \n"
      "  } \n"
      "  else if(index > 4.9) { \n"
      "    v = v1; \n"
      "  } \n"
      "  else if(index > 3.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 2.9) { \n"
      "    v = v1L; \n"
      "  } \n"
      "  else if(index > 1.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 0.9) { \n"
      "    v = v2L; \n"
      "  } \n"
      "  else { \n"
      "    v = v1L; \n"
      "  } \n"
      " \n"
      "  if(gl_InstanceID == u_last_instance && index > 11.9) { \n"
      "    gl_Position = vec4(0,0,0,1); \n"  // skip last line joint
      "  } else { \n"
      "    gl_Position = u_transform * vec4(v,0,1); \n"
      "    if(index > 17.9) { \n"
      "      v_vertex_mp = v - v2; \n"
      "      v_plane_n   = vec2(vN2.y, -vN2.x); \n"
      "      v_join = 0.0; \n"
      "    } \n"
      "    else if(index > 14.9 && index < 17.9) { \n"
      "      v_vertex_mp = v - vMiterL; \n"
      "      vec2 vNB = normalize( vMiterR - vMiterL ); \n"
      "      v_plane_n   = vec2(vNB.y, -vNB.x); \n"
      "      v_join = 1.0; \n"
      "    } \n"
      "    else { \n"
      "      v_vertex_mp = v - v1; \n"
      "      v_plane_n   = vec2(vN.y, -vN.x); \n"
      "      v_join = 0.0; \n"
      "    } \n"
      "  } \n"
      "  v_paint_uv  = (v - u_paint_start) * u_paint_ob_size; \n"
      "} \n"
#else
   const char *vs_src =
      "uniform mat4  u_transform; \n"
      "uniform int   u_last_instance; \n"
      "uniform float u_stroke_w; \n"
      "uniform float u_line_miter_limit; \n"
      "uniform vec2  u_paint_start; \n"
      "uniform vec2  u_paint_ob_size; \n"
      " \n"
      "ATTRIBUTE vec2  a_vertex; \n"
      "ATTRIBUTE vec2  a_vertex_n; \n"
      "ATTRIBUTE vec2  a_vertex_nn; \n"
      " \n"
      "VARYING_OUT vec2 v_vertex_mp; \n"
      "flat VARYING_OUT vec2 v_plane_n; \n"
      "flat VARYING_OUT float v_join; \n"
      "VARYING_OUT vec2  v_paint_uv; \n"
      " \n"
      "float intersect(vec2 _v1s, vec2 _v1e, vec2 _v2s, vec2 _v2e, out vec2 _r) { \n"
      "  vec2 vE = _v1e - _v1s; \n"
      "  vec2 vF = _v2e - _v2s; \n"
      "  vec2 vP = vec2(-vE.y, vE.x); \n"
      "  vec2 vG = _v1s - _v2s; \n"
      "  float h = dot(vF, vP); \n"
      "  h = dot(vG, vP) / h; \n"
      "  _r = vF * h; \n"
      "  _r += _v2s; \n"
#ifdef SHADERVG_DIV_PRECISION_NAN_WORKAROUND
      "  if(isnan(_r.x) || isnan(_r.y)) _r = _v2s; \n"
#endif // SHADERVG_DIV_PRECISION_NAN_WORKAROUND
      "  return h; \n"  // (todo) remove return value
      "} \n"
      " \n"
      "void main(void) { \n"
      "  vec2 v1 = a_vertex; \n"
      "  vec2 v2 = a_vertex_n; \n"
      "  vec2 v3 = a_vertex_nn; \n"
      " \n"
      "  vec2 v12 = v2 - v1; \n"
      "  vec2 vN = normalize(v12); \n"
      "  vec2 vD = vN * u_stroke_w; \n"
      "  vec2 v1L = vec2(v1.x + vD.y, v1.y - vD.x); \n"
      "  vec2 v2L = vec2(v2.x + vD.y, v2.y - vD.x); \n"
      "  vec2 v1R = vec2(v1.x - vD.y, v1.y + vD.x); \n"
      "  vec2 v2R = vec2(v2.x - vD.y, v2.y + vD.x); \n"
      " \n"
      "  vec2 v23 = v3 - v2; \n"
      "  vec2 vN2 = normalize(v23); \n"
      "  vec2 vD2 = vN2 * u_stroke_w; \n"
      "  vec2 v2L2 = vec2(v2.x + vD2.y, v2.y - vD2.x); \n"
      "  vec2 v3L = vec2(v3.x + vD2.y, v3.y - vD2.x); \n"
      "  vec2 v2R2 = vec2(v2.x - vD2.y, v2.y + vD2.x); \n"
      "  vec2 v3R = vec2(v3.x - vD2.y, v3.y + vD2.x); \n"
      " \n"
      "  float cz = v12.x * v23.y - v12.y * v23.x; \n"
      " \n"
      "  vec2 vMiterOrig; \n"
      "  vec2 vMiter; \n"
      "  vec2 vMiterL; \n"
      "  vec2 vMiterR; \n"
      "  vec2 vTmp; \n"
      "  float h; \n"
      "  float lenMiter; \n"
      "  float lenMiterRel; \n"
      "  if(cz > 0.0) { \n"
      "    h = intersect(v1L, v2L, v3L, v2L2, vMiterOrig); \n"
      "    vTmp = vMiterOrig - v2; \n"
      "    lenMiter = length(vTmp); \n"
      "    if(lenMiter > u_line_miter_limit) { \n"
      "      lenMiterRel = (u_line_miter_limit / lenMiter); \n"
      "      vMiterL = (vMiterOrig - v2L) * lenMiterRel + v2L; \n"
      "      vMiterR = (vMiterOrig - v2L2) * lenMiterRel + v2L2; \n"
      "    } else { \n"
      "      vMiterL = vMiterOrig; \n"
      "      vMiterR = vMiterOrig; \n"
      "    } \n"
      "  } else { \n"
      "    h = intersect(v1R, v2R, v3R, v2R2, vMiterOrig); \n"
      "    vTmp = vMiterOrig - v2; \n"
      "    lenMiter = length(vTmp); \n"
      "    if(lenMiter > u_line_miter_limit) { \n"
      "      lenMiterRel = (u_line_miter_limit / lenMiter); \n"
      "      vMiterL = (vMiterOrig - v2R) * lenMiterRel + v2R; \n"
      "      vMiterR = (vMiterOrig - v2R2) * lenMiterRel + v2R2; \n"
      "    } else { \n"
      "      vMiterL = vMiterOrig; \n"
      "      vMiterR = vMiterOrig; \n"
      "    } \n"
      "  } \n"
      "  vec2 v; \n"
      " \n"
      "  float index = float(gl_VertexID); \n"
      " \n"
      "  if(index > 13.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 12.9) { \n"
      "    v = (cz > 0.0) ? v2L2 : v2R2; \n"
      "  } \n"
      "  else if(index > 11.9) { \n"
      "    v = vMiterR; \n"
      "  } \n"
      "  else if(index > 10.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 9.9) { \n"
      "    v = vMiterR; \n"
      "  } \n"
      "  else if(index > 8.9) { \n"
      "    v = vMiterL; \n"
      "  } \n"
      "  else if(index > 7.9) { \n"
      "    v = v2; \n"
      "  } \n"
      "  else if(index > 6.9) { \n"
      "    v = vMiterL; \n"
      "  } \n"
      "  else if(index > 5.9) { \n"
      "    v = (cz > 0.0) ? v2L : v2R; \n"
      "  } \n"
      "  else if(index > 4.9) { \n"
      "    v = v1R; \n"
      "  } \n"
      "  else if(index > 3.9) { \n"
      "    v = v2R; \n"
      "  } \n"
      "  else if(index > 2.9) { \n"
      "    v = v1L; \n"
      "  } \n"
      "  else if(index > 1.9) { \n"
      "    v = v2R; \n"
      "  } \n"
      "  else if(index > 0.9) { \n"
      "    v = v2L; \n"
      "  } \n"
      "  else { \n"
      "    v = v1L; \n"
      "  } \n"
      " \n"
      "  if(gl_InstanceID == u_last_instance && index > 5.9) { \n"
      "    gl_Position = vec4(0,0,0,1); \n"  // skip last line joint
      "    v_plane_n = vec2(0,0); \n"
      "    v_join = 0.0; \n"
      "  } else { \n"
      "    gl_Position = u_transform * vec4(v,0,1); \n"
      "    if(index > 11.9) { \n"
      "      v_vertex_mp = v - v2; \n"
      "      v_plane_n   = vec2(vN2.y, -vN2.x); \n"
      "      v_join = 0.0; \n"
      "    } \n"
      "    else if(index > 8.9 && index < 11.9) { \n"
      "      v_vertex_mp = v - vMiterL; \n"
      "      vec2 vNB = normalize( vMiterR - vMiterL ); \n"
      "      v_plane_n   = vec2(vNB.y, -vNB.x); \n"
      "      v_join = 1.0; \n"
      "    } \n"
      "    else { \n"
      "      v_vertex_mp = v - v1; \n"
      "      v_plane_n   = vec2(vN.y, -vN.x); \n"
      "      v_join = 0.0; \n"
      "    } \n"
      "  } \n"
      "  v_paint_uv  = (v - u_paint_start) * u_paint_ob_size; \n"
      "} \n"
#endif // SHADERVG_HIRES_GEO
      ;

   // ------------ fragment shader ------------
   const char *fs_src =
      "uniform vec4      u_color_fill; \n"
      "uniform vec4      u_color_stroke; \n"
      "uniform float     u_decal_alpha; \n"
      "uniform float     u_stroke_w; \n"
      "uniform float     u_aa_range; \n"
#ifdef SHADERVG_DEBUG_FRAG
      "uniform float     u_debug; \n"
#endif // SHADERVG_DEBUG_FRAG
      "uniform sampler2D u_paint_tex; \n"
      "uniform vec2      u_paint_ndir; \n"
      " \n"
      "VARYING_IN vec2  v_vertex_mp; \n"
      "flat VARYING_IN vec2  v_plane_n; \n"
      "flat VARYING_IN float v_join; \n"
      "VARYING_IN vec2  v_paint_uv; \n"
      " \n"
      "void main(void) { \n"
      "  float a; \n"
      "  float d = abs(dot(v_vertex_mp, v_plane_n)); \n"
      "  if(v_join > 0.0) { \n"
      "    a = smoothstep(0.0, u_aa_range, d); \n"
      "  } \n"
      "  else { \n"
      "    a = 1.0 - smoothstep(u_stroke_w - u_aa_range, u_stroke_w, d); \n"
      "  } \n"
      "  vec2 uv; \n"
      "  uv.x = v_paint_uv.x * u_paint_ndir.x - v_paint_uv.y * u_paint_ndir.y; \n"
      "  uv.y = v_paint_uv.x * u_paint_ndir.y + v_paint_uv.y * u_paint_ndir.x; \n"
      "  vec4 cp = TEXTURE2D(u_paint_tex, uv); \n"
      "  FRAGCOLOR = vec4(mix(u_color_fill.rgb, u_color_stroke.rgb * cp.rgb, u_color_stroke.a * cp.a * u_decal_alpha), u_color_fill.a * a); \n"
#ifdef SHADERVG_DEBUG_FRAG
      "  if(u_debug > 0.0) { \n"
      "    FRAGCOLOR = vec4(uv.x, a, uv.y, 1.0); \n"
      "  } \n"
#endif // SHADERVG_DEBUG_FRAG
      "} \n"
      ;

   sBool validateShapeShader(void) {
      return
            (-1 != shape_a_vertex)
         && (-1 != shape_a_vertex_n)
         && (-1 != shape_a_vertex_nn)
         && (-1 != shape_u_transform)
         && (-1 != shape_u_last_instance)
         && (-1 != shape_u_color_fill)
         && (-1 != shape_u_color_stroke)
         && (-1 != shape_u_decal_alpha)
         && (-1 != shape_u_stroke_w)
         && (-1 != shape_u_aa_range)
         && (-1 != shape_u_line_miter_limit)
         && (-1 != shape_u_paint_start)
         && (-1 != shape_u_paint_ob_size)
         && (-1 != shape_u_paint_ndir)
         && (-1 != shape_u_paint_tex)
         ;
   }

   sBool onOpen(void) {
      if(createShapeShader(vs_src, fs_src))
      {
         return YAC_TRUE;
      }
      return YAC_FALSE;
   }

   // (note) see also: shadervg.cpp:loc_DrawLineStripFlatAAVBOPaint()

};
