#
# Makefile for tkmidipipe plugin on Windows / Visual C++ platform
#
# (c) 2014-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkmidipipe

EXTRAFLAGS= -DTKMIDIPIPE_BUILD

EXTRALIBS=

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
