#
# Makefile for tkmidipipe plugin on Linux / GCC / Clang platform
# 
# (c) 2014-2026 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkmidipipe

EXTRAFLAGS= -std=c++0x -DTKMIDIPIPE_BUILD

EXTRALIBS= -lm

PLAF_OBJ= 

include make.objects

include ../build_linux.mk
