#
# Makefile for tkmidipipe plugin + Microsoft Visual C++ 2003 / 2005 / 2008 / 2013 ToolKit
# 
# (c) 2014-2024 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkmidipipe

EXTRAFLAGS= -DTKMIDIPIPE_BUILD

EXTRALIBS=

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
