#
# Makefile for tkmidipipe plugin on macOS / GCC platform
# 
# (c) 2014-2024 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tkmidipipe

EXTRAFLAGS= -std=c++0x -DTKMIDIPIPE_BUILD

EXTRALIBS= -lm

PLAF_OBJ= 

include make.objects

include ../plugin_macos.mk
