// ---- ying_midipipe.h: auto generated by YInG - the YAC interface generator (Fri, 13/Jun/2025 11:28:29)
extern sUI clid_HostMIDIEvents;
class HostMIDIEvents;
extern sUI clid_MIDIPipe;
class MIDIPipe;
extern sUI clid_MIDIPipeDevice;
class MIDIPipeDevice;
extern sUI clid_MIDIPipeEvent;
class MIDIPipeEvent;
extern sUI clid_MIDIPipeFrame;
class MIDIPipeFrame;
extern sUI clid_MIDIPipeNode;
class MIDIPipeNode;
extern sUI clid_MIDIPipeNodeScriptProxy;
class MIDIPipeNodeScriptProxy;
extern sUI clid_MIDIPipeRoot;
class MIDIPipeRoot;
extern sUI clid_ModInputFilter;
class ModInputFilter;
