#
# Makefile for tksidplay2 plugin on Linux / GCC / Clang platform
#
# (c) 2003-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tksidplay2

SIDPLAY=sidplay-libs-2.1.1

EXTRAFLAGS= -DHAVE_UNIX -DHAVE_IOS_OPENMODE -I"$(SIDPLAY)/libsidplay/include/" -I"$(SIDPLAY)/libsidplay/include/sidplay" -I"$(SIDPLAY)/builders/resid-builder/include/" -I"$(SIDPLAY)/builders/resid-builder/include/sidplay/builders" -I"$(SIDPLAY)"

EXTRALIBS=

PLAF_OBJ=

include make.objects

# resid uses .cc file prefix
.cc.o:
	$(CC) $(CPPFLAGS) $(OPTFLAGS_SIZE) -c $< -o "$@"

include ../build_linux.mk
