#
# Makefile for tkgmp on macOS / Clang platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_macos.mk

PLUGIN=tkgmp

EXTRAFLAGS=

EXTRALIBS= -lgmp

PLAF_OBJ=

include make.objects

include ../build_macos.mk
