#
# Makefile for tkgmp on Linux / GCC platform
# 
# (c) 2008-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_linux.mk

PLUGIN=tkgmp

EXTRAFLAGS= 

EXTRALIBS= -lgmp

PLAF_OBJ=

include make.objects

include ../plugin_linux.mk
