#
# Makefile for tkgmp plugin on Windows platform
# 
# (c) 2003-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkgmp

# (todo) add gmp includes/libs
EXTRAFLAGS= 

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
