#
# Makefile for tkgmp on Linux / GCC / Clang platform
#
# (c) 2008-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_linux.mk

PLUGIN=tkgmp

EXTRAFLAGS=

EXTRALIBS= -lgmp

PLAF_OBJ=

include make.objects

include ../build_linux.mk
