#
# Makefile for tkgmp on macOS / GCC platform
# 
# (c) 2008-2023 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_macos.mk

PLUGIN=tkgmp

EXTRAFLAGS= 

EXTRALIBS= -lgmp

PLAF_OBJ=

include make.objects

include ../plugin_macos.mk
