#
# Makefile for tkmidi plugin + Microsoft Visual C++ 2003 / 2005 ToolKit
# 
# (c) 2007-2009 Bastian Spiegel <bs@tkscript.de> 
#

include ../install_msvc.mk

PLUGIN=tkmidi

EXTRAFLAGS= 

EXTRALIBS= winmm.lib

PLAF_OBJ= 

include make.objects

include ../plugin_msvc.mk
