#
# Makefile for tkmidi plugin on Windows / Visual C++ platform
#
# (c) 2007-2026 Bastian Spiegel <bs@tkscript.de>
#

include ../install_msvc.mk

PLUGIN=tkmidi

EXTRAFLAGS=

EXTRALIBS= winmm.lib

PLAF_OBJ=

include make.objects

include ../build_msvc.mk
