#
# Makefile for tkportaudio<alsa_async> plugin on Linux / GCC platform
# 
# (c) 2010-2023 Bastian Spiegel <bs@tkscript.de> 
#
#

include ../install_linux.mk

PLUGIN=tkportaudio

EXTRAFLAGS=

ifeq ($(CROSS_TARGET),OMAP3)
EXTRAFLAGS += -DFORCE_PAINT16 -DPANDORA_LOWLATENCY_HACK
endif

EXTRALIBS= -lasound

include make.objects

include ../plugin_linux.mk
